### ISSUE TITLE
[hi] Localize `Cloud computing`

### ISSUE THREAD

**Issue by octonawish-akcodes** [cncf/glossary#1005]
### Please describe why this term needs to be added

I want to localize cloud computing term to hindi localization.

**Comment by abh139** [comment]
Don't we have the self assign system, @jihoon-seo

**Comment by jihoon-seo** [comment]
@abh139 it seems that we don't have a self assign system.

BTW, it seems that you are already assigned to another issue: #771.

We can assign you one term at a time, so if you want to work on this, please unassign yourself from the issue #771,
or please resolve #771 and then you might be able to be assigned on this.

**Comment by bishal7679** [comment]
@Garima-Negi @anubha-v-ardhan Can you assign me for this issue?

**Comment by Garima-Negi** [comment]
> @Garima-Negi @anubha-v-ardhan Can you assign me for this issue?

Hi Bishal, I believe you already have an issue assigned to you. We only assign 1 issue to a person at a time

**Comment by bishal7679** [comment]
@Garima-Negi Actually I have already made a PR for that assigned issue. 
Can You please review it so that I can work on another issue?

**Comment by Garima-Negi** [comment]
Sure whenever the reviewers have time they will review.

**Comment by taniaduggal** [comment]
May I work on this? @jihoon-seo

**Comment by anubha-v-ardhan** [comment]
We can only assign this to one person.

@octonawish-akcodes, since you opened this issue and showed interest (https://github.com/cncf/glossary/issues/1005#issuecomment-1170880428), Do you wish to work on this? else we can assign the issue to next person on first come first serve basis

**Comment by bishal7679** [comment]
@anubha-v-ardhan I would like to work on that after merging [hi] version_control.md 
Could you pls assign me this issue?

**Comment by octonawish-akcodes** [comment]
@anubha-v-ardhan Please assign this to someone else, I am tackling some issues in my local configuration in rebasing so I am fixing that, please assign this to someone else.

**Comment by anubha-v-ardhan** [comment]
> Can I work on this issue?

@devsachinsharma Are you still interested in working on this issue?

**Comment by devsachinsharma** [comment]
@anubha-v-ardhan  Yes, I'm interested. But can you please review the remaining part of this issue https://github.com/cncf/glossary/pull/1082 . Thank you.

**Comment by Garima-Negi** [comment]
@shivam-sharma7 please comment on this issue so that I can assign it to you.
your PR has been reviewed recently

**Comment by shivam-sharma7** [comment]
Hey @Garima-Negi can you assign me?

**Comment by sayantani11** [comment]
@shivam-sharma7 done!

**Comment by anubha-v-ardhan** [comment]
Resolved by #1250
