### ISSUE TITLE
[New term] `Docker` for `hindi`

### ISSUE THREAD

**Issue by Omkar0114** [cncf/glossary#1030]
#### What this term is about? (briefly)
-  Docker is a container platform that allows you to build, test and deploy applications quickly.
#### Why this term needs to be added? (briefly) 
- Using docker can help you ship your code faster, and gives you control over your applications. You can deploy your applications on containers that make it easier for them to be deployed, scaled, perform rollbacks and identify issues. So it is an important term that should have to be added.
#### Languages that use this term? (briefly)
- English and Hindi

**Comment by AmanSarraf** [comment]
I want to work on this issue

**Comment by Garima-Negi** [comment]
this term docker is is not in the English glossary . please check: https://glossary.cncf.io/
the localization effort takes these finalized terms from the english glossary and then proceeds to localize. in this case  docker isn't in the glossary hence cannot be in the Hindi glossary. 
feel free to pick up another missing term that doesn't have a open issue/pr though

**Comment by Omkar0114** [comment]
Okay. Sure @Garima-Negi Thanks for helping out :)
