### ISSUE TITLE
Updating the wordlist folder with the new word

### ISSUE THREAD

**Issue by Omkar0114** [cncf/glossary#1032]

**Comment by Omkar0114** [comment]
Made PR #1033

**Comment by iamNoah1** [comment]
@Omkar0114 We need you to follow the intended process here :) You opened an issue without using any template. This makes it harder for the maintainers to process such an issue. Also, you opened a PR before the issue got accepted.

**Comment by Omkar0114** [comment]
Okay. But this issue is not related to any template so I opened a blank issue! So what should I do now? Should I close the PR now then?

**Comment by iamNoah1** [comment]
If this issue is not related to any template, it may be an indicator that is not needed at all :) I would say we do not need that right now. Updating the wordlist is only needed if the definition for a term contains a word that is not common and not included in the wordlist yet.

**Comment by Omkar0114** [comment]
Okay, Thanks a lot for suggesting :)
