### ISSUE TITLE
[Portuguese] Add tags to the localized terms 

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#1040]
Each definition file in `content/pt-br` needs to contain a field called `tags:[]` based in the original content from `content/en`.
This issue is to update all the files in `content/pt-br`, you can see an example [here](https://github.com/cncf/glossary/blob/main/content/en/abstraction.md?plain=1#L5).

**Ps.:** The tags should be translated to Portuguese as well.

**Comment by anacunha** [comment]
@edsoncelio should we translate the tags as well or no?

Based on the example you gave:

a) `tags: ["architecture", "", ""]`
b) `tags: ["arquitetura", "", ""]`

**Comment by edsoncelio** [comment]
> @edsoncelio should we translate the tags as well or no?
> 
> Based on the example you gave:
> 
> a) `tags: ["architecture", "", ""]`
> b) `tags: ["arquitetura", "", ""]`

Good question as I think yes but to confirm I'll check with the other's team's.

**Comment by edsoncelio** [comment]
> > @edsoncelio should we translate the tags as well or no?
> > Based on the example you gave:
> > a) `tags: ["architecture", "", ""]`
> > b) `tags: ["arquitetura", "", ""]`
> 
> Good question as I think yes but to confirm I'll check with the other's team's.

I was looking in this PR https://github.com/cncf/glossary/pull/1037 from Korean team looks like we should translate the tags too  @anacunha :)

**Comment by anacunha** [comment]
PR submitted.

Here's the proposed translation for the existing tags:

- `application` - aplicação
- `architecture` - arquitetura
- `fundamentals` - fundamentos
- `infrastructure` - infraestrutura
- `methodology` - metodologia
- `networking` - redes
- `platform` - plataforma
- `security` - segurança
