### ISSUE TITLE
[Portuguese] Translate i18n strings to use tags

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#1048]
Translate the i18n strings to Portuguese to fix this error below when we have tags:
<img width="481" alt="image" src="https://user-images.githubusercontent.com/5833278/177455804-e8c6e6ac-8fb1-40e8-8f36-eee584c48938.png">

You can see [here](https://github.com/cncf/glossary/blob/971043e3baac61c86124885465a2e0876cc8a03a/i18n/en.toml#L21) the strings that need to be translated.

The translated strings need to be added to the [this file](https://github.com/cncf/glossary/blob/main/i18n/pt-br.toml).

**Comment by tinniaru3005** [comment]
Hey, I want to work on this issue. Can you please assign it to me?

**Comment by edsoncelio** [comment]
> Hey @edsoncelio , I am new to the community and want to work on this issue. Can you please assign it to me?

Hi @tinniaru3005 welcome to the community :) 
We already have a PR opened to this issue - but you can join to the glossary channel (CNCF slack) on slack and ask for another issue, thank you!

**Comment by tinniaru3005** [comment]
> > Hey @edsoncelio , I am new to the community and want to work on this issue. Can you please assign it to me?
> 
> Hi @tinniaru3005 welcome to the community :) We already have a PR opened to this issue - but you can join to the glossary channel (CNCF slack) on slack and ask for another issue, thank you!

Sure. Thanks :)
