### ISSUE TITLE
[New term] `Edge Computing`

### ISSUE THREAD

**Issue by gdenn** [cncf/glossary#1064]
#### What this term is about? (briefly)

Edge computing is a form of computing that happens outside of cloud systems. Edge computing utilizes so called "edge devices" that are physical devices located outside of cloud infrastructure premises. 

#### Why this term needs to be added? (briefly) 

Edge computing can contribute to cloud systems by exchanging data from the edge to the cloud infrastructure as it is often the case in IoT projects and other projects that demand hardware to be present on specific locations.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by CathPag** [comment]
Apologies for the delay, @gdenn. We weren't sure if this should be included or not and were always pushing the decision to the next meeting. While it is not necessarily a cloud native term, we decided to accept it because this definition will be valuable for the user in a cloud native context. It's been a while since you submitted this. Are you still interested in working on it?

**Comment by PrathyushaModala** [comment]
Hi Guys,
Would like to take up this issue.
cc @CathPag @gdenn

**Comment by iamNoah1** [comment]
@CathPag I would say we can assign this to @PrathyushaModala ad @gdenn has not been very responsive nor reliable in the past :/

**Comment by CathPag** [comment]
Sure, here you go, @PrathyushaModala

**Comment by PrathyushaModala** [comment]
https://github.com/cncf/glossary/pull/1467
Here's the pull request I made referencing this issue, please review it.

**Comment by PrathyushaModala** [comment]
#1467 
Here's the pull request I made, @CathPag  ,@JasonMorgan ,@seokho-son , @iamNoah1 , @jihoon-seo please do review for the pull request so that I can merge it.
