### ISSUE TITLE
[New term] `Debugging` for `Hindi`

### ISSUE THREAD

**Issue by Omkar0114** [cncf/glossary#1067]
#### What this term is about? (briefly)
- Debugging is the process of finding & resolving bugs(errors) from a computer program, software, or system to get the desired result.
#### Why this term needs to be added? (briefly) 
- Localizing this term in `Hindi` will help `Hindi` folks learn about this term in their native language.

Link here:- https://glossary.cncf.io/debugging/

**Comment by Omkar0114** [comment]
I would like to work on this term. Anyone can review it and can assign it to me? :)
@Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava

**Comment by Garima-Negi** [comment]
Completed. PR is merged.

**Comment by Omkar0114** [comment]
Thank you 🥳
