### ISSUE TITLE
[New term] `Multi-tenancy`

### ISSUE THREAD

**Issue by sergeyborovoy** [cncf/glossary#1073]
#### What this term is about? (briefly)
- This is about a single instance of software serving multiple tenants
#### Why this term needs to be added? (briefly) 
- Important for the SaaS world and therefore for the Cloud in general

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by CathPag** [comment]
Thanks for your suggestion. Although this term is not cloud native specific, it is an important term to understand cloud native concepts, which is why we believe it should be part of the glossary. Are you still interested in working on this, @sergeyborovoy?

**Comment by sergeyborovoy** [comment]
Yes, will be happy to.  Could you please provide the link to the description of the collaboration / sumbission procedure or gudelines?...

**Comment by CathPag** [comment]
Sure, you can find the "how to contribute" and "style guide" on the Glossary nav bar >> https://glossary.cncf.io/

**Comment by CathPag** [comment]
Hi @sergeyborovoy, just wondering if you still wanted to help with these :)

**Comment by CathPag** [comment]
Oh, right! This one can be closed. Sorry, Kubecon disrupts everything :) I'll close this issue and please feel free to work on the other one (if you are interested). Again, your contribution was great, and we'd love to see more if you're up for it :)

**Comment by sergeyborovoy** [comment]
Hi @CathPag Let's find out first if @FavourDaniel is still working on the "stateless apps" or has she given up.  We don't want to yank stuff from under people, do we? :)

**Comment by FavourDaniel** [comment]
@sergeyborovoy I would be sending in an update on it today or tomorrow
