### ISSUE TITLE
[New term] `tenant`

### ISSUE THREAD

**Issue by sergeyborovoy** [cncf/glossary#1074]
#### What this term is about? (briefly)
- A tenant is a group of users sharing common access to a software instance
#### Why this term needs to be added? (briefly) 
- It is important for understanding _multi_-tenancy, which in its turn is an important Cloud term 

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by CathPag** [comment]
After some deliberation with the maintainers, we decided not to include this term. It is not cloud native specific, and what people need to know to understand cloud native concepts can be covered in the multi-tenancy definition.
