### ISSUE TITLE
Convert auto-scaling entry to Property format

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#108]
The [auto-scaling entry](https://github.com/cncf/glossary/blob/main/definitions/auto_scaling.md) should be converted to the property format. View [the style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

The current definition seems to be stretching to fit with our original, what it is, problem it addresses, and how it helps.

**Comment by gedalyahreback** [comment]
Just saw the CNCF announcement of the glossary and looking at "good first issue" labels.

I agree with you that the entry seems to be stretching, but isn't auto-scaling a concept rather than a property? If that's the case, I can edit it (I handle the blog at Logz.io, writing and editing this stuff is my forte).

**Comment by JasonMorgan** [comment]
@gedalyahreback I'd love that! Assigned you the issue.

**Comment by Ayush7614** [comment]
Hey @JasonMorgan i would like to work on the issue Please assign me

**Comment by sudhxnva** [comment]
Hi @JasonMorgan , I noticed that the issue has already been addressed with the PRs #109 and #95. Is there anything else that needs attention here?

**Comment by CathPag** [comment]
@Ayush7614 my apologies. Looks like we missed your message a few days ago. (@sudhxnva, Ayush claimed this first and you already claimed one term. Please tackle that first before picking a new term)

Ayush, first of all, thanks for helping out. We are looking for two things:

1. Update the format according to the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md).
2. Make sure the definitions are correct and complete.

**Comment by Pravenn18** [comment]
Hey,can you guys tell me how should i contribute here,i mean which language i need to master!!!

**Comment by CathPag** [comment]
Sorry, @sudhxnva. We got so many issue claims, I didn't properly read yours. Yes, this one is done and will be closed. @Pravenn18, this glossary is in English. There will be efforts to translate it but that hasn't been started yet.
