### ISSUE TITLE
[New term] `FinOps`

### ISSUE THREAD

**Issue by wahlax-llc** [cncf/glossary#1098]
#### What this term is about? (briefly)
- See https://www.finops.org/introduction/what-is-finops/
- FinOps is lingo for the discipline of cloud spend

#### Why this term needs to be added? (briefly) 
-  Similar to DevOps or DevSecOps but more cloud specific

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [ ] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by devdude101** [comment]
Hey,
Can I take this issue?
I have been working in Fintech for sometime so can write about finops.

**Comment by wahlax-llc** [comment]
@devdude101  Fine by me as long as it is a desired term. I did not think I could do it justice. Believe there is an acceptance to happen first that will change the issue status from "triage/awaiting" to something else. This was my first term proposal, so I am still learning the intended process.

**Comment by CathPag** [comment]
Thanks for your suggestion. After some deliberation with the maintainers, we decided not to include this term. This is vertical-specific, and we aim to focus on general cloud native terms. We do appreciate the submission, though.
