### ISSUE TITLE
[Portuguese] `` for `lang/pt`

### ISSUE THREAD

**Issue by DonatoHorn** [cncf/glossary#1101]
### Please describe why this term needs to be updated

I reviewed 19 pages, and made suggestions on them.

**Comment by edsoncelio** [comment]
Hi @DonatoHorn some points here:
* The bot commands like `/assign` doesn’t work here 
* could you describe better your issue? You can describe which pages you want to fix 
* If are more like suggestions, it's better to ask in our slack channel `#glossary-localization-portuguese` and then we can discuss and agree or not 
* The issue title needs to be something more meaningful, could you change that?

Thank you :)
