### ISSUE TITLE
[hi] Localize term `site_reliability_engineering` into `Hindi`

### ISSUE THREAD

**Issue by taniaduggal** [cncf/glossary#1130]
localization of `site_reliabilty_engineering` into Hindi
  

-   https://glossary.cncf.io/site-reliability-engineering/

**Comment by taniaduggal** [comment]
I want to work on this :) @anubha-v-ardhan

**Comment by Garima-Negi** [comment]
HI @taniaduggal , thank you for creating this issue. It has now been assigned to you!

**Comment by taniaduggal** [comment]
@anubha-v-ardhan Please take a look at my PR
