### ISSUE TITLE
Couldn't find 'Become an Approver' page

### ISSUE THREAD

**Issue by NitishKumar06** [cncf/glossary#1141]
While going through the following page (https://glossary.cncf.io/contributor-ladder/#2-approvers) , a text under 'Approvers' say to look at 'Become an Approver' for instructions. I was not able to find the link. 

Is the following page even added yet? If Yes, please let me know about the link else add a new page for 'Becoming an approver'

**Comment by jihoon-seo** [comment]
Here is the link to the "Becoming an Approver": https://glossary.cncf.io/contributor-ladder/#becoming-an-approver

**Comment by NitishKumar06** [comment]
Thanks @jihoon-seo , the following issue is resolved now!
