### ISSUE TITLE
[New term] `Changelog`

### ISSUE THREAD

**Issue by arunkarthicknm** [cncf/glossary#1144]
#### What this term is about? (briefly)
- It explains what changelog actually is.
#### Why this term needs to be added? (briefly) 
- Because, there are lot of misconceptions and unawareness on changelog and it needs to be addressed.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by arunkarthicknm** [comment]
Shall I work on this term?

**Comment by iamNoah1** [comment]
@arunkarthicknm I admire your enthusiasm, but apparently you checked 2 of the checkboxes without really paying attention to them. 
IMHO your suggested term does not fit the cloud native definition not is it essential to understand cloud native terms. If you think it does, please explain why :) 
You opened a PR without being patient and wait for the term to be accepted and assigned to you. That is not how it works :)

**Comment by arunkarthicknm** [comment]
Got it, thanks @iamNoah1 :)
