### ISSUE TITLE
[New term] `Theme Switcher` for `Dark and Light mode`

### ISSUE THREAD

**Issue by mandeepsng** [cncf/glossary#1160]
#### What this term is about? (briefly)
- This is about adding a theme switcher (**new feature, these days trending on every website**)
#### Why this term needs to be added? (briefly) 
**- Because the website's dark and light modes, affect our eyes so users can switch according to their lightning.** 
#### Languages that use this term? (briefly)
- We can implement this new feature on the frontend side by using **react or jQuery**.

Feature demo = [https://mandeepdev.vercel.app/](https://mandeepdev.vercel.app/)

**Comment by mandeepsng** [comment]
by mistake I added here in **new term non-english**
Please ignore from here, I added on **new term english**

**Comment by seokho-son** [comment]
Hi @mandeepsng 
Thank you for the suggestion.

You can close this issue and open a new issue using the right issue template.

With the issue template (`Request to add a new term (English)`),
You need to provide more descriptions why the suggested term is needed to CNCF Glossary.

In addition, I think `Theme Switcher` cannot be accepted as a new term for Cloud Native. (I am one of the maintainers)
The suggested term fits the cloud native definition or is essential to understanding cloud native terms. 
(We hope to avoid adding general or broad terminologies)

**Comment by anubha-v-ardhan** [comment]
Superseded by #1161
