### ISSUE TITLE
[New term] Theme Switcher for Dark and Light mode

### ISSUE THREAD

**Issue by mandeepsng** [cncf/glossary#1161]
#### What this term is about? (briefly)
- This is about adding a theme switcher (**new feature, these days trending on every website**)
#### Why this term needs to be added? (briefly) 
- **Because the website's dark and light modes, affect our eyes so users can switch according to their lightning.**

Feature demo = [https://mandeepdev.vercel.app/](https://mandeepdev.vercel.app/)

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [ ] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by seokho-son** [comment]
Hi @mandeepsng

I think `Theme Switcher` is a too general term and not suitable as a cloud native term.
Why do you think `Theme Switcher` fits the cloud native definition ?

**Comment by mandeepsng** [comment]
Because the website's dark and light modes, affect our eyes so users can switch according to their lightning and
hard to read when light off, dark mode is very useful at that case.
and this is cool trending feature in now days.

**Comment by jihoon-seo** [comment]
I guess that what @mandeepsng suggests is the feature in the CNCF Glossary website that toggles dark mode and light mode, and that he just picked an wrong issue template.

**Comment by mandeepsng** [comment]
Hi **@jihoon-seo** 
Thank you for your reply.
So what should be an exact template for this?

**Comment by jihoon-seo** [comment]
For now and for this case, you can open a blank issue with no issue template:
![image](https://user-images.githubusercontent.com/46767780/183580965-8af2367d-dd25-4647-8e62-5473b363ffb5.png)

**Comment by mandeepsng** [comment]
thank you 
should I close this now?

**Comment by jihoon-seo** [comment]
You can edit this issue, but it might be easier to close this and open a new one.

**Comment by mandeepsng** [comment]
ok
