### ISSUE TITLE
[New term] `Containers`

### ISSUE THREAD

**Issue by HenokB** [cncf/glossary#1165]
#### What this term is about? (briefly)
- Containers, part of a more general software approach called cloud-native, are small software packages that, ideally, perform a small, well-defined task. Container images include all the software, including settings, libraries, and other dependencies, needed for them to run.
#### Why this term needs to be added? (briefly) 
- In the book, Cloud Native Patterns, author Cornelia Davis observes, "Containers are a great enabler of cloud-native software." The Cloud Native Computing Foundation places microservice containerization as the first step in their Cloud-Native Trail Map - guidance for enterprises beginning their cloud-native journey.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by iamNoah1** [comment]
Thanks, @HenokB, but the term Containers already exists in the glossary :) See: https://glossary.cncf.io/container/
