### ISSUE TITLE
[New term] `Portability` for `Hindi`

### ISSUE THREAD

**Issue by Omkar0114** [cncf/glossary#1166]
#### What this term is about? (briefly)
-  Software portability is the possibility to use the same software in different environments.

#### Why this term needs to be added? (briefly) 
- Localizing this term in Hindi will help Hindi folks learn about this term in their native language.

Link here: https://glossary.cncf.io/portability/

**Comment by Omkar0114** [comment]
I would like to work on this term. Anyone can review it and can assign it to me? :)
@Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava

**Comment by anubha-v-ardhan** [comment]
Thank you @Omkar0114 :)

**Comment by Omkar0114** [comment]
Thanks for assigning me @anubha-v-ardhan :)
