### ISSUE TITLE
[New term] `Abstraction` for `French`

### ISSUE THREAD

**Issue by HenokB** [cncf/glossary#1168]
#### What this term is about? (briefly)
- In the context of computing, an abstraction is a representation that hides specifics from a consumer of services (a consumer being a computer program or human), making a system more generic and thus easily understood.
#### Why this term needs to be added? (briefly) 
- Localizing this term in French will help French-speaking folks learn about this term in their native language.

Link here - https://glossary.cncf.io/abstraction/

**Comment by HenokB** [comment]
Hello, I would like to work on this issue. Anyone can review it and can assign it to me? :)

**Comment by anubha-v-ardhan** [comment]
Hi @HenokB,
You can contact the french localization team theough the channel `#glossary-localization-french` on CNCF Slack. The people mentioned here are responsible for Hindi localization.

**Comment by iamNoah1** [comment]
@HenokB are you a french native speaker?

**Comment by HenokB** [comment]
> @HenokB are you a french native speaker?

No, I'm not a native speaker.

**Comment by iamNoah1** [comment]
I admire your enthusiasm, but this is not how it works. You have to be a native speaker in order to localize a term. This should be obvious. Please make sure you read the contribution guide: https://glossary.cncf.io/contribute/

**Comment by sestegra** [comment]
I would like to work on this issue . Please assign it to me.
