### ISSUE TITLE
[New term] `Agile Software Development` for `French`

### ISSUE THREAD

**Issue by HenokB** [cncf/glossary#1169]
#### What this term is about? (briefly)
- It's about Agile software development which is a set of practices that emphasize iterative development cycles and self-organizing teams.
#### Why this term needs to be added? (briefly) 
- Localizing this term in French will help French-speaking folks learn about this term in their native language.
Link here-  https://glossary.cncf.io/agile-software-development/

**Comment by HenokB** [comment]
Hello, I would like to work on this issue. Anyone can review it and can assign it to me?
@Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava

**Comment by anubha-v-ardhan** [comment]
Hi @HenokB,
You can contact the french localization team theough the channel #glossary-localization-french on CNCF Slack. The people mentioned here are responsible for Hindi localization.

**Comment by sestegra** [comment]
@Krast76  I would like to work on this issue . Please assign it to me.
