### ISSUE TITLE
[hi] `Devsecops` for `Hindi`

### ISSUE THREAD

**Issue by octonawish-akcodes** [cncf/glossary#1183]
#### Why this term needs to be updated? (briefly) 
- Translation of Devsecops into Hindi localization.

**Comment by octonawish-akcodes** [comment]
I can work on this

**Comment by anubha-v-ardhan** [comment]
There was #760 working on this term but was closed for some reason. You can use that PR for reference :)

**Comment by anubha-v-ardhan** [comment]
@SahityaGupta25 worked on this Devsecops previously, maybe you can collaborate with him and open a new PR.

**Comment by SahityaGupta25** [comment]
@octonawish-akcodes  Sure
