### ISSUE TITLE
Filterable list of Glossary terms

### ISSUE THREAD

**Issue by cjyabraham** [cncf/glossary#1188]
Allow for filtering glossary terms by tag, similar to [the Kubernetes search UI](https://kubernetes.io/docs/reference/glossary/?fundamental=true).

Maybe provide access to this page using an "Advanced Search" link directly below the regular search input in the sidebar. Also, each tag on the site could link to this page with that tag selected.

Use-cases from @CathPag:
- We want people to be able to filter terms. People may want to see all fundamental terms if they are just getting started and read those first. E.g,. abstraction, cluster, container, nodes. You need to understand those concepts before reading the rest...we may need an intermediate category for this to be really useful.
- Same thing for the tags. Maybe I want to learn about architecture and read all related terms to that to get a better sense of it.
- For technology, concept, property there is no strong case. It would rather be for consistency. But for level and tags, it does make a lot of sense.

**Comment by CathPag** [comment]
As mentioned in the other issue, I really like the Kubernetes behavior

**Comment by cjyabraham** [comment]
[Done](https://github.com/cncf/glossary/pull/1715)
