### ISSUE TITLE
Text in Microservices not clear.

### ISSUE THREAD

**Issue by NitishKumar06** [cncf/glossary#1189]
#### Why this term needs to be updated? (briefly)
- 
The following page (https://glossary.cncf.io/microservices/#problem-it-addresses) explains the problems that a monolith architecture faces and what are the benefits of microservices.

Look at the following line: _ Monolithic applications also make it easy for developers to succumb to design pitfalls._ The word 'Because' has been used after .  I believe it would be better if we slightly change the English signs to make the text look cleaner and more accurate.

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [X] I want to work on this suggestion. (If not checked, maintainers will assign another volunteer)

### (Note)

I'd be happy to work on this following issue.

**Comment by iamNoah1** [comment]
Thanks @NitishKumar06 for the suggestion. Can you make a more concrete suggestion. You could open a PR if you like.

**Comment by NitishKumar06** [comment]
Hey @iamNoah1 after going through the docs once again, I'm satisfied with the contents. The changes mentioned above don't hold much importance.
