### ISSUE TITLE
[Localize] `Microservice` for `Hindi`

### ISSUE THREAD

**Issue by NitishKumar06** [cncf/glossary#1190]
#### Why this term needs to be updated? (briefly) 
- 
The following page: https://glossary.cncf.io/microservices/ needs to be localized into Hindi which is necessary for the Indian folks who are comfortable in understanding the concept of CNCF in the Hindi language.

Note: I'd love to work on this issue and add the new page as well. Thank you!

**Comment by anubha-v-ardhan** [comment]
@NitishKumar06 #1139 is already open localizing this term, We'll have to close this issue.
