### ISSUE TITLE
[Portuguese] Localize 'Event-Driven Architecture'

### ISSUE THREAD

**Issue by MrErlison** [cncf/glossary#1206]
Localize [https://glossary.cncf.io/event-driven-architecture/](https://glossary.cncf.io/event-driven-architecture/)

**Comment by pasimoes** [comment]
I would be happy to work on this content.

**Comment by edsoncelio** [comment]
> I would be happy to work on this content.

Great, thank you! I'll assign it to you, If you have any questions let us know at the slack channel :)
