### ISSUE TITLE
[Portuguese] Localize 'Function as a Service (FaaS)'

### ISSUE THREAD

**Issue by MrErlison** [cncf/glossary#1207]
Localize [https://glossary.cncf.io/function-as-a-service/](https://glossary.cncf.io/function-as-a-service/)

**Comment by pasimoes** [comment]
I would be happy to work on this content.

**Comment by pasimoes** [comment]
The translation is done but to be more instructive for the reader I add a description of public cloud providers and also frameworks (famous) which allow building FaaS.

Some examples of Managed Public Cloud FaaS include:
- [AWS Lambda](https://aws.amazon.com/lambda/)
- [Microsoft Azure Functions](https://azure.microsoft.com/en-us/services/functions/).
- [Google Cloud Functions](https://cloud.google.com/functions/)
- [Oracle Cloud Infrastructure Functions](https://www.oracle.com/cloud/cloud-native/functions/)

Some examples of Platforms for executing FaaS in Public and Private Cloud:
- [OpenFaaS](https://www.openfaas.com)
- [Apache OpenWhisk](https://openwhisk.apache.org)
- [Knative](https://www.openfaas.com)

**Comment by edsoncelio** [comment]
> The translation is done but to be more instructive for the reader I add a description of public cloud providers and also frameworks (famous) which allow building FaaS.
> 
> Some examples of Managed Public Cloud FaaS include:
> 
> * [AWS Lambda](https://aws.amazon.com/lambda/)
> * [Microsoft Azure Functions](https://azure.microsoft.com/en-us/services/functions/).
> * [Google Cloud Functions](https://cloud.google.com/functions/)
> * [Oracle Cloud Infrastructure Functions](https://www.oracle.com/cloud/cloud-native/functions/)
> 
> Some examples of Platforms for executing FaaS in Public and Private Cloud:
> 
> * [OpenFaaS](https://www.openfaas.com)
> * [Apache OpenWhisk](https://openwhisk.apache.org)
> * [Knative](https://www.openfaas.com)

Great suggestion! Could you send it on the main slack channel for the project? It can be a good nice to have

**Comment by MrErlison** [comment]
> > The translation is done but to be more instructive for the reader I add a description of public cloud providers and also frameworks (famous) which allow building FaaS.
> > Some examples of Managed Public Cloud FaaS include:
> > 
> > * [AWS Lambda](https://aws.amazon.com/lambda/)
> > * [Microsoft Azure Functions](https://azure.microsoft.com/en-us/services/functions/).
> > * [Google Cloud Functions](https://cloud.google.com/functions/)
> > * [Oracle Cloud Infrastructure Functions](https://www.oracle.com/cloud/cloud-native/functions/)
> > 
> > Some examples of Platforms for executing FaaS in Public and Private Cloud:
> > 
> > * [OpenFaaS](https://www.openfaas.com)
> > * [Apache OpenWhisk](https://openwhisk.apache.org)
> > * [Knative](https://www.openfaas.com)
> 
> Great suggestion! Could you send it on the main slack channel for the project? It can be a good nice to have

Hi @pasimoes
I like it. But in this case, I find it interesting to suggest these additions to the original term in order to maintain similarity.

**Comment by pasimoes** [comment]
thanks.  I will suggest.  if you want to keep it on hold until we see if they approve and then we synchronize.

**Comment by pasimoes** [comment]
I submitted the issue. let's wait for approval to add this suggestion.
https://github.com/cncf/glossary/issues/1627

**Comment by pasimoes** [comment]
> I submitted PR #1627. let's wait for approval to add this suggestion.

I closed this PR because of technical problems with the build and CA validation.

**Comment by pasimoes** [comment]
I closed the PR #1580 because of technical problems with the build and CA validation.
