### ISSUE TITLE
[Portuguese] Localize 'Managed services'

### ISSUE THREAD

**Issue by MrErlison** [cncf/glossary#1210]
Localize [https://glossary.cncf.io/managed-services/](https://glossary.cncf.io/managed-services/)

**Comment by rafaelmnatali** [comment]
Hi @MrErlison, it seems this term was removed from the glossary. At least, not only the page is returning `404` but also not finding anything in the list that resembles `managed services`.

**Comment by MrErlison** [comment]
Sorry for the inconvenience. Deprecated.
