### ISSUE TITLE
Update terms for V2 to new format

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#122]
So far only 25 terms are included in V1 of the glossary. We'd love help updating the remaining terms. [Here is a list of all term](https://docs.google.com/spreadsheets/d/1QvGbINXH60kOibr-Yf5IKHGf2aX2a7cTzQQu_aqJz58/edit#gid=0&fvid=1364988504). On top are those that are included in the pdf and below those that likely need some work. 

For the format, please refer to the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md)

**Comment by ShivamTyagi12345** [comment]
i would like to work on this issue

**Comment by CathPag** [comment]
Thanks for wanting to help, @ShivamTyagi12345! Can you pick a specific term? Sorry, there shouldn't be a good first issue/help wanted tag, so I just removed them.

**Comment by ShivamTyagi12345** [comment]
hey @CathPag  .Can you please suggest a beginner friendly issue to get started with the contributions.

**Comment by CathPag** [comment]
Check out the terms in the "for next release" column in the [project board](https://github.com/cncf/glossary/projects/1). To update the definition, you'll need to have a good understanding of what it means. Anything you feel comfortable explaining to others? That's basically what the glossary is. Explaining terms to other people who are not familiar with it, so it's more about what you know. Does that make sense?

**Comment by ShivamTyagi12345** [comment]
Yes @CathPag  ,makes sense. Just to get myself started , I spotted and fixed a basic typo.
Being a beginner ,How can I explore more of such technical- terms(eg. Node, Stateless Apps ,Loosely controlled architecture etc.) to add to this glossary ?

**Comment by CathPag** [comment]
I'm assuming you're a student since you reached out right after the .edYou program, are you?

See this as a university assignment :) Do some research, ask other (more experienced) students, maybe even a professor (would be really cool if a professor would support this effort!) The difference between an academic assignment and this is that we'd ask you to confirm the definition is correct before submitting, though. Otherwise, it will be more, not less work for the maintainers. Hope this helps.
