### ISSUE TITLE
[Portuguese] Localize 'Shift Left'

### ISSUE THREAD

**Issue by MrErlison** [cncf/glossary#1225]
Localize [https://glossary.cncf.io/shift-left/](https://glossary.cncf.io/shift-left/)

**Comment by matheuspaes** [comment]
Hello, @MrErlison I would like to localize this term, could you assignee for me?

**Comment by MrErlison** [comment]
> Hello, @MrErlison I would like to localize this term, could you assignee for me?

Hi @matheuspaes if you need help, please don't hesitate to ask us in  [Portuguese slack](https://cloud-native.slack.com/archives/C02MWQTJUPL) channel #glossary-localization-portuguese
