### ISSUE TITLE
Cloud Native Operations

### ISSUE THREAD

**Issue by denniskaran** [cncf/glossary#1240]
#### What this term is about? (briefly)
If you are an IT Operations org and you want to modernize your current operations to be cloud-native what does that entail? 
I feel that Cloud Native Operations should encompass several disciplines beyond SRE that orgs need to adopt to modernize their current operations to be cloud-native. i.e. GitOps, DevSecOps, Observability, Chaos Engineering, etc.

#### Why this term needs to be added?
There are many definitions and variations of the term Cloud Native Operations and we need the CNCF to come up with a standard definition so that the name isn't convoluted in the industry as Cloud Native becomes more and more prevalent.

- Many orgs managing a Kubernetes cluster would claim they have a ["Cloud Native Operations"](https://www.globalknowledge.com/us-en/course/185594/cloud-native-operations-bootcamp-cn251/#:~:text=CN251%20is%20an%20intensive%20cloud,administering%20containerized%20applications%20in%20Kubernetes.) team.
- Some Professional Services organizations provide ["Cloud Native Operations"](https://info.container-solutions.com/hubfs/CNO-brochure.pdf?hsLang=en) services to help mature their Cloud Native adoption and providing SRE services.
 - Research organizations are starting to talk about ["Cloud Native Operations"](https://www.hfsresearch.com/research/the-seven-pillars-of-cloud-native-operations/) and adding Observability as another discipline. 
 -Cloud Native is all-encompassing in the "[Kubernetes and Cloud Native Operations Report 2022]( https://juju.is/cloud-native-kubernetes-usage-report-2022)"
 - There are several talks on Cloud Native Operations and they are all unique.
 - [Google Container Engine and the path to cloud-native operations (Google Cloud Next '17)](https://www.youtube.com/watch?v=7d7GxhCw2B0)
 - [Driving Cloud Native Operations with HashiCorp ](https://www.youtube.com/watch?v=vKjWVP8GyZQ)
 - [AWS re:Invent 2021 - Cloud-native operations: Agility and speed through distributed ownership](https://www.youtube.com/watch?v=YxX1mOE5B5Y)

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [x] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by CathPag** [comment]
Thanks for your suggestion, @denniskaran.  The maintainers agreed that this is not (yet?) an established term and should thus not be part of the Glossary.
