### ISSUE TITLE
Localise 'Cloud Computing' to Hi

### ISSUE THREAD

**Issue by NitishKumar06** [cncf/glossary#1242]
### 1. Please describe why this term needs to be updated

The following page (https://glossary.cncf.io/cloud-computing/) needs a translation into the Hindi language so that the readers who prefer learning and understanding more in the Hindi language can understand better.

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [X] I want to work on this suggestion. (If not checked, maintainers will assign another volunteer)

### (Note)

I'd love to work on this issue.

**Comment by shivam-sharma7** [comment]
can i work on this issues?

**Comment by NitishKumar06** [comment]
I've already requested to work on this issue
