### ISSUE TITLE
[hi] Localize term 'Version Control' into Hindi

### ISSUE THREAD

**Issue by shivam-sharma7** [cncf/glossary#1259]
#### Why this term needs to be updated? (briefly)
- Localize term 'Version Control' into Hindi for people who want translate this term in Hindi
-  https://glossary.cncf.io/version-control/

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [X] I want to work on this suggestion. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by shivam-sharma7** [comment]
@anubha-v-ardhan I would like to work on this. Please assign me.
Thank-you:)

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 Version-control has been already merged into dev/hi branch #1049

@bishal7679 Thanks for sharing

**Comment by sayantani11** [comment]
Since this is done, i am closing the issue.
