### ISSUE TITLE
[hi] `api-gateway` for `Hindi`

### ISSUE THREAD

**Issue by amolmote** [cncf/glossary#1269]
Localize api-gateway For Hindi
[api-gateway.md](https://github.com/cncf/glossary/blob/dev-hi/content/en/api-gateway.md)

**Comment by amolmote** [comment]
thank u @bishal7679 for suggestion.

**Comment by anubha-v-ardhan** [comment]
The issue template used is to intitate a new localization team. I'd request you to remove irrelavant text from the issue description.

**Comment by amolmote** [comment]
done @anubha-v-ardhan please accept triage if this issue is valid

**Comment by amolmote** [comment]
@jihoon-seo  I want to work on it so please raise the triage and assign it to me

**Comment by jihoon-seo** [comment]
Approvers of Hindi team (@Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava), PTAL!

**Comment by NitishKumar06** [comment]
Since this issue has been raised for a long time, and no updates have been there - I'd be raising a PR for this.

**Comment by Garima-Negi** [comment]
closing this as a new issue for api-gateway is now created and is getting actively worked on : https://github.com/cncf/glossary/issues/1540
