### ISSUE TITLE
 Localise 'Cloud Computing' to Hi

### ISSUE THREAD

**Issue by shivam-sharma7** [cncf/glossary#1271]
#### Why this term needs to be updated? (briefly)
- The following page (https://glossary.cncf.io/cloud-computing/) needs a translation into the Hindi language so that the readers who prefer learning and understanding more in the Hindi language can understand better.

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [X] I want to work on this suggestion. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by jihoon-seo** [comment]
This issue is a duplicate of #1005.
