### ISSUE TITLE
Static site generator for glossary

### ISSUE THREAD

**Issue by epogrebnyak** [cncf/glossary#128]
Thanks for putting up a glossary! I wondered if the team had a plan to publish the glossary as a web site? You have the source files in markdown, have you considered using a static site generator like mkdocs or Hugo and publish on Github pages? This can be a good view of or the files.

**Comment by CathPag** [comment]
Hi @epogrebnyak, apologies for the late reply. Yes, that's the plan for V2 which should go live for KubeCon NA 2021.
