### ISSUE TITLE
[hi] Localize `Distributed System` in Hindi

### ISSUE THREAD

**Issue by Shivansh-yadav13** [cncf/glossary#1300]
- https://glossary.cncf.io/distributed-systems/

**Comment by abhay-raj19** [comment]
Hey @NitishKumar06 as said by you that the issue is prior existing for localisation of `Distributed system` in Hindi , and I want to work on this issue pls assign me.

**Comment by abhay-raj19** [comment]
I will work fast and will raise a PR in next 2-3 working days after assigned date.
Pls @NitishKumar06 @sayantani11 assign me for the next best results.

**Comment by NitishKumar06** [comment]
> Hey @NitishKumar06 as said by you that the issue is prior existing for localisation of `Distributed system` in Hindi , and I want to work on this issue pls assign me.

https://github.com/cncf/glossary/pull/1347

**Comment by Aryan-Singla** [comment]
@aj11anuj can you please check is this issue is open or not . If open please assign to me

**Comment by kumarankit999** [comment]
Hey @nitishfy will you work on this Issue Further and then do it or If you don't want to work on this, I can assign this to someone

**Comment by nitishfy** [comment]
HI @kumarankit999 , right now, I don't have the bandwidth to work on this issue. If someone else would like to take this issue, please go ahead :)

**Comment by Aryan-Singla** [comment]
Can I do work on this

**Comment by kumarankit999** [comment]
Thanks @nitishfy for helping Us.
