### ISSUE TITLE
[hi] Localize `service.md` for `Hindi`

### ISSUE THREAD

**Issue by amolmote** [cncf/glossary#1304]
[hi] Localize  [service.md](https://github.com/cncf/glossary/blob/dev-hi/content/en/service.md ) for Hindi

**Comment by amolmote** [comment]
@jihoon-seo  I want to work on it so please raise the triage and assign it to me

**Comment by jihoon-seo** [comment]
Approvers of Hindi team (@Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava), PTAL!

**Comment by shivam-sharma7** [comment]
@Garima-Negi @anubha-v-ardhan can you assign me this?

**Comment by SaarthakMaini** [comment]
I think this issue can be closed as completed
