### ISSUE TITLE
[New term] `Hypervisor`

### ISSUE THREAD

**Issue by KiranSatyaRaj** [cncf/glossary#1306]
#### What this term is about? (briefly)
- A hypervisor makes virtualization feasible, it is the software that sits on top of the compute host and virtualizes its functionalities into subparts, distributes them to multiple users, and workloads, and enables us to take advantage of the compute host.
#### Why this term needs to be added? (briefly) 
- It is virtualization that has brought the cost of computing down and brought us a step closer to efficient usage of the physical machines, the underlying piece of software that makes it possible and manages the virtual servers is a hypervisor, having a high-level view of the hypervisor would provide more clarity about how this led to the development of cloud-native applications.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by CathPag** [comment]
Thanks for your suggestion, @KiranSatyaRaj. We've accepted the term and assigned the issue to you.

**Comment by KiranSatyaRaj** [comment]
Thank you so much @CathPag, I'm on it.

**Comment by NitishKumar06** [comment]
@KiranSatyaRaj Do you need any help from my side? Please let me know anytime.

**Comment by KiranSatyaRaj** [comment]
> @KiranSatyaRaj Do you need any help from my side? Please let me know anytime.

Thanks @NitishKumar06 for offering the help, I'm making progress and will make pull request soon regarding this issue, I will definitely reach out to you if there's anything I'm stuck with.

**Comment by KiranSatyaRaj** [comment]
#1385 
Here's the pull request I made referencing this issue, please review it.

**Comment by KiranSatyaRaj** [comment]
#1385

**Comment by NitishKumar06** [comment]
Thanks @KiranSatyaRaj! I'll go through it shortly!
