### ISSUE TITLE
[New term] `Environment`

### ISSUE THREAD

**Issue by lukepatrick** [cncf/glossary#1309]
#### What this term is about? (briefly)
- "Environment" is a word that is thrown around a lot in cloud native and software development lifecycle contexts, but usually lacks a concrete definition. 
#### Why this term needs to be added? (briefly) 
- "Environment" can be an overloaded term, an under used term, or arbitrarily mixed with "infrastructure" 
- "Environment" can be both underutilized - run the code anywhere, or an incredibly important distinction - "don't deploy to 'production' until all the -ilities are met" 

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by CathPag** [comment]
Thanks for your suggestion, @lukepatrick, but the maintainers believe that this term is too basic for this Glossary.
