### ISSUE TITLE
Issues on labeler workflow

### ISSUE THREAD

**Issue by yunkon-kim** [cncf/glossary#1322]
Hi, I would like to share my observation on the labeler workflow issues. (PTAL @seokho-son)

#### 1. Failing on labeling
Several days ago, the labeler workflow was updated and re-enabled on the upstream. But, the workflow (i.e.,.github/workflows/labeler.yml) hasn't been applied yet on every `dev-**` branch. Thus, I expected this issue would be resolved naturally. Until then, please ignore the error.

#### 2. Awaiting approval from a maintainer
I should have expected such an inconvenient operation... When the first-time contributors create a PR, the labeler workflow will ask the approval from a maintainer. An alternative to this is to run the workflow as a cron job. In this case, I'm concerned about the request limit on GitHub Actions.

Comments, advice, concerns, and contributions are always welcome =)

**Comment by seokho-son** [comment]
To prevent unnecessary issues regarding the workflow, I disabled it manually.
Thank you @yunkon-kim :)

**Comment by yunkon-kim** [comment]
@seokho-son I got it 👍 

Is it possible to replace `dev-**` (i.e., wildcard) with `dev-ko` to test this workflow? 
Only PRs targeting the dev-ko branch will trigger this workflow. When another team needs this workflow, we can explicitly add their target branch.

Suggestion:
```diff
name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened]
    paths:
      - 'content/**.md'
    branches:
-      - 'dev-**'
-      - 'main'
+      - 'dev-ko'
```

Ref: [labler.yml](https://github.com/cncf/glossary/blob/main/.github/workflows/labeler.yml)

**Comment by seokho-son** [comment]
@yunkon-kim 
Thanks! I think so.
Could you open a PR for that ?

**Comment by yunkon-kim** [comment]
@seokho-son Thank you !

I will open the PR.
