### ISSUE TITLE
[hi] Localize  `Zero Trust Architecture` into Hindi 

### ISSUE THREAD

**Issue by shivam-sharma7** [cncf/glossary#1354]
# This issue is to initiate a new l10n Team

page-https://glossary.cncf.io/zero-trust-architecture/

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

For example, the two-letter code for Korean is `ko`.

 - Language name (ex: `Korean`): 
 - Language two-letter code (ex: `ko`): 

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

Ex: `- [A] Seokho Son (@seokho-son)`

- 
- 
- 

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-ko`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by shivam-sharma7** [comment]
can you assign me?

**Comment by Garima-Negi** [comment]
reassigning to Amol Mote snce he already has a PR ready.

**Comment by sayantani11** [comment]
Done! #1249
