### ISSUE TITLE
Rename `content/bn/auto_scaling.md` to `content/bn/auto-scaling.md`

### ISSUE THREAD

**Issue by PratikDey** [cncf/glossary#1364]
Currently the auto scaling in content/bn/ folder markdown file has an '_' as a separator. Request to add a '-' as a separator
![Screenshot from 2022-10-11 23-38-55](https://user-images.githubusercontent.com/56970651/195167660-9153845d-439c-45c0-9767-05bab216b6cc.png)

**Comment by NitishKumar06** [comment]
I could not see the file auto_scaling in bn folder

**Comment by PratikDey** [comment]
Check again please

**Comment by NitishKumar06** [comment]
@PratikDey 
![folder](https://user-images.githubusercontent.com/86051118/195889494-56d56157-7881-48b4-8ae1-ee5f7048e20d.png)

**Comment by PratikDey** [comment]
What branch are you checking this on?

**Comment by NitishKumar06** [comment]
@PratikDey master

**Comment by Imtiaz1234** [comment]
@PratikDey  yes, I have seen that. You can work on this.
