### ISSUE TITLE
Cloud native technologies >> update to new format 

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#138]
https://github.com/cncf/glossary/blob/main/definitions/cloud_native_tech.md

Please convert entry to the property format. View the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

**Comment by kumardeni** [comment]
@JasonMorgan @CathPag - i can take up if available..

**Comment by CathPag** [comment]
Same here, @kumardeni. Please finish the other term first — thanks!
