### ISSUE TITLE
 [Spanish] localize 'Microservices'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1394]
Localize the `content/en/microservices.md` document to Spanish

**Comment by mdf-ido** [comment]
I'd love to help with this term / Me gustaría ayudar con este termino

**Comment by electrocucaracha** [comment]
@mdf-ido Planeas trabajar en este issue? Puedo reasignarlo a alguien mas?

**Comment by mdf-ido** [comment]
Si, lo puedo hacer esta semana pero si otra persona puede hacerlo antes entonces si! 👯
