### ISSUE TITLE
 [Spanish] localize 'Monolithic Apps'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1395]
Localize the `content/en/monolithic-apps.md` document to Spanish

**Comment by tinniaru3005** [comment]
Hey @electrocucaracha, can you please assign me this issue?

**Comment by electrocucaracha** [comment]
@tinniaru3005 did you still working on this? Can I reassign this one?

**Comment by tinniaru3005** [comment]
No I am not. Sorry for the delay.

**Comment by mdf-ido** [comment]
I can take this one
