### ISSUE TITLE
 [Spanish] localize 'Multitenancy'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1396]
Localize the `content/en/multitenancy.md` document to Spanish

**Comment by tinniaru3005** [comment]
Hey @electrocucaracha, Can you please assign me this issue?

**Comment by tinniaru3005** [comment]
> @tinniaru3005 did you still working on this? Can I reassign this one?

No I don't. I got busy with my preparations for my Masters entrance exam and completely for got about the issues. So sorry for the delay.

**Comment by mdf-ido** [comment]
I can help here
