### ISSUE TITLE
[Spanish] localize 'mTLS (Mutual Transport Layer Security)'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1397]
Localize the `content/en/mutual-transport-layer-security.md` document to Spanish

**Comment by vasucp1207** [comment]
@electrocucaracha, can I work on this?

**Comment by electrocucaracha** [comment]
> @electrocucaracha, can I work on this?

It seems like @tinniaru3005 requested this before, but I didn't perform the change.

**Comment by electrocucaracha** [comment]
@tinniaru3005 did you still working on this? Can I reassign this to @vasucp1207?

**Comment by tinniaru3005** [comment]
> @tinniaru3005 did you still working on this? Can I reassign this to @vasucp1207?

Ya sure. I got busy with my preparations for my Masters entrance exam and completely for got about it. So sorry for the delay.

**Comment by mdf-ido** [comment]
Let me know if you need help here as well

**Comment by electrocucaracha** [comment]
@mdf-ido  I'll move this to the backlog, let me know in case that you have some progress.

**Comment by marianogg9** [comment]
@electrocucaracha estoy libre para trabajar en este issue. Gracias!

**Comment by ramrodo** [comment]
closed by https://github.com/cncf/glossary/pull/2072
