### ISSUE TITLE
 [Spanish] localize 'Reliability' 

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1399]
Localize the `content/en/reliability.md` document to Spanish

**Comment by anairinac** [comment]
Hi team, can I take this one?

**Comment by anairinac** [comment]
Hi, the PR I submitted is ready for review. Let me know if I need to update the wording :)

Should I post the PR in one of the Slack channels since this is my first contrib to the glossary? PR says it needs a maintainer to approve, as well as the reviewers.

**Comment by electrocucaracha** [comment]
Really? I need to take time to double-check duplicates. If you can help me on detect those duplicates issues should be great or I can assign you other issue

**Comment by electrocucaracha** [comment]
> Hi, the PR I submitted is ready for review. Let me know if I need to update the wording :)
> 
> Should I post the PR in one of the Slack channels since this is my first contrib to the glossary? PR says it needs a maintainer to approve, as well as the reviewers.

That's fine, I will take a look later.
