### ISSUE TITLE
Containerization >> update to new format

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#140]
https://github.com/cncf/glossary/blob/main/definitions/containerization.md

Please convert entry to the property format. View the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

**Comment by TakshakRamteke** [comment]
Hello, May I work on this one

**Comment by CathPag** [comment]
@TakshakRamteke, there is a PR for that term already. We currently only have two terms available (please refer to the [project board](https://github.com/cncf/glossary/projects/1)) but you can identify one that is missing or wait for a few weeks. We'll be adding more soon.

**Comment by TakshakRamteke** [comment]
@CathPag Ok
