### ISSUE TITLE
 [Spanish] localize 'Scalability'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1402]
Localize the `content/en/scalability.md` document to Spanish

**Comment by tinniaru3005** [comment]
Hey @electrocucaracha, Can you please assign me this issue?

**Comment by electrocucaracha** [comment]
@tinniaru3005 did you still working on this? Can I reassign this one?

**Comment by tinniaru3005** [comment]
> @tinniaru3005 did you still working on this? Can I reassign this one?

Ya sure. I got busy with my preparations for my Masters entrance exam and completely for got about it. So sorry for the delay.

**Comment by ramrodo** [comment]
@electrocucaracha I would like to start working on this one.
