### ISSUE TITLE
Distributed apps >> update to new format

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#141]
https://github.com/cncf/glossary/blob/main/definitions/distributed_apps.md

Please convert entry to the property format. View the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

**Comment by reddymahendra52** [comment]
Hello,
Can I work on this??
I have gone through the comments of other issues. So I fairly got an idea of what I have to do.

**Comment by CathPag** [comment]
Sounds good, thanks @reddymahendra52!

**Comment by CathPag** [comment]
Actually, this is already done and in review. Please look at the [board](https://github.com/cncf/glossary/projects/1) when picking a term.

**Comment by reddymahendra52** [comment]
Okay Sorry,
I was thinking of working on **Loosely Coupled Architecture** Can you assign me that??
