### ISSUE TITLE
[Portuguese] Localize 'Event Streaming'

### ISSUE THREAD

**Issue by MrErlison** [cncf/glossary#1411]
Localize [https://glossary.cncf.io/event-streaming/](https://glossary.cncf.io/event-streaming/)

**Comment by vasucp1207** [comment]
@MrErlison, I am interested in working on this issue.

**Comment by MrErlison** [comment]
Hi @vasucp1207 if you need help, please don't hesitate to ask us in Portuguese slack channel #glossary-localization-portuguese

Remember, you need open your PR to branch dev-pt. Please, read this [guide](https://gist.github.com/edsoncelio/d7fdec7f24d5aba87e3e517c672e9eb5) for more details.
