### ISSUE TITLE
Initiate Japanese Localization Team

### ISSUE THREAD

**Issue by inductor** [cncf/glossary#1422]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

For example, the two-letter code for Korean is `ko`.

 - Language name (ex: `Korean`): Japanese
 - Language two-letter code (ex: `ko`): ja

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

Ex: `- [A] Seokho Son (@seokho-son)`

- [A] Kohei Ota (@inductor)
- [A] Nao Nishijima(@naonishijima)
- [A] Kaito (@kaitoii11)
- Hitoshi Yabusaki(TBD)
- Ide Takaya(@t-ide)
- Hu SHIZGEN(@shizhenhu)
- Ryotaro Kobayashi(@ryoryotaro)

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-ja`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by naonishijima** [comment]
Added list of volunteers

- [A] Nao Nishijima(@naonishijima)
- Hitoshi Yabusaki(TBD)
- Ide Takaya(@t-ide)
- Hu SHIZGEN(@shizhenhu)

**Comment by seokho-son** [comment]
[A] Kohei Ota (@inductor), [A] Nao Nishijima(@naonishijima), [A] Kaito (@kaitoii11), Hitoshi Yabusaki, Ide Takaya(@t-ide), Hu SHIZGEN(@shizhenhu), Ryotaro Kobayashi(@ryoryotaro) !
Thank you for the initiation of the Japanese Team !

Created Dev branch and label for Japanese! You can use the branch now. 
- Development branch: `dev-ja` (https://github.com/cncf/glossary/tree/dev-ja)
- Issue/PR label: https://github.com/cncf/glossary/labels/lang%2Fja (https://github.com/cncf/glossary/labels) 

You already have the Slack channel: [`#glossary-localization-japanese`](https://cloud-native.slack.com/archives/C057F81GFUG)

- Next step: https://github.com/cncf/glossary/blob/main/LOCALIZATION.md
- Some references (related PRs/Issues): https://github.com/cncf/glossary/projects/2

To Japanese approver candidates [A] Kohei Ota (@inductor), [A] Nao Nishijima(@naonishijima), [A] Kaito (@kaitoii11),
I am going to open a PR to add @inductor@naonishijima @kaitoii11 to Japanese contents approver (owner).
In the meantime, please check the following policy.
[Policies for localization approvers (to be confirmed by candidates) #723](https://github.com/cncf/glossary/discussions/723)

**Comment by seokho-son** [comment]
Hi @cjyabraham :)
Please enable Netlify build preview for the `dev-ja` branch.

**Comment by cjyabraham** [comment]
done

**Comment by naonishijima** [comment]
@seokho-son 
I don't know this is the right place to inquire, but I would like to add Nakamura-san(@yuichi-nakamura) to the approver of Japanese Localization Team. Thanks.

**Comment by naonishijima** [comment]
@jihoon-seo @seokho-son 
I don't know this is the right place to request, I would like to add Nakamura-san(@yuichi-nakamura) to the approver of Japanese Localization Team. Thanks.

**Comment by seokho-son** [comment]
Hi @naonishijima,
Apologies for my delayed response, I've been overwhelmed with notifications recently. ;) Of course, the Japanese Localization Team is more than welcome to suggest a new approver. However, please ensure that the suggested individual is an eligible contributor. It's worth noting that contributors can open/review a PR without necessarily being an approver.

Two quick questions
 - is Nakamura-san(@yuichi-nakamura) nominated by the team?
 - is the candidate appropriate contributor? (already contributing to localization? or known expert for localization or open source management?)

**Comment by naonishijima** [comment]
Hi @seokho-son,

Thank you for response!


> is Nakamura-san(@yuichi-nakamura) nominated by the team?

Yes. I recommend Nakamura-san.

> is the candidate appropriate contributor? (already contributing to localization? or known expert for localization or open source management?)

He have contributes and organizes events in the Japanese security OSS community(SELinux, Keycloak).  Also he start to contribute CNCF this year.

**Comment by naonishijima** [comment]
Hi @seokho-son ,
Is there anything I should do from my side?

**Comment by seokho-son** [comment]
Hi @naonishijima 
Could you help @yuichi-nakamura read #2343 ?

**Comment by naonishijima** [comment]
Hi @seokho-son ,
Thank you for your support.
I will help @yuichi-nakamura -san as soon as possible.
