### ISSUE TITLE
Monolithic application >> update to new format

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#143]
https://github.com/cncf/glossary/blob/main/definitions/monolithic_apps.md

Please convert entry to the property format. View the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

**Comment by aaroosh-07** [comment]
@CathPag can I take up this issue?

**Comment by CathPag** [comment]
@aaroosh-07, we'll need to review your current PR first. That way, you can keep the feedback in mind that's we'll provide. We have a few people on vacation, so thanks for your patience.

**Comment by aaroosh-07** [comment]
okay @CathPag

**Comment by Anubhavjoshi040** [comment]
@CathPag can I work on this issue?

**Comment by CathPag** [comment]
ok, go for it.

**Comment by CathPag** [comment]
@Anubhavjoshi040, just FYI, we have to finalize all 50 terms by KubeCon and would need this definition no later than October 4. If we don't have it by then, we'll have to start working on it as it has to be finalized by Oct 8. Let me know if that works.

**Comment by Anubhavjoshi040** [comment]
@CathPag yeah I'll complete it by tomorrow. Sorry for the delay.
