### ISSUE TITLE
[hi] Localize `Serverless` for `Hindi`

### ISSUE THREAD

**Issue by shivam-sharma7** [cncf/glossary#1435]
### Please describe why this term needs to be updated

- Serverless term available in `English,` `Chinese` and `Portugues` but This term also need to be Localize into `Hindi` for the people who want to read this term in Hindi.
- visit on page-https://glossary.cncf.io/serverless/

https://github.com/cncf/glossary/issues/1435#tasklist-block-950c877d-a325-49f9-b666-75a5ebe28db9

**Comment by shivam-sharma7** [comment]
can you assign me ? / @Garima-Negi

**Comment by NitishKumar06** [comment]
@shivam-sharma7 You can start working on it. I'm assuming @Garima-Negi / @anubha-v-ardhan might be busy. Raise a PR for this issue and we'd review it.
