### ISSUE TITLE
Node >> update to new format

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#144]
https://github.com/cncf/glossary/blob/main/definitions/nodes.md

Please convert entry to the property format. View the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

**Comment by Utkarshn10** [comment]
Hi, I would like to work on this issue. Since this is the first time I am contributing to this repo I have a small doubt/clarification. The Issue is to convert the category to Property in place of Concept, right?

**Comment by CathPag** [comment]
Thanks for wanting to help out @Utkarshn10! Updating is only one part. None of these terms have been vetted yet, so we need to ensure definitions are correct and complete. If you're not 100% sure, maybe someone more experienced can help you with the definition. Once you are confident the definition is correct and in the right format (please refer to the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md)), you can submit a PR. Does that make sense?

**Comment by Utkarshn10** [comment]
Yeah that makes sense. So I will do research regarding the topic and then submit a PR. 
Doubt: Is there any mail/slack channel where I can post my doubts or get information whether the info I am writing in the PR is correct or not.

**Comment by CathPag** [comment]
Yes, you find the marketing-business-value channel on the CNCF Slack. Here's something I just said to another person which could help:

> See this as a university assignment :) Do some research, ask other (more experienced) students, maybe even a professor (would be really cool if a professor would support this effort!) The difference between an academic assignment and this is that we'd ask you to confirm the definition is correct before submitting, though. Otherwise, it will be more, not less work for the maintainers. Hope this helps.

**Comment by Utkarshn10** [comment]
@CathPag Thanks! I will make sure that the definitions are correct.

**Comment by ashish-patwal** [comment]
Hey @CathPag , it's been 3 weeks . If this issue is still open , i can work on this .

**Comment by CathPag** [comment]
Sure! Just assigned to you @ashish-patwal

**Comment by ashish-patwal** [comment]
Thanks , I will try to get it done ASAP !

**Comment by CathPag** [comment]
Don't rush it too much. A good definition takes its time :)

**Comment by ashish-patwal** [comment]
I will certainly follow your advice
