### ISSUE TITLE
Portability >> update to new format

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#145]
https://github.com/cncf/glossary/blob/main/definitions/portability.md

Please convert entry to the property format. View the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

**Comment by Anubhavjoshi040** [comment]
Hey @CathPag I would love to work on this issue to make my first contribution to open source.

**Comment by Anubhavjoshi040** [comment]
Hey, I have my PR almost ready for this issue but is it necessary to get assigned first?

**Comment by CathPag** [comment]
Hi @Anubhavjoshi040, looks like I completely missed your first message — sorry about that. Please look at the [project board](https://github.com/cncf/glossary/projects/1) to pick terms, portability was already in progress. Since I was working on it, I didn't assign it to me specifically. I just submitted the PR, feel free to review and suggest changes
