### ISSUE TITLE
[New term] `Role-based access control (RBAC)`

### ISSUE THREAD

**Issue by juliafmorgado** [cncf/glossary#1465]
#### What this term is about? (briefly)

Role-based access control (RBAC) is a security approach that authorizes and restricts system access to users based on their role(s) within an organization.

#### Why this term needs to be added? (briefly) 

Enterprise environments often involve multiple teams working on cloud native projects and applications on the same cloud infrastructure. When it comes to managing security for such environments, this complex weave of permissions and roles can get ugly quickly as more teams and stakeholders get involved. RBCA ensures least privilege access is maintained without making its management unwieldy.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by seokho-son** [comment]
Hi @juliafmorgado 
Thank you for the suggestion. Maintainers agree with your suggestion ! :)

Please try to explain RBAC easily so that non-technical folks can understand it easily.

Please check following resources before you start. :)
- [Style Guide](https://glossary.cncf.io/style-guide/)
- [How To Contribute](https://glossary.cncf.io/contribute/)

(CC @iamNoah1 @CathPag @jihoon-seo @JasonMorgan )

**Comment by juliafmorgado** [comment]
Sounds good!

**Comment by juliafmorgado** [comment]
Related PR: https://github.com/cncf/glossary/pull/1503
