### ISSUE TITLE
Stateful application >> update to new format

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#147]
https://github.com/cncf/glossary/blob/main/definitions/stateful_apps.md

Please convert entry to the property format. View the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

**Comment by sudhxnva** [comment]
Hi! I'd like to take a dig at this issue. Seems fairly straightforward and I have gone through the style guide.

**Comment by CathPag** [comment]
Great! Thanks for your help @sudhxnva!

We are looking for two things:

1. Update the format according to the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md).
2. Make sure the definitions are correct and complete.

If you're not 100% sure about the definition, consider asking someone else (a more experienced colleague/classmate/professor). You can also submit an incomplete definition but please say so when submitting the PR (e.g. I know virtual machines address X and Y but not too sure about Z). We can then fill the gaps. But please _do_ verify that what you submit is technically accurate.

I hope this helps.

**Comment by kumar-deni** [comment]
@CathPag @JasonMorgan - i can take this up..

**Comment by CathPag** [comment]
You got it :)
