### ISSUE TITLE
Tightly coupled architectures >> update to new format 

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#148]
https://github.com/cncf/glossary/blob/main/definitions/tightly_coupled_architectures.md

Please convert entry to the property format. View the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

**Comment by TakshakRamteke** [comment]
Hello @CathPag @JasonMorgan , I would like to work on this one please

**Comment by JasonMorgan** [comment]
@TakshakRamteke it's now in the new format but if you'd still like to work it it needs to be improved before we can mark it as completed. Let me know and I'm happy to assign it.

**Comment by TakshakRamteke** [comment]
@JasonMorgan Yeah sure why not I'll be more than happy to work on this one, but could you please tell me what do we need to improve in this one ?

**Comment by CathPag** [comment]
Term has been assigned
