### ISSUE TITLE
Virtual machine >> update to new format 

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#149]
https://github.com/cncf/glossary/blob/main/definitions/virtual_machine.md

Please convert entry to the property format. View the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

**Comment by TakshakRamteke** [comment]
Hello, I would like to work on this one but just to be sure Virtual machine is a Concept rather than Software so if that is the case I'd love to help.

**Comment by CathPag** [comment]
Thanks for your help @TakshakRamteke! 

We are looking for two things:

1. Update the format according to the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md). 
2. Make sure the definitions are correct and complete.

If you're not 100% sure about the definition, consider asking someone else (a more experienced colleague/classmate/professor). You can also submit an incomplete definition but please say so when submitting the PR (e.g. I know virtual machines address X and Y but not too sure about Z). We can then fill the gaps. But please _do_ verify that what you submit is technically accurate.

I hope this helps.
