### ISSUE TITLE
Stateless Apps >> update to new format

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#150]
https://github.com/cncf/glossary/blob/main/definitions/stateless_apps.md

Please convert entry to the property format. View the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

**Comment by Arvind644** [comment]
@CathPag I want to ask that can we change #What it is , # Problem it Addresses , # How it Helps to ###What it is ,  ### Problem it Addresses , ### Problem it Addresses, because it becomes bigger heading coming after definition, which becomes odd in styling

**Comment by CathPag** [comment]
@Arvind644, here's an [example of a term that's ready](https://github.com/cncf/glossary/blob/main/definitions/api_gateway.md)

**Comment by Arvind644** [comment]
Thank you

**Comment by Anubhavjoshi040** [comment]
Hey, I would love to update this definition to new format.

**Comment by CathPag** [comment]
Sure! Here you go, @Anubhavjoshi040

**Comment by JasonMorgan** [comment]
Depends on this PR: https://github.com/cncf/glossary/pull/189
