### ISSUE TITLE
[hi] Localize `Event Streaming` for `Hindi`

### ISSUE THREAD

**Issue by yashpimple** [cncf/glossary#1511]
#### Why this term needs to be updated? (briefly) 
- Event Streaming term available in English only but This term also needs to be Localized into Hindi for the people who want to read this term in Hindi.
- visit on page-https://glossary.cncf.io/event-streaming/

**Comment by YashPimple** [comment]
Would like to work on this issue can you assign it to me @Garima-Negi

**Comment by himanshu1221** [comment]
Can You assign this to me i wana work on this issue @YashPimple

**Comment by akshat5302** [comment]
I would like to work on this issue @YashPimple If you need a partner I am up for it

**Comment by AniketNS** [comment]
Hi @jihoon-seo please assign this task to me.

**Comment by YashPimple** [comment]
@AniketNS I have made the PR as instructed and would like you to have a look at another issue.
