### ISSUE TITLE
[New term] `cloud native apps` for `Hindi`

### ISSUE THREAD

**Issue by Martande8055** [cncf/glossary#1536]
### Please describe why this term needs to be updated

What is this term about? (briefly)

- Cloud native applications are specifically designed to take advantage of innovations in cloud computing.

Why does this term need to be added? (briefly)

- Localizing this term in Hindi will help Hindi folks learn about this term in their native language.

Link here: 

- https://glossary.cncf.io/cloud-native-apps/

**Comment by Martande8055** [comment]
I would like to work on this term. Anyone can review it and can assign it to me? :)
@Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava

**Comment by Martande8055** [comment]
Please can any one assign it to me 
@Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava

**Comment by anubha-v-ardhan** [comment]
Thank you @Martande8055 :)
