### ISSUE TITLE
[hi] Localize ```API Gateway``` for ```Hindi```

### ISSUE THREAD

**Issue by akshat5302** [cncf/glossary#1540]
**Please describe why this term needs to be updated**

**Why does this term need to be updated? (briefly)**

> - API Gateway is a tool that aggregates all unique APIs, making them all available in one place 
> - The API Gateway term is available in English only but This term also needs to be Localized into Hindi for people who want to read this term in Hindi.

visit the page-https://glossary.cncf.io/api-gateway/

**Comment by akshat5302** [comment]
I would like to work on this issue please assign it to me :) 
@anubha-v-ardhan @sayantani11 @Garima-Negi @bishal7679 @verma-kunal

**Comment by Anuragwagh** [comment]
I speak Hindi on a daily basis and have been proficient in writing in Hindi since elementary school, so assign me this problem and I will solve it; I will localise the API Gateway in Hindi in a very understandable manner, so anyone interested in reading in Hindi will easily understand it.

**Comment by akshat5302** [comment]
Hey @Anuragwagh I already started working on this issue you can choose any other 😅😊

**Comment by AniketNS** [comment]
Hey @akshat5302 i would like to work on this issue. Please assign it to me.

**Comment by AniketNS** [comment]
Hi @Garima-Negi mam, Akshat is busy with his exams. He asked me to do this task. Can u please assign this task to me?

**Comment by akshat5302** [comment]
Yes, @Garima-Negi I might take some time to complete it. It will be great if @AniketNS could do it.

**Comment by AniketNS** [comment]
Hello @Garima-Negi, I've completed the task. Please review it and tell me if there is any modification needed.

**Comment by AniketNS** [comment]
Why this issue is still open?
