### ISSUE TITLE
[New term] localise topics into Hindi

### ISSUE THREAD

**Issue by Anuragwagh** [cncf/glossary#1542]
**Why this term needs to be added?**

As far as I can tell, some pages have been translated into localised Hindi; however, not all pages have been translated, so if someone wants to read it in Hindi, he or she will only get some of the topics, which will disappoint him or her and make it difficult to understand other topics. So translating other topics into localised Hindi is also necessary to understand other topics.

**Comment by Anuragwagh** [comment]
I speak Hindi on a daily basis and have been proficient in writing in Hindi since elementary school, so assign me this problem and I will solve it; I will localise the API Gateway in Hindi in a very understandable manner, so anyone interested in reading in Hindi will easily understand it. 

1) I will convert it into an easily understandable phrase:
2) I will use simple, understandable words, so anyone who is not proficient in Hindi can understand the sentences.

I will localise all the topics that have not been localised in Hindi; these topics are listed below.

Kubernetes : https://glossary.cncf.io/kubernetes/
Loosely Coupled Architecture : https://glossary.cncf.io/loosely-coupled-architecture/
Microservices : https://glossary.cncf.io/microservices/
Monolithic Apps : https://glossary.cncf.io/monolithic-apps/
Mutual Transport Layer Security (mTLS) : https://glossary.cncf.io/mutual-transport-layer-security/
Observability : https://glossary.cncf.io/observability/
Portability : https://glossary.cncf.io/portability/
Reliability : https://glossary.cncf.io/reliability/
Scalability : https://glossary.cncf.io/scalability/
Security Chaos Engineering : https://glossary.cncf.io/security-chaos-engineering/
Serverless : https://glossary.cncf.io/serverless/
Service : https://glossary.cncf.io/service/
Service Discovery : https://glossary.cncf.io/service-discovery/
Service Mesh : https://glossary.cncf.io/service-mesh/
Service Proxy : https://glossary.cncf.io/service-proxy/
Site Reliability Engineering :https://glossary.cncf.io/site-reliability-engineering/
Tightly Coupled Architectures:https://glossary.cncf.io/tightly-coupled-architectures/
Transport Layer Security : https://glossary.cncf.io/transport-layer-security/
Vertical Scaling : https://glossary.cncf.io/vertical-scaling/
Virtual Machine : https://glossary.cncf.io/virtual-machine/
Virtualization : https://glossary.cncf.io/virtualization/
Zero Trust Architecture : https://glossary.cncf.io/zero-trust-architecture/

Assign it to me.

**Comment by AniketNS** [comment]
I'd also do this in a better manner. I'll write these documents in Hindi as well as in a very easy way to understand. Please assign this task to me.

**Comment by Anuragwagh** [comment]
> I'd also do this in a better manner. I'll write these documents in Hindi as well as in a very easy way to understand. Please assign this task to me.

Hey, @AniketNS, I am working on it.

**Comment by akshat5302** [comment]
Hey @AniketNS in CNCF Glossary (https://glossary.cncf.io/) many topics still need a translation you can work on that by opening up an issue regarding the same topic 
For now, you can work on mine #1540 if you want to cause I postponed working on it due to exams

**Comment by Garima-Negi** [comment]
Many of the terms mentioned above have already been localised in dev-hi branch. We will soon be merging it into dev so that the terms become live on the website.

For the rest, we follow the procedure of one issue per term/content followed by PR for the same. 
Hence closing this issue, please go through existing issues marked with label lang/hi
