### ISSUE TITLE
Vertical scaling definition 

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#157]
Please follow format defined in[ style guide](https://github.com/cncf/glossary/blob/main/style-guide.md).

**Comment by himanshu007-creator** [comment]
Hi i would like to work on this issue

**Comment by JasonMorgan** [comment]
Thanks for helping! I've assigned you the item and set it to in progress.

**Comment by JasonMorgan** [comment]
Issue is up for grabs. @sayantani11 if you're interested let me know and I'll assign it over.

**Comment by kumardeni** [comment]
@JasonMorgan - I can take it up, if it is available.

**Comment by CathPag** [comment]
@kumardeni, as mentioned in the other conversation, we ask for people to work on one term at a time. Once the other term is approved, you can claim another one.

**Comment by reapedjuggler** [comment]
@JasonMorgan, @CathPag I would be glad to take it up, if it is available :smile:

**Comment by CathPag** [comment]
Sounds good :)
