### ISSUE TITLE
Cloud Computing For Hindi

### ISSUE THREAD

**Issue by gauravrattan** [cncf/glossary#1571]
Cloud Computing  Hindi version is not available. If any one read in Hindi then he/she face issue.
Link=https://glossary.cncf.io/cloud-computing/

**Comment by VaibhavJangid** [comment]
I would like to work on this term, I am a native Hindi speaker I would like to translate it into Hindi. If it hasn't been assigned to anyone then please assign it to me.

**Comment by Garima-Negi** [comment]
duplicate of [https://github.com/cncf/glossary/issues/1005](https://github.com/cncf/glossary/issues/1005)
