### ISSUE TITLE
Horizontal scaling definition

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#158]
Please follow format defined in [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md).

**Comment by himanshu007-creator** [comment]
Hi i would like to work on this issue

**Comment by CathPag** [comment]
Thanks, @himanshu007-creator. Once you've submitted a PR for the other term and it was accepted, we can assign you the next one. Hope that's ok.

**Comment by sayantani11** [comment]
Hey I would like to contribute to this issue. Thank you.

**Comment by CathPag** [comment]
Thanks for helping, @sayantani11! Please make sure to review the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) before getting started.

**Comment by sayantani11** [comment]
@CathPag I will.... Thanks for assigning

**Comment by reddymahendra52** [comment]
Hello, Can I work on this issue too?
I would also like to contribute to this community.

**Comment by CathPag** [comment]
@reddymahendra52, thanks for wanting to help! 
As you can see above @sayantani11 already claimed this term. Please pick one that hasn't been assigned yet.
