### ISSUE TITLE
[hi] Localize kubernetes.md to Hindi

### ISSUE THREAD

**Issue by Garima-Negi** [cncf/glossary#1588]
content: [https://glossary.cncf.io/kubernetes/](https://glossary.cncf.io/kubernetes/) 

Please complete DCO requirements before making a PR or commits : [https://wiki.linuxfoundation.org/dco](https://wiki.linuxfoundation.org/dco)

**Comment by Omkar0114** [comment]
Hey, @Garima-Negi I would like to take this one!
Assign it to me :)

**Comment by Omkar0114** [comment]
Thanks for assigning!

**Comment by ARYANis0001** [comment]
Hey @aj11anuj if PR for this issue Localize Kubernetes. md to Hindi #1588 is merged then why this issue is still open
