### ISSUE TITLE
[hi] Localize self-healing.md to Hindi

### ISSUE THREAD

**Issue by Garima-Negi** [cncf/glossary#1593]
content: https://github.com/cncf/glossary/blob/main/content/en/self-healing.md

**Comment by shyamtawli** [comment]
do you want, to covert this file in hindi?

**Comment by chirag0002** [comment]
Hey @Garima-Negi, please assign me this issue.
I do want to work on this.

**Comment by ShivangShandilya** [comment]
\assign

**Comment by ShivangShandilya** [comment]
Hello @Garima-Negi can you please assign this to me so that I can work on this issue ASAP.

**Comment by AniketNS** [comment]
Hello @Garima-Negi, I've already localized one topic. It'd be great if you assign this to me. I'll open a PR as soon as possible.

**Comment by ShivangShandilya** [comment]
@AniketNS hello Aniket, I'm already working on this issue, if possible can you pick another one?

**Comment by AniketNS** [comment]
It's alright Shivang, I'll find another one.

**Comment by VishavSingla** [comment]
hello,
Can you please assign this issue to me if it still needs to be solved?

**Comment by bhanuteja1901** [comment]
hi!! 
i'm beginer to open source .can you assign me

**Comment by AniketNS** [comment]
No, I can't.

**Comment by skushagra9** [comment]
Hey , I would love to work on this issue

**Comment by skushagra9** [comment]
@Garima-Negi

**Comment by Sulochan-khadka** [comment]
@Garima-Negi I would be obliged if you elaborate the issue and then assign me to work on it.

**Comment by ShivangShandilya** [comment]
Guys there is already a PR raised for the same

**Comment by Garima-Negi** [comment]
@ShivangShandilya  Can you please remove horizontal-scaling.md from the self-healing PR above?

you may create a separate issue for horizontal-scaling and create a PR for that.

**Comment by ShivangShandilya** [comment]
Ohh my bad, I'll open another issue for the same.

**Comment by Rohit-Kumar18** [comment]
Hey @Garima-Negi can you please assign me this issue so that I can work on this.

**Comment by bishal7679** [comment]
Closing as completed by #1642
