### ISSUE TITLE
[hi] localize `infrastructure-as-code.md ` to `Hindi`

### ISSUE THREAD

**Issue by YashPimple** [cncf/glossary#1595]
### Please describe why this term needs to be updated

Why this term needs to be updated? (briefly)

Infrastructure as Code (IaC) term available in English only but This term also needs to be Localized into Hindi for the people who want to read this term in Hindi.

visit on page-https://glossary.cncf.io/infrastructure-as-code/

**Comment by ShivangShandilya** [comment]
I can work on this issue, kindly assign this to me.
Regards

**Comment by YashPimple** [comment]
@ShivangShandilya I am currently working on it can you find an another issue .

**Comment by ShivangShandilya** [comment]
sure @YashPimple thanks for telling.
If you're unable to work on this due to some issue do tag me 😄

**Comment by anubha-v-ardhan** [comment]
infrastucture as code already exists for the Hindi localization, I'm sorry but I'll have to close this issue along with the linked PR. 
If you'd like to improve/update the existing definition, feel free to open another issue.

If you believe I misunderstood this issue, feel free to reopen and inform me
