### ISSUE TITLE
Cloud native security >> update to new format

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#160]
https://github.com/cncf/glossary/blob/main/definitions/cloud_native_security.md

Please convert entry to the property format. View the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) for more details.

**Comment by sayantani11** [comment]
I can do this

**Comment by sayantani11** [comment]
If you can assign me

**Comment by CathPag** [comment]
Thanks, @sayantani11. This term is already in review. Please refer to the [project board](https://github.com/cncf/glossary/projects/1) to select terms but wait until your first PR got merged.

**Comment by JasonMorgan** [comment]
Resolved here: https://github.com/cncf/glossary/pull/162

closing
