### ISSUE TITLE
Localise Zero Trust Architecture in hindi

### ISSUE THREAD

**Issue by Anuragwagh** [cncf/glossary#1609]
Zero Trust Architecture is not in hindi 
https://glossary.cncf.io/zero-trust-architecture/

Assign me to work on it

**Comment by VamshiReddy02** [comment]
can I work on this issue?

**Comment by jihoon-seo** [comment]
This issue is a duplicate of #1354.

**Comment by Garima-Negi** [comment]
closing since this is a duplicate PR. Issue for zero-trust architecture is already being worked on and a PR is under review
