### ISSUE TITLE
[Spanish] localize 'Service Mesh'

### ISSUE THREAD

**Issue by krol3** [cncf/glossary#1618]
Localize the content/en/service-mesh.md document to Spanish

**Comment by krol3** [comment]
I would like to work on this translation

**Comment by mdf-ido** [comment]
I can work on this as well

**Comment by electrocucaracha** [comment]
@krol3 voy a regresar este issue a `todo`, avísame en caso contrario

**Comment by marianogg9** [comment]
@electrocucaracha estoy disponible para trabajar en este issue. Gracias!
