### ISSUE TITLE
Localise Horizontal Scaling page in hindi

### ISSUE THREAD

**Issue by VamshiReddy02** [cncf/glossary#1623]
The Hindi version of Horizontal Scaling is not available.
Link: https://glossary.cncf.io/horizontal-scaling/

**Comment by neelshah2409** [comment]
> The Hindi version of Horizontal Scaling is not available. Link: https://glossary.cncf.io/horizontal-scaling/

I would like to work on this @VamshiReddy02 Please assign me.

**Comment by anubha-v-ardhan** [comment]
Hi @SaxenaAnushka102, Are you still interested in this issue?

**Comment by SaxenaAnushka102** [comment]
Hello @anubha-v-ardhan! Sure I can take it up👍

**Comment by SaxenaAnushka102** [comment]
Hello @anubha-v-ardhan! I've created a [PR for this issue](https://github.com/cncf/glossary/pull/1988), please check it out & let me know if any changes have to be made. Thanks!

**Comment by bishal7679** [comment]
Closing as completed by #1988
