### ISSUE TITLE
[Update term] `Function as a Service` for `En`

### ISSUE THREAD

**Issue by pasimoes** [cncf/glossary#1627]
#### Why this term needs to be updated? (briefly)
- 
My suggestion to be more instructive for the reader is to add a description of public cloud providers and also frameworks (famous) which allow building FaaS.

Some examples of Managed Public Cloud FaaS include:

- [AWS Lambda](https://aws.amazon.com/lambda/)
- [Microsoft Azure Functions](https://azure.microsoft.com/en-us/services/functions/).
- [Google Cloud Functions](https://cloud.google.com/functions/)
- [Oracle Cloud Infrastructure Functions](https://www.oracle.com/cloud/cloud-native/functions/)

Some examples of Platforms for executing FaaS in Public and Private Cloud:

- [OpenFaaS](https://www.openfaas.com)
- [Apache OpenWhisk](https://openwhisk.apache.org)
- [Knative](https://www.openfaas.com)

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [X] I want to work on this suggestion. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by Aarav238** [comment]
I would like to work on it. Could you please assign this to me

**Comment by CathPag** [comment]
@pasimoes, unfortunately, we don't want to point to any proprietary products. The Glossary should focus on open source only. I'll go ahead and closes this PR. If there was more to your proposal than adding the examples, please let me know.

**Comment by pasimoes** [comment]
@CathPag I can't understand this point.. currently, the glossary has 3 proprietary options. What I propose was to organize that as bullet points and add another one that is based on an open source project and also list the open source options. I can't understand your point.  I can understand if you say that will remove all current proprietary options and stay with only the open source items. 

`need without paying for services when code isn’t running. Some popular FaaS examples include: [Amazon’s AWS Lambda](https://aws.amazon.com/lambda/), [Google Cloud Functions](https://cloud.google.com/functions/) and [Microsoft Azure Functions](https://azure.microsoft.com/en-us/services/functions/). `
