### ISSUE TITLE
[Update term] `_index.md` for `dev-es`

### ISSUE THREAD

**Issue by krol3** [cncf/glossary#1667]
#### Why this term needs to be updated? (briefly) 
- After merge this https://github.com/cncf/glossary/pull/1644, we need to fix the `_index.md`.

`the content in the _index.md part from the source document has been removed by this PR. (Acknowledgement to the Glossary maintainers)`

**Comment by kumarankit999** [comment]
Hey, I am new in this project, And i would like to work on this issue

**Comment by jihoon-seo** [comment]
@kumarankit999 I guess that you are a native Hindi speaker, and not a native Spanish speaker.
Please leave the Spanish localization jobs for Spanish speakers.

**Comment by kumarankit999** [comment]
ok,No problem

**Comment by marianogg9** [comment]
Hi @jihoon-seo - im a native Spanish speaker, I would love to contribute on this. Thank you!

**Comment by jihoon-seo** [comment]
@marianogg9 it would be great to consult Spanish approvers (@raelga @electrocucaracha @krol3 @92nqb).

**Comment by krol3** [comment]
@marianogg9 , @electrocucaracha, @jihoon-seo 

The index.md section in [spanish](https://github.com/cncf/glossary/blob/main/content/es/_index.md) it seems equal to the [English version](https://github.com/cncf/glossary/blob/main/content/en/_index.md).

Please take a look, to close this issue.
