### ISSUE TITLE
[hi]  Localize `Zero Trust Architecture.md` to Hindi.

### ISSUE THREAD

**Issue by Aarav238** [cncf/glossary#1671]
Page content - https://glossary.cncf.io/zero-trust-architecture/

`Zero Trust Architecture.md` is not available in hindi .

### Why this term needs to be updated?
- `Zero Trust Architecture` term available in English only but This term also needs to be Localized in Hindi.
- visit on page- https://glossary.cncf.io/zero-trust-architecture/

**Comment by mohitvdx** [comment]
Hi I am new to the community. I can translate it to hindi language, though i dont know how to make it available on the glossary page. what should I do?

**Comment by Aarav238** [comment]
Read the contribution guidelines @mohitvdx

**Comment by skushagra9** [comment]
Hey @Aarav238 , I would love to work on this issue

**Comment by Aarav238** [comment]
@skushagra9 I have already submitted the PR regarding this.

**Comment by Aarav238** [comment]
@skushagra9  You should look into the website and check which terms are not localized yet , then raise issue regarding that term and Submit the PR about that.

**Comment by shivam-sharma7** [comment]
hey @jihoon-seo i have already opened a PR for this 2 month ago #1387

**Comment by shivam-sharma7** [comment]
#1387

**Comment by jihoon-seo** [comment]
@shivam-sharma7 you are right.
This issue is a duplicate of #1354.

**Comment by Garima-Negi** [comment]
This is a duplicate issue as @jihoon-seo has mentioned.

@Aarav238 Please go through open issues before creating new ones. Thank you.
