### ISSUE TITLE
[New term] `BugReport`

### ISSUE THREAD

**Issue by kumarankit999** [cncf/glossary#1676]
#### What this term is about? (briefly)
- A bug report is document used to describe a bug or problem within computer system. It is typically used by software  engineers, and other technical personnel to report issues and problems with computer systems, software, and hardware. Bug reports contain information about the issue, including a description of the problem, the affected system, and any steps that were taken to try to fix the problem. They also may include screenshots or other evidence of the issue as well as any recommendations for how to resolve it.
#### Why this term needs to be added? (briefly) 
- It is to be added Because it helps developers identify and fix the problem quickly. It provides a clear understanding of the issue and gives the developers a starting point to find the solution. A bug report can also provide valuable information about the user experience and help developers create better software. By providing bug reports, users can help make sure that their favorite software is working correctly and efficiently.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [x] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by jihoon-seo** [comment]
@kumarankit999 Thank you for your suggestion, but I think that the term 'bug report' is rather a general computer/tech term, and neither fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) nor is essential to understanding cloud native terms.
Please check the first item of the checklist above again.

**Comment by seokho-son** [comment]
I agree with @jihoon-seo

**Comment by seokho-son** [comment]
Hi @kumarankit999 
Thank you for the suggestion as @jihoon-seo mentioned, maintainers think BugReport is not appropriate for Cloud Native Glossary. Please looking for other contribution points. Let me close this Issue.
