### ISSUE TITLE
Need to rebase all dev-xx (branch for l10n) with main

### ISSUE THREAD

**Issue by seokho-son** [cncf/glossary#1681]
Hello, this issue is from the maintainers.

Since there are several major changes that affect to development branches for localization (Tags for terms, Deprecated terms, Labeler workflow), all localization branches (dev-xx) needs to be updated.

This is an action item to all localization teams. (especially for the members who are managing development branch itself)

Let me check all localization branches are updated.

- [x] dev-ko
- [x] dev-bn
- [x] dev-hi
- [x] dev-es
- [x] dev-fr
- [x] dev-pt
- [x] dev-zh
- [x] dev-it
- [x] dev-de
- [x] dev-ur
- [x] dev-ar

Please note that there is a target date to complete this issue. After the target date, some PRs to a dev-xx branch which is not updated can face `Some checks were not successful`.

Target date: Feb. 12

**Comment by seokho-son** [comment]
https://github.com/cncf/glossary/pull/1682 is an example to update a dev-xx branch.

**Comment by seokho-son** [comment]
Not mandatory in case of `dev-es`, `dev-pt` which have been updated recently. ;)

**Comment by iamNoah1** [comment]
Here is the PR for rebasing dev-de with main: https://github.com/cncf/glossary/pull/1686

**Comment by seokho-son** [comment]
> shivaabhishek07

Hi @shivaabhishek07 
I am not sure I understood your problem correctly. 
- Do you want to push commits in your local branch to dev-hi branch of upstream (cncf/glossary) ? (it is not allowed in general. we need to open a PR for that)
- or.. your problem is that you can not push commits in your local branch to dev-hi branch of your remote repository (shivaabhishek07/glossary) because of any conflict?

**Comment by shivaabhishek07** [comment]
Hey @seokho-son, what you have understood is absolutely correct (first point).
Thanks for letting me know that I have to open a PR.

**Comment by shivaabhishek07** [comment]
Here it is for `dev-hi` #1690

**Comment by seokho-son** [comment]
Complete ! Thanks all!
