### ISSUE TITLE
[hi] Localize Idempotence to Hindi

### ISSUE THREAD

**Issue by neelshah2409** [cncf/glossary#1693]
#### Why this term needs to be updated? (briefly) 
- https://glossary.cncf.io/idempotence/
- Idempotence should also be added in Hindi

**Comment by GH-aditya** [comment]
Assign me

**Comment by gauravrattan** [comment]
assign me @Garima-Negi @anubha-v-ardhan

**Comment by kelvinparmar** [comment]
Hello @dixitrathi7
I am Kelvin Parmar , I am interested to an issue if no one working in this issue then please assign me.

**Comment by SaxenaAnushka102** [comment]
Hi @sayantani11! I'd like to take up this issue could you please assign it to me?

**Comment by shubham-singh-748** [comment]
First of all, why this term needs to be updated, because of Hindi folks, those who don't know English much, then it would be efficient for them to read.

hey @neelshah2409 , this issue quite interesting to me, i want to work on this issue, if someone is not working anymore.

**Comment by neelshah2409** [comment]
Hii @Garima-Negi ,I have made a PR already (#1729 ) Please review it .

**Comment by bishal7679** [comment]
closing as completed by #1729
