### ISSUE TITLE
[hi] Localize horizontal-scaling.md in Hindi

### ISSUE THREAD

**Issue by ShivangShandilya** [cncf/glossary#1699]
content : https://github.com/cncf/glossary/blob/main/content/en/horizontal-scaling.md

**Comment by ShivangShandilya** [comment]
I am working on this issue and will open a PR for the same shortly

**Comment by jihoon-seo** [comment]
This issue is a duplicate of #1623.

**Comment by ShivangShandilya** [comment]
oops sorry, I'll close this one. Thanks for telling
