### ISSUE TITLE
Container definition not started

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#17]
Need someone to fill in a definition for container. You can find it [here](https://github.com/cncf/glossary/blob/main/definitions/container.yaml)

**Comment by TheJaySmith** [comment]
https://github.com/cncf/glossary/blob/main/definitions/container.md

**Comment by TheJaySmith** [comment]
[PR 37](https://github.com/cncf/glossary/pull/37)

**Comment by IdealUsrname** [comment]
Please open a new issue for discussion/feedback. Thanks!
