### ISSUE TITLE
[hi] Rename some markdown files

### ISSUE THREAD

**Issue by jihoon-seo** [cncf/glossary#1732]
In [`content/hi/` directory of `dev-hi` branch](https://github.com/cncf/glossary/tree/dev-hi/content/hi), you can see that some of markdown files have underscores (`_`) in their filename.
We decided to replace spaces (` `) and underscores (`_`) to hyphen (`-`), so those need to be replaced as well.

If you want to contribute, please
- first make sure that you are assigned, and then
- open single PR that renames 2 files: `bare_metal_machine.md` and `client_server_architecture.md`.

**Comment by shivam-sharma7** [comment]
@jihoon-seo  can you assign me?

**Comment by dixitrathi7** [comment]
HI @jihoon-seo I want to work on this issue please Assign me

**Comment by jihoon-seo** [comment]
@shivam-sharma7 left comment first, so @shivam-sharma7 please go ahead!

**Comment by Raj7Dev** [comment]
can you assign me if this issue is still open?

**Comment by abhay-raj19** [comment]
hey @jihoon-seo is this issue still in pending? I want to wor

**Comment by abhay-raj19** [comment]
hey, @jihoon-seo is this issue still pending?
If it is so i want to work on it and will do it in a quick faster way..
Pls do assign me

**Comment by anubha-v-ardhan** [comment]
@0xRajvardhan @abhay-raj19, PR #1834 is under review for a solution to this issue, so we'll not be able to assign you this for now. I hope you'll be able to find another issue of your interest and continue contributing.

**Comment by balkishanmandal** [comment]
Can u please assign me this issue?

**Comment by shivam-sharma7** [comment]
@balkishanmandal I am already assigned look for another issues

**Comment by gunjjoshi** [comment]
> In [`content/hi/` directory of `dev-hi` branch](https://github.com/cncf/glossary/tree/dev-hi/content/hi), you can see that some of markdown files have underscores (`_`) in their filename. We decided to replace spaces (` `) and underscores (`_`) to hyphen (`-`), so those need to be replaced as well.
> 
> If you want to contribute, please
> 
> * first make sure that you are assigned, and then
> * open single PR that renames 2 files: `bare_metal_machine.md` and `client_server_architecture.md`.

Assign this to me so that I can rename the files.

**Comment by kumarankit999** [comment]
Hey @shivam-sharma7, it's been 3 month and still this issue hasn't been closed yet. So, kindly @jihoon-seo assign to another folk, who want to work on this

**Comment by gunjjoshi** [comment]
@jihoon-seo Assign this to me so that the work can be done properly. This should have been completed till now.

**Comment by jihoon-seo** [comment]
This issue has been resolved by the PR #2352.
