### ISSUE TITLE
[hi] Localize Edge Computing to Hindi

### ISSUE THREAD

**Issue by neelshah2409** [cncf/glossary#1734]
Why this term needs to be updated? (briefly)
https://glossary.cncf.io/edge-computing/
Edge Computing should also be added in Hindi

**Comment by dixitrathi7** [comment]
Hi @jihoon-seo I want to work on this issue Assign me, thanks

**Comment by jihoon-seo** [comment]
@dixitrathi7 instead of asking me, it would be great to ask Hindi localization approvers (@Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava) to be assigned.

**Comment by dixitrathi7** [comment]
Hi @Garima-Negi (@sayantani11 @anubha-v-ardhan @jayesh-srivastava) I want to work on the issue that raise by @neelshah2409 
Assign me.

**Comment by akshatcoder-hash** [comment]
Hey there! @Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava! I would love to work on this issue. Could you please assign it to me?

**Comment by Aryan-Singla** [comment]
@kumarankit999  If no one is working on it please assign to me

**Comment by kumarankit999** [comment]
Hey @Aryan-Singla, @akshatcoder-hash has already raised a PR and you can check the latest comment on that!

**Comment by aj11anuj** [comment]
Since a long time, there isn't any response from Akshat's side. So, Aryan you can work on this issue.

**Comment by Aryan-Singla** [comment]
@aj11anuj I will raise PR in a few days
