### ISSUE TITLE
Screenshot in `How To contribute`need update.

### ISSUE THREAD

**Issue by Petrie** [cncf/glossary#1751]
For example : 
![image](https://user-images.githubusercontent.com/2252964/221520067-7108628c-0d68-40ca-8a1f-5e69d69719b5.png)

We have updated the website with a new style, so the screenshot should also be updated.

**Comment by Faizan711** [comment]
Is anyone working on it, if not i would like to get assigned for it.

**Comment by Petrie** [comment]
Can any maintainer assign this to @Faizan711.
@jihoon-seo @seokho-son

**Comment by Faizan711** [comment]
Ok, i will make the change and make a PR.
