### ISSUE TITLE
[New term] `Admission Controller`

### ISSUE THREAD

**Issue by oshi36** [cncf/glossary#1758]
#### What this term is about? (briefly)
- Admission Controller is an important part of the Kubernetes API server, which checks whether the incoming requests of the object are valid or not from the authenticated user.

#### Why this term needs to be added? (briefly) 
- This needs to be added because it is important to understand in terms of DevOps and security. It provides control to resources to be deployed in order to limit the risk.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by oshi36** [comment]
Hi @seokho-son, please let me know whether this term can be included in the glossary or not. I have messaged on slack also regarding this.

**Comment by seokho-son** [comment]
Hi @oshi36 Thank you for the suggestion.
Maintainers are discussing to triage this issue.

**Comment by oshi36** [comment]
sure @seokho-son , also please mention to maintainers that `Dynamic admission controller` should be a part of it or it will be a separate term.

**Comment by seokho-son** [comment]
Actually, I think `Admission Controller` is Kubernetes-specific term which may not fit with the Cloud native Glossary. (there is definition in [K8s website](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#what-are-they) already) We don't want duplicated definitions.
Maintainers are discussing for `Admission Control` which can be a more general term. But not determined yet. :)
I guess `Dynamic admission controller` is even more detail term hard to be generalized.
Anyway, I will share your request to maintainers. :)

**Comment by seokho-son** [comment]
Hi @oshi36 
Maintainers decided not to include `Admission Controller` in the Glossary. 
- Admission Controller is advanced and Kubernetes-specific term which may not fit with the Cloud native Glossary. (there is definition in [K8s website](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#what-are-they) already) We don't want duplicated definitions.

**Comment by seokho-son** [comment]
Thank you for the suggestion ! :)
