### ISSUE TITLE
Create definition for serverless 

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#176]
when creating the definition, please make sure to follow the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md)

**Comment by sayantani11** [comment]
Hey @CathPag can I work on this or wait for the previous PR to be reviewed?

**Comment by sandipanpanda** [comment]
Hey @CathPag I am a complete beginner to open source and I would love to work on this good first issue.

**Comment by ShivamTyagi12345** [comment]
i would like to help with this non-code contribution

**Comment by CathPag** [comment]
@sayantani11, before assigning something new to you, I'd like to finalize your PR. I've been reworking it a bit and would like for you to get some feedback before tackling a new term. That way you can use that feedback for the next term. Currently, I'm the only maintainer who's available (everyone else is on vacation or busy with other projects) and before finalizing the review, I'd like to discuss it with one of them. 

I did update the [style guide](https://github.com/cncf/glossary/pull/179/files?short_path=8572650)  but the change hasn't been merged yet.

@sandipanpanda, you're welcome to work on this. Please also read the change in the style guide reflected in the PR linked above.

@ShivamTyagi12345, I'm afraid Sandipanpanda claimed this before you did.

**Comment by sandipanpanda** [comment]
@CathPag thank you for assigning. I have read the changes reflected in the updated style guide in the PR linked by you and will contribute accordingly.
