### ISSUE TITLE
[Spanish] localize 'Search Results'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1767]
Localize the `content/en/search.md` document to Spanish

**Comment by marianogg9** [comment]
@electrocucaracha podria trabajar en este issue por favor? gracias!

**Comment by MartinEliasQ** [comment]
@electrocucaracha Me gustaria trabajar en este Issue. Gracias!

**Comment by ramrodo** [comment]
closed by https://github.com/cncf/glossary/pull/2086
