### ISSUE TITLE
[Spanish] localize 'Self Healing'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1769]
Localize the `content/en/self-healing.md` document to Spanish

**Comment by adityaxxz** [comment]
@electrocucaracha Sure , i'll do it assign it to me , i'll PR asap. thank you

**Comment by adityaxxz** [comment]
@electrocucaracha  hey , I created a PR for `content/en/self-healing.md` , but forgot to sign off 2 of my commits , this is my first time contributing , so maybe u can help me redoing it .

**Comment by electrocucaracha** [comment]
> @electrocucaracha hey , I created a PR for `content/en/self-healing.md` , but forgot to sign off 2 of my commits , this is my first time contributing , so maybe u can help me redoing it .

Did you do it through the WebUI? Or the command line? More likely, you'll have to amend the commit and push the change over the same opened PR

**Comment by adityaxxz** [comment]
> > @electrocucaracha hey , I created a PR for `content/en/self-healing.md` , but forgot to sign off 2 of my commits , this is my first time contributing , so maybe u can help me redoing it .
> 
> Did you do it through the WebUI? Or the command line? More likely, you'll have to amend the commit and push the change over the same opened PR

Sure , will do.

**Comment by ramrodo** [comment]
closed by https://github.com/cncf/glossary/pull/2098
