### ISSUE TITLE
[Spanish] localize 'Service Proxy'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1772]
Localize the `content/en/service-proxy.md` document to Spanish

**Comment by Ambareen09** [comment]
Can I please take up this issue?

**Comment by electrocucaracha** [comment]
Thanks for participating into the CNCF Glossary project. The Spanish translation team would like to facilitate your contribution's journey, so please share your goals and/or skills in order to assist you better. We also encourage new contributors to participate in their native speaking language.
