### ISSUE TITLE
[Spanish] localize 'Definition Template'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1778]
Localize the `content/en/_TEMPLATE.md` document to Spanish

**Comment by ai-naymul** [comment]
Hello there,
I would like to work on this could you please assign me this!
Thank you :)

**Comment by electrocucaracha** [comment]
Thanks for participating into the CNCF Glossary project. The Spanish translation team would like to facilitate your contribution's journey, so please share your goals and/or skills in order to assist you better. We also encourage new contributors to participate in their native speaking language.

**Comment by marianogg9** [comment]
@electrocucaracha estoy libre para trabajar en este issue. Gracias!
