### ISSUE TITLE
[Spanish] localize 'Tightly Coupled Architectures'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1779]
Localize the `content/en/tightly-coupled-architectures.md` document to Spanish

**Comment by ai-naymul** [comment]
Hello there,
I would like to work on this could you please assign me this!
Thank you :)

**Comment by jossemarGT** [comment]
Hi,

It seems this ticket (and its PR #1854 ) got staled, can I get assign to it?

Regards.

**Comment by ramrodo** [comment]
closed by https://github.com/cncf/glossary/pull/2194
