### ISSUE TITLE
[Spanish] localize 'Version Control'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1781]
Localize the `content/en/version-control.md` document to Spanish

**Comment by ShankyJS** [comment]
Hey @electrocucaracha do you mind assigning me this one please!

**Comment by MartinEliasQ** [comment]
@electrocucaracha Me gustaría abordar este Issue. ¡Gracias!

**Comment by ramrodo** [comment]
closed by https://github.com/cncf/glossary/pull/2103
