### ISSUE TITLE
[Spanish] localize 'Vertical Scaling'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1782]
Localize the `content/en/vertical-scaling.md` document to Spanish

**Comment by ShankyJS** [comment]
Hey @electrocucaracha do you mind assigning me this one please!

**Comment by electrocucaracha** [comment]
@ShankyJS I'll move this to the backlog, let me know in case that you have some progress.

**Comment by marianogg9** [comment]
@electrocucaracha estoy libre para trabajar en este issue. Gracias!
