### ISSUE TITLE
[Spanish] localize 'Virtualization'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1783]
Localize the `content/en/virtualization.md` document to Spanish

**Comment by ShankyJS** [comment]
Hey @electrocucaracha please assign me this one!

**Comment by electrocucaracha** [comment]
@ShankyJS I'll move this to the backlog, let me know in case that you have some progress.

**Comment by marianogg9** [comment]
@electrocucaracha estoy libre para trabajar en este issue. Gracias!

**Comment by ramrodo** [comment]
closed by https://github.com/cncf/glossary/pull/2070
