### ISSUE TITLE
[Spanish] localize 'Zero Trust Architecture'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#1785]
Localize the `content/en/zero-trust-architecture.md` document to Spanish

**Comment by josefloressv** [comment]
@electrocucaracha me gustaría trabajar en este issue

**Comment by electrocucaracha** [comment]
@josefloressv I'll move this to the backlog, let me know in case that you have some progress.

**Comment by MartinEliasQ** [comment]
Hola @electrocucaracha me gustaría trabajar en este issue. ¡Gracias!

**Comment by ramrodo** [comment]
closed by https://github.com/cncf/glossary/pull/2122
