### ISSUE TITLE
[Spanish] localize 'Service'

### ISSUE THREAD

**Issue by 92nqb** [cncf/glossary#1786]
Localize the `content/en/service.md` document to Spanish

**Comment by adityaxxz** [comment]
@92nqb  Sure , i'll do it assign it to me , i'll PR asap. thank you. :)

**Comment by rohan-choudharyy** [comment]
Is anyone working on this? I would like to contribute

**Comment by electrocucaracha** [comment]
Thanks for participating into the CNCF Glossary project. The Spanish translation team would like to facilitate your contribution's journey, so please share your goals and/or skills in order to assist you better. We also encourage new contributors to participate in their native speaking language.

**Comment by adityaxxz** [comment]
> 
Their preference is to have solely individuals who are native speakers of the language participate/contribute in the efforts towards improvement.

**Comment by adityaxxz** [comment]
> > 
> 
> Their preference is to have solely individuals who are native speakers of the language participate/contribute in the efforts towards improvement.



> Is anyone working on this? I would like to contribute

Their preference is to have solely individuals who are native speakers of the language participate/contribute in the efforts towards improvement.

**Comment by abhay-raj19** [comment]
Hey,members is anyone working on this issue. I would like to work for this issue.

**Comment by electrocucaracha** [comment]
@abhay-raj19 thanks for participating on this. Are you a Spanish native speaker? If that's not the case, we encourage contributors to participate in the translation of other languages, unless they have different goals in mind. This decision was taken to reduce the burden during the review process.

**Comment by abhay-raj19** [comment]
I am native english speaker, am a resident of India.

**Comment by electrocucaracha** [comment]
> I am native english speaker, am a resident of India.

Well, in that case you can contribute to other translations like [Hindi](https://github.com/cncf/glossary/tree/main/content/hi) or English.

**Comment by MartinEliasQ** [comment]
@electrocucaracha Me gustaría tomar  este Issue.

**Comment by ramrodo** [comment]
closed by https://github.com/cncf/glossary/pull/2091
