### ISSUE TITLE
[Spanish] localize 'Service Discovery'

### ISSUE THREAD

**Issue by 92nqb** [cncf/glossary#1788]
Localize the `content/en/service-discovery.md` document to Spanish

**Comment by Kanika637** [comment]
Can I work on this issue, with some guidance?

**Comment by electrocucaracha** [comment]
Thanks for participating into the CNCF Glossary project. The Spanish translation team would like to facilitate your contribution's journey, so please share your goals and/or skills in order to assist you better. We also encourage new contributors to participate in their native speaking language.

**Comment by marianogg9** [comment]
@electrocucaracha im free to work on this issue please. Thanks!
