### ISSUE TITLE
Localise Horizontal Scaling page in Bengali

### ISSUE THREAD

**Issue by sajdakabir** [cncf/glossary#1866]
The Bengali version of Horizontal Scaling is not available.
Link: https://glossary.cncf.io/horizontal-scaling/

@waleed318  Can you assign it to me? I want to work on this issue.

**Comment by waleed318** [comment]
Hello sajdakabir, I am Urdu glossary approver please contact your bengali team. 🙂

**Comment by sajdakabir** [comment]
@jihoon-seo Can I work on this issue?

**Comment by asem-hamid** [comment]
@sajdakabir  already Localized by  someone

https://glossary.cncf.io/bn/horizontal-scaling/

**Comment by asem-hamid** [comment]
@mitul3737 This issue is already fixed.

**Comment by sajibAdhi** [comment]
The issue is already fixed in this [PR](https://github.com/cncf/glossary/pull/1814). I am closing this issue.
