### ISSUE TITLE
[ur] Localize Cloud Computing Term(s) in Urdu

### ISSUE THREAD

**Issue by zhaque44** [cncf/glossary#1874]
label: lang/ur

I would like to participate in the localization of "Cloud Computing" terms in Urdu.

**Comment by waleed318** [comment]
You are good to go @zhaque44 !

**Comment by Saim-Safdar** [comment]
Thanks Zubair, looks good to proceed.

**Comment by Saim-Safdar** [comment]
Looks good

**Comment by waleed318** [comment]
Closing Issue as PR Merged
