### ISSUE TITLE
[New term] `Runtime`

### ISSUE THREAD

**Issue by cjyabraham** [cncf/glossary#1892]
#### What this term is about? (briefly)
- I wish I knew what it means. I came to the glossary looking for the answer but didn't find it.
#### Why this term needs to be added? (briefly) 
- I guess it's a common term in Cloud Native land? We have a [Runtime TAG](https://github.com/cncf/tag-runtime) so it must be quite important?

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [ ] I want to work on this term and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)". (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by CathPag** [comment]
While runtime can mean many things in different contexts, this term should start with a general definition and then explain what it means in the context of cloud native. 

Want to work on this term? Please read the "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)" section of our how-to guide. If that is you, let us know 🙂

**Comment by ekranjan23** [comment]
I would like to work on this term

**Comment by CathPag** [comment]
Great! Before I assign it to you, can you please confirm have deep cloud native expertise as outlined in the "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)" section?

**Comment by arunkarthicknm** [comment]
Shall I work on this?

**Comment by CathPag** [comment]
Hi @arunkarthicknm, you can....if you can confirm you have deep cloud native expertise as outlined in the "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)" section.

**Comment by akshatcoder-hash** [comment]
Hey @CathPag! I would love to work on this issue. Could you please check with @arunkarthicknm if he's working on this or not?

**Comment by CathPag** [comment]
Hi @akshatcoder-hash, @arunkarthicknm  didn't respond, so I assume they read the "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)" section and realized they didn't meet the requirements. Can you please confirm you do?

**Comment by akshatcoder-hash** [comment]
Hey @CathPag!
Yes, I meet the requirements and I have been contributing to the repository for more than an year now.
I an ready to work on this issue.

**Comment by CathPag** [comment]
Excellent, thanks for confirming. It's all yours.
