### ISSUE TITLE
[New term] `GlossaryTermHere`

### ISSUE THREAD

**Issue by ekranjan23** [cncf/glossary#1896]
#### What this term is about? (briefly)
- This is first word which is contribute by me.
#### Why this term needs to be added? (briefly) 
- 

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)". (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by seokho-son** [comment]
Hi @ekranjan23
You can think opening an Issue or PR is a kind of proposal. So, a proper title, contents along with the given template are important in open source contribution. Obviously, this issue does not include meaningful contents.
Let me close this issue. Recommend you to check https://glossary.cncf.io/contribute/ first. :)
