### ISSUE TITLE
Zero Trust Architecture

### ISSUE THREAD

**Issue by NIKITA-M-VERMA** [cncf/glossary#1927]
## How it helps

Enhanced visibility and control By monitoring and controlling access to resources in real-time.
Improved visibility and control over network activities, makes  it easier to detect and respond to potential security incidents.
ZTA can help organizations comply with regulatory requirements by providing a framework for implementing security controls and monitoring access to sensitive data and resources.
ZTA provides a higher level of security by enforcing the principle of least privilege, ensuring that users and devices only have access to the resources they need, and limiting lateral movement within the network.

**Comment by seokho-son** [comment]
Hi @NIKITA-M-VERMA 
You can think opening an Issue or PR is a kind of proposal. So, a proper title, contents along with the given template are important in open source contribution.

Let me close this issue and please retry. :)
