### ISSUE TITLE
[New term] `WebAssembly`

### ISSUE THREAD

**Issue by seokho-son** [cncf/glossary#1942]
#### What this term is about? (briefly)
- WebAssembly (abbreviated Wasm) is a binary instruction format for a stack-based virtual machine. Wasm is designed as a portable compilation target for programming languages, enabling deployment on the web for client and server applications. (https://webassembly.org)
- We may utilize WebAssembly instead of Container in several use cases.

#### Why this term needs to be added? (briefly) 
- Recently, there are several initiatives to integrate or utilize WebAssembly technologies in the Cloud Native computing. (https://www.cncf.io/blog/2022/11/17/better-together-a-kubernetes-and-wasm-case-study/ , https://landscape.cncf.io/wasm)
- Although there is an official definition of WebAssembly available (https://webassembly.org), WebAssembly is still a difficult concept for non-technical users and requires a simpler explanation. 
- It would be better to describe `how WebAssembly helps` from the perspective of Cloud Native in the Cloud Native Glossary.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)". (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by arunkarthicknm** [comment]
Shall I work on this?

**Comment by iamNoah1** [comment]
@arunkarthicknm do you still work on it?

**Comment by arunkarthicknm** [comment]
Yeah sure! @iamNoah1
