### ISSUE TITLE
Zero Trust Architecture

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#197]
Finalize definition for [ZTA](https://github.com/cncf/glossary/blob/main/definitions/zero_trust_architecture.md
)

**Comment by Asmit2952** [comment]
Hey @JasonMorgan @CathPag can I work on this issue?

**Comment by CathPag** [comment]
@Asmit2952, my apologies, but we already have a definition for[ zero trust architecture](https://github.com/cncf/glossary/blob/main/definitions/zero_trust_architecture.md). I think it's pretty solid and only needs final review to make sure it's ready for V2. That's our mistake, it shouldn't have been in the "for next release" column. Can you pick a different term?

**Comment by Asmit2952** [comment]
@CathPag No problem, I actually also commented on Virtual Machine #196. Could you assign me that or any other term? I can work on those.
