### ISSUE TITLE
Localization for `distributed-systems`is missing in French

### ISSUE THREAD

**Issue by Horgix** [cncf/glossary#1973]
### Please describe why this term needs to be updated

The `distributed-systems` concept that exists in the English glossary on <https://glossary.cncf.io/distributed-systems/> isn't translated in French currently.

As discussed with @huats and @Krast76 (as the FR core reviewers) during the KubeCon+CloudNativeCon EU 2023 on the 2023-04-21, this is part of the core set of (14) concepts to have some minimal viable translation.

I'd like to work on this and already got a PR ready to be sent as soon as this is assigned to me :relaxed:

**Comment by abhay-raj19** [comment]
Hey @Horgix Hindi version of  "Distributed System" is also missing in it.
But I can fix it up as I am a native Indian and I know Hindi very well so I can convert it Up .
Pls do check it up .
And Help me to contribute it for the same .

**Comment by abhay-raj19** [comment]
Or I should create a new issue regarding the above case, what do you say @Horgix  ?

**Comment by jihoon-seo** [comment]
@abhay-raj19 you had to open a new issue regarding the Hindi localization of the term 'Distributed System', but since there exists the issue that have already been opened (#1300), so you don't need to.
