### ISSUE TITLE
Definition needed for SaaS

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#198]
Needs to be written and finalized for V2. Please request to be assigned to it and refer to the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) before getting started.

**Comment by CathPag** [comment]
@sandipanpanda, we added a bunch of new issues. Wanna work on any of them? If so, please check the [project board](https://github.com/cncf/glossary/projects/1). Your serverless definition was great! If you have time, we'd love you to contribute more!

**Comment by sandipanpanda** [comment]
@CathPag Thank you for the opportunity! I am ready and would love to contribute more. I am excited to pick up and work on the new issues!

**Comment by CathPag** [comment]
Great! Let us know what you want to work on and we'll assign it to you :)

**Comment by sandipanpanda** [comment]
Shall I pick up this?

**Comment by CathPag** [comment]
Sure! Didn't want to choose SaaS for you but if this sounds good, let's do it!

**Comment by sandipanpanda** [comment]
> Sure! Didn't want to choose SaaS for you but if this sounds good, let's do it!

I am willing to take up and work on the issue that you find me a good fit for. Can you please choose and assign that to me if that's possible?

**Comment by CathPag** [comment]
I already did, it's yours :)

**Comment by hippyaki** [comment]
@CathPag The spell check failed for the definition. Let me know if I can make changes to it.
