### ISSUE TITLE
Definition needed for PaaS

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#199]
Need to create and finalize for V2. Please request to be assigned to it and refer to the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) before getting started.

**Comment by ShivamTyagi12345** [comment]
hey @JasonMorgan  can i help with the same
I am a beginner to this community and am looking to get started

**Comment by Anubhavjoshi040** [comment]
Hey @CathPag, Can I work on this definition?

**Comment by CathPag** [comment]
Looks like @ShivamTyagi12345 claimed this first, @Anubhavjoshi040. Since Shivam is new, maybe you could collaborate on this? Just an idea and no need at all to do so. I'll assign this to Shivam and you can decide what to do.  If you want your own term, please claim another one.

**Comment by CathPag** [comment]
Please disregard. @ShivamTyagi12345, you already claimed one today. Please work on that one first. Once your PR is approved, you can tackle another term. @Anubhavjoshi040, I'll assign this to you.

**Comment by Anubhavjoshi040** [comment]
@CathPag @ShivamTyagi12345 is already assigned on a different issue.

**Comment by Anubhavjoshi040** [comment]
Thank You!

**Comment by ShivamTyagi12345** [comment]
sure
