### ISSUE TITLE
Distributed Systems: how it helps missing 

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#20]
In this distributed system entry [,](https://github.com/cncf/glossary/blob/main/definitions/distributed_systems.yaml) the "how it helps" part is missing.

**Comment by SamDelamarter** [comment]
Hi @CathPag, it looks like the how it helps section was added, so this issue can probably be closed.

**Comment by CathPag** [comment]
Thanks, @SamDelamarter, actually the last section, how it helps, is missing. We are currently only addressing the what it is and the problem it addresses.

**Comment by Vivek-Hotti** [comment]
Please see PR #66 .
