### ISSUE TITLE
Definition needed for IaaS

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#200]
Needs to be written and finalized for V2. Please request to be assigned to it and refer to the [style guide ](https://github.com/cncf/glossary/blob/main/style-guide.md)before getting started.

**Comment by kumardeni** [comment]
@CathPag - i can take up, if available

**Comment by CathPag** [comment]
Sure! 
I saw you also requested to work on vertical scaling. You can only claim one term at a time, so please work on this one first. When it's approved, you can claim the next.

**Comment by ashish-patwal** [comment]
Hey @CathPag , i want to work on this issue .

**Comment by CathPag** [comment]
@ashish-patwal, Kumar has already claimed this term. Please pick a different one.
