### ISSUE TITLE
Definition needed for managed service

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#202]
Needs to be written and finalized for V2. Please request to be assigned to it and refer to the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) before getting started.

**Comment by ShivamTyagi12345** [comment]
hey @CathPag  Can I Help with this

**Comment by CathPag** [comment]
Great, thanks!

**Comment by ShivamTyagi12345** [comment]
hey @CathPag  ,I have made my PR .Please have a look. Thanks.
