### ISSUE TITLE
[FR] Localization of Container Image into french.

### ISSUE THREAD

**Issue by huats** [cncf/glossary#2031]
Localize Container Image in French

**Comment by jihoon-seo** [comment]
@huats As you may already know, the status of the term 'Container Image' is 'Feedback Appreciated', which means that the term is intentionally not visible in the website and there exists possibility that the term gets deprecated.
So it is encouraged to localize other 'Completed' terms, than this one.
Please consider the points mentioned above. 😊

**Comment by huats** [comment]
Hello @jihoon-seo I am not sure what to do with container-image. I clearly understand your point with the "Feedback Appreciated" but on the other side, the containerization text refers to the text of "container-image" https://github.com/cncf/glossary/blob/main/content/en/containerization.md
Does it mean that we have to remove the link to that page in our translation ? Or do we don't treat container-image as "Feedback Appreciated" and translate it ? I would prefer go for the later.

**Comment by huats** [comment]
Please also note that in the Korean version(by instance) container-image is not translated but the link in containerization is still there, which lead to redirect the visitor to the english version of the glossary, which I think is not great.

**Comment by jihoon-seo** [comment]
Considering that the status of the term 'Container Image' is 'Feedback Appreciated', it would be great to remove all the links that go to the term 'Container Image' and its localized versions if any.
I will open a PR that resolves this issue (to remove links to 'deprecated' / 'Feedback Appreciated' terms)!

**Comment by sestegra** [comment]
Close this issue for now. A new issue will be opened as soon as the `container-image` status passes to `Completed`.
