### ISSUE TITLE
[hi] Localize `Service Discovery` in Hindi.

### ISSUE THREAD

**Issue by Aarav238** [cncf/glossary#2058]
Page content - https://glossary.cncf.io/service-discovery/

`Zero Trust Architecture.md` is not available in hindi .

# Please describe why this term needs to be updated
- `Service Discovery` term available in English only but This term also needs to be Localized in Hindi.
- visit on page- https://glossary.cncf.io/service-discovery/

**Comment by Aarav238** [comment]
@jihoon-seo  should i raise pr regarding this.

**Comment by jihoon-seo** [comment]
Rather than asking to me, please ask to the Hindi localization approvers: @Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava .

**Comment by nikhilchauhangithub** [comment]
kindly assign this to me, as hindi is my native language, i am good fit for this issue
