### ISSUE TITLE
Add a procedure to join the CNCF Slack workspace

### ISSUE THREAD

**Issue by yunkon-kim** [cncf/glossary#2082]
Hi folks!

I'd like to talk about adding a procedure(or just a link) to join the **CNCF Slack workspace** on the main page of [Cloud Naive Glossary](https://glossary.cncf.io/).

(Perhaps this will be added near the red line. 😃)
![image](https://github.com/cncf/glossary/assets/7975459/c8595f6b-3434-48d4-a823-5bfaa3a69c91)

### Background
I've seen some Korean contributors struggle with joining the glossary's Slack channel via link.
- (for example) #glossary-localization-korean: https://cloud-native.slack.com/archives/C02PC0MLQKU

In that case, I had to manually add them using the Slack channel's "Add People" feature.

### Question
<ins> First I'm wondering if any of the folks have the same issue or not. </ins>

### Suggestion and  the reason why I suggest
If so, I think it can be a solution for contributors to join the **CNCF Slack workspace** first on the link, https://communityinviter.com/apps/cloud-native/cncf.

In fact, while guiding contributors to join the CNCF Slack workspace first, no one mentioned channel join issues.

This could be a way for contributors to join Glossary using only a guide.

As an example:
```diff
- Anyone who ..., and join the [#glossary](https://cloud-native.slack.com/archives/C02TX20MQBB) channel on the CNCF Slack. ....
+ Anyone who ..., join the [CNCF Slack](https://communityinviter.com/apps/cloud-native/cncf) workspace, and join the [#glossary](https://cloud-native.slack.com/archives/C02TX20MQBB) channel. ...
```

**Comment by ronitblenz** [comment]
Assign me if you need this issue to be fixed

**Comment by seokho-son** [comment]
Regardless of the condition weather other folks are also experiencing the same issue or not, I think we can update the guide. 
So, yes! I agree. I'd like to accept the suggestion. 
Thanks @yunkon-kim !

If you want to work on this issue, you can assign your self. (If not, please assign @ronitblenz)

**Comment by ronitblenz** [comment]
I am open to take the issue?

**Comment by aryasoni98** [comment]
/assign me 

I would like to work on it.

**Comment by seokho-son** [comment]
Hi @ronitblenz,
It seems like yunkon-kim is busy at the moment. :)

I would like to assign you to this task. Please proceed.
/assign @ronitblenz

Hi @aryasoni98,
Thank you! However, I believe we should assign a contributor in an orderly manner, considering that handling this issue is simple. Please find another issue to work on.

**Comment by ronitblenz** [comment]
@seokho-son On it!
