### ISSUE TITLE
[i18n] 'Search results' page fallbacks to English one

### ISSUE THREAD

**Issue by jihoon-seo** [cncf/glossary#2087]
For example, in https://glossary.cncf.io/es/ (Spanish page),
when I search for 'Kubernetes',
it goes to https://glossary.cncf.io/search/?q=kubernetes ,
not https://glossary.cncf.io/es/search/?q=kubernetes .

(And this phenomenon persists even if we add the file `content/es/search.md` ;
please try at https://deploy-preview-2086--cncfglossary.netlify.app/es/ , the preview of the PR #2086,
which adds `content/es/search.md`.
In precise, it fallbacks from https://deploy-preview-2086--cncfglossary.netlify.app/es/ to https://glossary.cncf.io/search/?q=kubernetes ,
not https://deploy-preview-2086--cncfglossary.netlify.app/es/search/?q=kubernetes or https://glossary.cncf.io/es/search/?q=kubernetes .)

Would it be possible to make the language selection persistent across page transitions between search result page and others?
@cjyabraham could you please take a look? Thank you!

**Comment by cjyabraham** [comment]
Hmm. This appears to be a bug in the docsy theme. [The example site](https://example.docsy.dev/) behaves the same way. Looks like [this theme js file](https://github.com/google/docsy/blob/170cdd9cd31794eac802b0cec083097155feb81b/assets/js/search.js) is what needs fixing.

**Comment by cjyabraham** [comment]
@thetwopct assigning you since it's some weird context issue within the js file. I can think of a few workarounds but not sure if they're too hacky. One idea is to just include the js function inline in the footer so we can grab the correct context and search url, but maybe there is a more elegant solution.

**Comment by chalin** [comment]
Upstreamed the issue:

- https://github.com/google/docsy/issues/1558

**Comment by cjyabraham** [comment]
This is fixed in the new PageFind search
