### ISSUE TITLE
[New term] `Message Queues`

### ISSUE THREAD

**Issue by ronitblenz** [cncf/glossary#2099]
#### What this term is about? (briefly)
- Message queues are a key component of many cloud-native architectures. They provide a method of communication and coordination between distributed and decoupled microservices, which are a common pattern in cloud-native applications.

- A message queue works by receiving, storing, and delivering messages. If a service (producer) has data to send to another service (consumer), it can put a message on the queue. The consumer can then retrieve the message from the queue when it's ready to process it. This allows the producer and consumer to work at their own pace and not need to be directly connected to each other.

- Popular message queue systems used in cloud-native architectures include RabbitMQ, Apache Kafka, Amazon SQS (Simple Queue Service), Google Cloud Pub/Sub, and Azure Service Bus. These services provide robust, scalable, and distributed message queuing capabilities, making them well-suited to cloud-native applications.

#### Why this term needs to be added? (briefly) 
- Decoupling: Message queues decouple the sender and receiver, allowing them to operate independently. This is particularly important in a microservices architecture, where each service should be able to evolve independently.

- Resilience: If a service goes down, messages destined for it can be stored in the queue until the service is back up, preventing data loss.

- Load Balancing: If there are multiple instances of a service, a message queue can distribute messages between them to balance the load.

- Asynchronous Processing: Message queues allow for asynchronous processing, which can improve performance and responsiveness, especially for tasks that are time-consuming or need to be scheduled for later processing.

- Scalability: Message queues can help to manage and control the flow of data, which can be particularly important in a cloud-native environment where services can be rapidly scaled up or down based on demand.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)". (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by ronitblenz** [comment]
If accepted, I would love to add this term to the glossary

**Comment by iamNoah1** [comment]
@ronitblenz thanks for taking the time to suggest this term. However, the maintainers decided to not accept this term for the glossary. The main reason being that we already have the term about event driven architecture which we see as the concept that drive message queues. That is why we don't see any additional value in having the additional term talking about message queues.

**Comment by ronitblenz** [comment]
@iamNoah1 Thanks for the confirmation!
