### ISSUE TITLE
Portability Definition Not Started

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#21]
Need someone to fill in a definition for Portability. You can find it [here](https://github.com/cncf/glossary/blob/main/definitions/portability.yaml)

**Comment by JasonMorgan** [comment]
Wrong link above, find the definition [here](https://github.com/cncf/glossary/blob/main/definitions/portability.md)

**Comment by Vivek-Hotti** [comment]
Please see PR #66 .
