### ISSUE TITLE
[ja] Localize cloud native security for Japanese

### ISSUE THREAD

**Issue by naonishijima** [cncf/glossary#2112]
- Localize cloud native security for Japanese
- https://glossary.cncf.io/cloud-native-security/

**Comment by aryasoni98** [comment]
@naonishijima I have to convert the link into Japanese right

**Comment by aryasoni98** [comment]
<img width="889" alt="Screenshot 2023-06-10 at 1 14 47 PM" src="https://github.com/cncf/glossary/assets/18515597/fa864fbf-58b3-468f-b0aa-1d7a4f36a853">

**Comment by aryasoni98** [comment]
@naonishijima when I fork the repository I didn’t see the ja folder on the `main` branch.

**Comment by naonishijima** [comment]
We need at least 10 terms in Japanese before go to main branch.
https://github.com/cncf/glossary/discussions/2111

**Comment by naonishijima** [comment]
> @naonishijima I have to convert the link into Japanese right

Yes!

**Comment by aryasoni98** [comment]
> #2111

so how can i contribute on it.
