### ISSUE TITLE
Initiate Turkish l10n team

### ISSUE THREAD

**Issue by aliok** [cncf/glossary#2123]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

For example, the two-letter code for Korean is `ko`.

 - Language name (ex: `Korean`): Turkish
 - Language two-letter code (ex: `ko`): tr

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

- [A] @aliok
- [A] @halil-bugol
- [A] @developer-guy
- [A] @eminalemdar
- @symys
- @boramir
- @mertsaygi
- @onurkcbyk
- @devenes
- @rwxdash
- @Dentrax
- @ihsanalgul

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-ko`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by aliok** [comment]
NOTE: the volunteer list is not complete yet

**Comment by seokho-son** [comment]
Thanks @aliok :)
- created `#glossary-localization-turkish` channel in the CNCF slack !
- created https://github.com/cncf/glossary/labels/lang%2Ftr label.

**Comment by seokho-son** [comment]
Hi @aliok :)
We're currently working on the following tasks:

 - we will update `CODEOWNERS` (via #2134)
 - after the `CODEOWNERS` updated, I will create dev-tr. (if updating `CODEOWNERS` is delayed, I will create `dev-tr` first)

In the meantime, could you please leave comment here to confirm that each approver candidate (@aliok, @halil-bugol, @developer-guy, @eminalemdar) understands the policy and information for localization approvers?

- #723

**Comment by aliok** [comment]
@seokho-son I confirm!

**Comment by halil-bugol** [comment]
I confirm

**Comment by eminalemdar** [comment]
I confirm!

**Comment by seokho-son** [comment]
Hi folks ! :) 

- Created development branch for Turkish!: https://github.com/cncf/glossary/tree/dev-tr
- Added the approvers ! 
  - Please let @developer-guy check the above comment. :)

You can go to the next step. :)

**Comment by aliok** [comment]
@seokho-son I think we can resolve this ticket now. Or anything you would expect from us before doing so?

**Comment by seokho-son** [comment]
I typically close this type of issue after the initial site configuration has been merged. 
But, why not, we can close this issue now. ;)
