### ISSUE TITLE
[ja] Localize Scalability for Japanese

### ISSUE THREAD

**Issue by naonishijima** [cncf/glossary#2136]
- Localize Scalability for Japanese
- https://glossary.cncf.io/scalability/

**Comment by nikhilchauhangithub** [comment]
I would like work on this task, Kindly assign it to me, Thanks

**Comment by naonishijima** [comment]
Please take charge of one PR at a time.

**Comment by Ayaan49** [comment]
Hey, may I work on this?

**Comment by naonishijima** [comment]
Hi @Ayaan49 ,
Thank you for your interest on Japanese localization jobs, but this job needs a native Japanese speaker skill likes 「てにおは」「ですます」 and dsiscuss in Japanese with approvers.
https://github.com/cncf/glossary/pull/2140#issuecomment-1610418343 helps you.

**Comment by shizhenhu** [comment]
Hi @naonishijima 
I'm interested in working on this task, could you please assign it to me? Thank you.
