### ISSUE TITLE
[ja] Localize Tightly Coupled Architectures for Japanese

### ISSUE THREAD

**Issue by naonishijima** [cncf/glossary#2137]
- Localize Tightly Coupled Architectures for Japanese
- https://glossary.cncf.io/tightly-coupled-architectures/

**Comment by nikhilchauhangithub** [comment]
I would like work on this task, Kindly assign it to me, Thanks

**Comment by nikhilchauhangithub** [comment]
Thank you, I create a pr but got some kind of problem, it is my first pr so
kindly help me out

**Comment by bashi8128** [comment]
I'm working on this one.
Please assign me.
