### ISSUE TITLE
[Update term] `Nodes` for `En`

### ISSUE THREAD

**Issue by guillaumebernard84** [cncf/glossary#2148]
#### Why this term needs to be updated? (briefly)
- In the 'problem it addresses' paragraph, I think we should talk about microservices running on nodes, instead of processes. The term process isn't in the glossary, and doesn't appear in the `distributed apps` nor in the `Cloud native technology` definitions. If you agree with this change, I can submit a PR.

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [X] I want to work on this suggestion and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)".. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by CathPag** [comment]
Hi @guillaumebernard84, this is the feedback from @seokho-son, one of the Glossary maintainers. 

Why this term needs to be updated? (briefly)

> In the 'problem it addresses' paragraph, I think we should talk about microservices running on nodes, instead of processes. The term process isn't in the glossary, and doesn't appear in the distributed apps nor in the Cloud native technology definitions. If you agree with this change, I can submit a PR.

I disagree with the contributor's suggestion.
According to current definition of Node in the Glossary, a node is a computer that works in concert with other computers, or nodes, to accomplish a common task.

I think we don't have to limit capability of a Node into running microservices only. (a Node is basically a computation unit. The term can be used to name a computational unit-member in a cluster or a disctributed system)
Also, even though we don't have process definition in the Glossary, readers may understand what is process mentioned in the Problem it addresses section from its context.

I prefer a minor modification.

Current:
- To address this, developers started creating [distributed applications](https://glossary.cncf.io/distributed-apps/) where each process runs on its own node.
Possible enhancement for consistancy:
- To address this, developers started creating [distributed applications](https://glossary.cncf.io/distributed-apps/) where each application or process runs on its own node.

**Comment by guillaumebernard84** [comment]
Hello
Ok, I understand. 
Tell me if you want me to open a PR with the minor modification, or if you prefer to leave it as is and close the issue.

**Comment by seokho-son** [comment]
Hi @guillaumebernard84 
In the case of minor modifications (such as fixing a typo, aligning words, fixing a link, etc.), there is no need to open an issue. :)
You can directly make a suggestion through a PR (Pull Request). (However, please be aware that contributions can be duplicated among contributors.)
I believe we don't need to close this issue. Let's close it when your upcoming PR has been merged! :)

**Comment by CathPag** [comment]
@seokho-son, I believe @guillaumebernard84's question was whether he should proceed with your suggested change based on your comment I posed above.

**Comment by seokho-son** [comment]
Hi @guillaumebernard84 

My suggestion for the minor modification is about consistency as follows. You may check the definition and include additional suggestions in your PR. (if the suggestions are minor, you can suggest it from the PR)

```diff
-To address this, developers started creating [distributed applications](https://glossary.cncf.io/distributed-apps/) where each process runs on its own node.

+To address this, developers started creating [distributed applications](https://glossary.cncf.io/distributed-apps/) where each application or process runs on its own node.
```

Let me close this issue. (you don't have to reference this issue for your upcoming PR) 
:)
