### ISSUE TITLE
Add Working groupd details

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#215]
This effort is now part of a CNCF working group. We need to update the readme to reflect that.

**Comment by sandeeplenka** [comment]
Hey I would like to work on this can you Guide me

**Comment by ShivamTyagi12345** [comment]
Hey, @JasonMorgan.May I help with this?

**Comment by CathPag** [comment]
Apologies for the late response @ShivamTyagi12345. Yes, please! We'd love for you to help!

**Comment by manavsiddharthgupta** [comment]
hey its not assigned , can you please assign me and explain the task cause i'm a begineer.

**Comment by imoisharma** [comment]
> This effort is now part of a CNCF working group. We need to update the readme to reflect that.

where this file exit?
