### ISSUE TITLE
[Update term] `DevSecOps` for `En`

### ISSUE THREAD

**Issue by tico88612** [cncf/glossary#2167]
#### Why this term needs to be updated? (briefly)
- In the `Problem it addresses` section, the term `continuous deployment` currently links to the `continuous delivery` page. I believe this need to be corrected.
- Perhaps we need to incorporate both `continuous deployment` and `continuous delivery` into the description.

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [X] I want to work on this suggestion and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)".. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by Nitishupkr** [comment]
triage/accepted

**Comment by Nitishupkr** [comment]
I want to work on this issue

**Comment by CathPag** [comment]
> triage/accepted

@Nitishupkr, only maintainers can accept or decline terms. Also, as you can see @tico88612 would like to work on this.

@tico88612, sorry, just seeing this. Let me get back to you shortly.

**Comment by nate-double-u** [comment]
Hi @tico88612, thanks for this. I've accepted triage, so feel free to open a PR with your suggested changes.
