### ISSUE TITLE
[hi] Localize i18n strings in `hi.toml`

### ISSUE THREAD

**Issue by panchal20bhavin** [cncf/glossary#2182]
#### Why this term needs to be updated? (briefly) 
- 
There are some string in hi.toml(**Hindi**) which are not translated in Hindi language.

#### Why this term needs to be updated? (briefly) 
-
As you see that some string are still not translate, User might be seen English string, so I propose to update all String in Hindi language.
 

![Screenshot (291)](https://github.com/cncf/glossary/assets/65060686/454a4aa9-39f4-44c6-8396-3d663c2e1d78)

**Comment by aryasoni98** [comment]
I would like to work on it

**Comment by 7h3-3mp7y-m4n** [comment]
@aryasoni98 can you give this opportunity to me to contribute
