### ISSUE TITLE
[Spanish] Localize `Virtualization` 

### ISSUE THREAD

**Issue by franciscorodriguezsv24** [cncf/glossary#2185]
Localize `content/en/virtualization.md` in Spanish

**Comment by franciscorodriguezsv24** [comment]
Hola comunidad, me gustaría  traducir este segmento del glosario al español.

**Comment by ramrodo** [comment]
¡Hola @franciscorodriguezsv24! Muchas gracias por el interés y ayuda pero éste concepto ya fue traducido en [éste PR](https://github.com/cncf/glossary/pull/2070).

Pero dejame crear un nuevo issue para que puedas aportar en otro concepto :)
