### ISSUE TITLE
[es] Localize `Role-Based Access Control (RBAC)`

### ISSUE THREAD

**Issue by ramrodo** [cncf/glossary#2186]
Localize the content/en/role-based-access-control.md document to Spanish

**Comment by ramrodo** [comment]
@franciscorodriguezsv24 puedes trabajar en éste otro término :)

**Comment by franciscorodriguezsv24** [comment]
perfecto, muchas gracias !!

**Comment by electrocucaracha** [comment]
@franciscorodriguezsv24 algun avance al respecto?

**Comment by franciscorodriguezsv24** [comment]
Hola, si, solo que aun no lo he podido subir pero espero subirlo estos dias

**Comment by ramrodo** [comment]
@franciscorodriguezsv24 hola! Tendrás un avance que puedas subir a un PR?

**Comment by franciscorodriguezsv24** [comment]
Hola  este seria el nuevo PR #2346

**Comment by ramrodo** [comment]
Cerrando este PR en favor de https://github.com/cncf/glossary/pull/2346

**Comment by ramrodo** [comment]
closed by https://github.com/cncf/glossary/pull/2364
