### ISSUE TITLE
Stateless Apps Definition Not Started

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#22]
Need someone to fill in a definition for stateless apps. You can find it [here](https://github.com/cncf/glossary/blob/main/definitions/stateless_apps.yaml)

**Comment by Vivek-Hotti** [comment]
Please see PR #65

**Comment by xmulligan** [comment]
I think this issue can be closed now since #65 is merged

**Comment by JasonMorgan** [comment]
Thanks!
