### ISSUE TITLE
Initiate Russian l10n team

### ISSUE THREAD

**Issue by shurup** [cncf/glossary#2220]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

 - Language name: `Russian`
 - Language two-letter code: `ru`

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

- [A] @shurup
- [A] @kirkonru
- @tym83

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-ko`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by seokho-son** [comment]
Hi @shurup 
Could you invite more contributors for Runssian l10n? (especially, additional contributor who can approve localized content)
I think 3~4 approvers are good number as starting members. 
It is because if one of approvers open a PR, the PR can not be merged naturally since the development branch has merge protection(condition). (Author of PR cannot approve the PR. At least two approving reviews)

**Comment by seokho-son** [comment]
- Your label: https://github.com/cncf/glossary/labels/lang%2Fru
- Your dev branch: [dev-ru](https://github.com/cncf/glossary/tree/dev-ru)
:)

**Comment by shurup** [comment]
Hi @seokho-son! Thank you!

Regarding your question: thank you for this important point. Do you think adding @tym83 to our approvers' list will do the trick now (as a fast solution)? We'll be happy to wait for more people to join, but it might take a while.

**Comment by seokho-son** [comment]
Hi @shurup 
We need approvers who understand and capable of managing branches. I just added two suggested approver candidates.
In the meantime, I will help merging PRs for Russian localization if needed. Please call me in the comment if additional approval is needed. :)

**Comment by shurup** [comment]
Hi @seokho-son! Sounds excellent; thanks a lot!

**Comment by shurup** [comment]
@seokho-son while our initial PR is ready (#2468), we also want to make an announcement in the CNCF blog. We have almost finished its content (in Google Docs). How should we proceed with it?

**Comment by seokho-son** [comment]
@shurup I guess we can close this issue since there are enough members are working on. :)
