### ISSUE TITLE
Change "What it is" heading in definition template

### ISSUE THREAD

**Issue by nate-double-u** [cncf/glossary#2242]
The heading "What it is" would be more grammatically correct as: "What is it?"

This update would involve changing [the template in the Style Guide](https://glossary.cncf.io/style-guide/#definition-template) and updating all the en language terms that have been added so far.
```[tasklist]
### Tasks
```

**Comment by rolfedh** [comment]
- + 1. I like the proposed changes. Generally, titles that ask a question spur readers' curiosity, engagement, and retention. 
- Although we _could_ express some of the other section titles as questions, but I prefer not to. Variation is also important for retaining interest.

**Comment by iamNoah1** [comment]
after long discussion about this topic among the maintainers, the consensus is to remove the what it is header. see #2575
