### ISSUE TITLE
Localize code-of-conduct.md for `Hindi`

### ISSUE THREAD

**Issue by kumarankit999** [cncf/glossary#2247]
#### Why this term needs to be updated? (briefly) 
- Localize Code of Conduct for Traditional Hindi because it is available in various languages excluding Hindi.
-https://github.com/cncf/foundation/blob/main/code-of-conduct.md

**Comment by kumarankit999** [comment]
Can you assign me @jihoon-seo ,So that I will work on this

**Comment by jihoon-seo** [comment]
That file is in https://github.com/cncf/foundation, not in this repo.
You may start with opening an issue in https://github.com/cncf/foundation .

**Comment by kumarankit999** [comment]
I have opened this issue in CNCF Foundation @jihoon-seo
