### ISSUE TITLE
"Propose new terms" section of the "How to Contribute" guide shouldn't be localized

### ISSUE THREAD

**Issue by aliok** [cncf/glossary#2249]
Part of the new language package, it is required to localize the The "How to Contribute" guide at  https://glossary.cncf.io/contribute/ .

There's a "[Propose new terms"](https://glossary.cncf.io/contribute/#propose-new-terms) section in that guide, which I saw localized into other languages, but as is (I checked German and Italian).

My logic is this:

1. Proposing a new term is only possible with "English" as the entry point
![Screenshot 2023-07-26 at 00 21 55](https://github.com/cncf/glossary/assets/376732/8493426e-f0d5-4095-8fb2-43c764d1fe5a)

2. If the person who wants to propose a new term knows English, they can go and check the same section in the English guide and learn how to propose a new term.
3. If they don't know English, they cannot propose a new term anyway.

Am I missing a point or a case?

Instead, I think this section should be basically clearly saying:
- English is the entry language for new terms
- Here's the procedure on how to do that (link to "[Propose new terms"](https://glossary.cncf.io/contribute/#propose-new-terms))

I have been working on localizing this guide to Turkish and I found it a bit weird that I am writing text that explains how to create a new English term in Turkish :)

**Comment by aliok** [comment]
cc @CathPag @seokho-son

**Comment by aliok** [comment]
cc @jihoon-seo

**Comment by seokho-son** [comment]
Thank you, @aliok. First and foremost, I appreciate your efforts in considering and identifying this issue!

The Korean localization team (and perhaps other language teams as well) has previously deliberated on this matter.

The Korean localization team has considered the logic behind points 2 and 3, and we have subsequently localized "[Propose new terms"](https://glossary.cncf.io/contribute/#propose-new-terms) section in the contribution guide. The rationale for our decision is as follows:

> "1. Proposing a new term is only possible with "English" as the entry point"

--> Yes (as is) 


> "2. If the person who wants to propose a new term knows English, they can go and check the same section in the English guide and learn how to propose a new term."

--> Even for Koreans who can use English (not necessarily at a native level, but competent enough to suggest new terms in English), having the guide in Korean makes it relatively easier and quicker for them to understand the process.


> "3. If they don't know English, they cannot propose a new term anyway."

--> Even for Koreans who aren't proficient in English, while they might not propose new terms themselves, having the guide in Korean can make them easily aware of the procedure (our efforts to make it official and community-driven) we have in the Glossary project for suggesting new terms.

Is this rationale acceptable to your team ? :)

**Comment by aliok** [comment]
Thanks for the feedback @seokho-son 

I think we can accept that :)

/close
