### ISSUE TITLE
Update links to website 

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#226]
We need to update all links in the definitions so they link to the new website. The website is not live yet but will be very soon.

**Comment by reddymahendra52** [comment]
Can I take up this issue?

**Comment by CathPag** [comment]
It's all yours :) I'll let you know when the website is live

**Comment by reddymahendra52** [comment]
@CathPag 
I can see that the website is live. And most of the links on the site are linked properly. Should I go over the definitions once and see if any links are to be added ?

Or do I need to do something else?

**Comment by CathPag** [comment]
I think the person who created the website did that too. Sorry, I didn't know. But I'll let you know next time we have a similar task. Your links were super helpful!!

**Comment by reddymahendra52** [comment]
Sure..!!
Thanks
