### ISSUE TITLE
[es] Create a workflow to add new issues to GitHub Projects automatically

### ISSUE THREAD

**Issue by ramrodo** [cncf/glossary#2267]
We would like to have a process/workflow that every time we create new issues, these can be added to the GitHub project: https://github.com/cncf/glossary/projects/5.

Reference:
https://github.com/actions/add-to-project/tree/main

**Comment by ramrodo** [comment]
@jossemarGT could you write a comment here to assign this issue to you, please? Thanks :)

**Comment by jossemarGT** [comment]
Oh my! I didn't see that comment! Could I be assigned to this ticket?

**Comment by electrocucaracha** [comment]
Given that most of the work has been done, this effort will be postponed for future improvement
