### ISSUE TITLE
[tw] Localize `Kubernetes` for Traditional Chinese

### ISSUE THREAD

**Issue by johnlinp** [cncf/glossary#2297]
1. Localize `Kubernetes` for Traditional Chinese
2. https://glossary.cncf.io/kubernetes/

**Comment by ranjan2829** [comment]
done with the pr #2299

**Comment by hwchiu** [comment]
@ranjan2829 

你的 PR 整個從系統上就是流程錯誤，首先繁體中文化翻譯有自己的 branch 要處理，不是直接推到 main，更不是直接修改英文語系的內容，你這樣會導致整個英文版本的內容都錯誤，請先上 Slack 瞭解每個語系的翻譯流程

再者你的翻譯內容非常的機器化，整個語句與語法都不是繁體中文用法，翻譯不應該是單純的機器翻譯，而是要該母語人士去消化理解並且轉換為該語言的慣用語句

@johnlinp  
再麻煩你繼續開 PR 走正式流程與母語人士的翻譯，感謝
