### ISSUE TITLE
Proposed to add 2 new members to dev-tw

### ISSUE THREAD

**Issue by pichuang** [cncf/glossary#2321]
Based on the past dev-tw merge records and the activity level of the Issue, as current members, I would like to submit @hwchiu and @johnlinp to be part of the zh-tw branch and hope to encourage everyone to keep contributing.

**Comment by ydFu** [comment]
This nomination process has been discussed in [#glossary-localization-traditional-chinese Slack](https://cloud-native.slack.com/archives/C055KERTNCX/p1692513600644879) and the interest of all parties has been confirmed.

Welcome to @hwchiu and @johnlinp join the `dev-tw` team.

**Comment by seokho-son** [comment]
will be handled by #2343
