### ISSUE TITLE
[es] Translate - `devsecops` into Spanish

### ISSUE THREAD

**Issue by krol3** [cncf/glossary#2333]
**This is a Feature Request**
Translate this page [devsecops](https://glossary.cncf.io/devsecops) into Spanish.

**What would you like to be added**
The translation will be added to `content/es/`devsecops

**Why is this needed**
There is no Spanish translation for this file. It would be great if we could read this in Spanish.

**Comments**
The Spanish translation team would like to facilitate your contribution's journey,  any doubt participate in the weekly meetings in the kubernetes slack channel `kubernetes-docs-es`

We also encourage new contributors to participate in their native speaking language 💥.

**Comment by mhamzanadeem** [comment]
I have setup the environment .  I started working on this issue .  But I found that  " content/es "  have already the file                      
" devsecops.md  "  which is already translated in Spanish.

**Comment by ramrodo** [comment]
Closing this issue since that term [is already localised](https://github.com/cncf/glossary/blob/main/content/es/devsecops.md).
