### ISSUE TITLE
[pt] Localize distributed systems

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#2380]
Localize https://glossary.cncf.io/distributed-systems/.

**Comment by rafaelmnatali** [comment]
@edsoncelio I believe this was already resolved in the PR https://github.com/cncf/glossary/pull/2340

could you double check, please?

**Comment by edsoncelio** [comment]
> @edsoncelio I believe this was already resolved in the PR #2340
> 
> could you double check, please?

Thanks! You're right!
