### ISSUE TITLE
Proposal for new terms

### ISSUE THREAD

**Issue by iamNoah1** [cncf/glossary#240]
I would like to propose adding the following terms: 

* Agile/Agile Software Development -> check
* CaaS, PaaS, IaaS, SaaS, FaaS -> Only CaaS missing
* Serverless -> already present
* Docker -> apparently not needed 
* Site Reliability Engineering

**Comment by sandipanpanda** [comment]
Definitions of Serverless, SaaS, FaaS, IaaS are already available.

**Comment by JasonMorgan** [comment]
@iamNoah1 sorry about the slow response! I believe that with the new glossary.cncf.io site we're deprecating the pdf. Regardless, we'd love to see some PRs and issues for the terms you listed with the possible exception of docker as I'm not sure it requires a definition.

**Comment by iamNoah1** [comment]
@JasonMorgan no worries. Thanks for the feedback, I will open PR(s) to add the terms that are not already existing :)

**Comment by CathPag** [comment]
Hi @iamNoah1, wanna work on any of the other terms you suggested that haven't been addressed yet? Also, if you could create one issue per term, that'd be great. Thank you! Catherine

**Comment by iamNoah1** [comment]
Hei @CathPag, yes I will. I think only SRE is not addressed yet. Will create an issue for it :) and close this one.

**Comment by iamNoah1** [comment]
obsolete through #261 and #262
