### ISSUE TITLE
[New term] `DevRel`

### ISSUE THREAD

**Issue by Madhurchandran** [cncf/glossary#2427]
#### What this term is about? (briefly)
- DevRel also known as Developer Relations or Developer Advocacy, is a role that exists in developer companies that target the developers' markets. DevRel helps to educate developers and get people into the community to contribute. There are multiple DevRel types exist that help to scale communities
#### Why this term needs to be added? (briefly) 
1. there should be page about DevRel engineer what they actually do.
2. they are developer, or community builder much to be know about this.
3.  I want this this term to be added like Devops in side drawer we can search with tag.
4. learn new about this role in community. 
- 

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [x] I want to work on this term and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)". (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by Madhurchandran** [comment]
@jihoon-seo DevRel is not available in glossary page

**Comment by nate-double-u** [comment]
Hi, thanks for this suggestion @Madhurchandran. The maintainers discussed this term and have decided not to accept it as it is not a cloud native specific term.
