### ISSUE TITLE
[Update term] `Continuous Delivery` for `En`

### ISSUE THREAD

**Issue by guillaumebernard84** [cncf/glossary#2433]
#### Why this term needs to be updated? (briefly)
- The last sentence of the [Continuous Delivery ](https://glossary.cncf.io/continuous-delivery/) term says:
"Typically, trunk-based development is used in CD strategies as opposed to feature branching or pull requests"
It is highly unlikely that the reader knows what "trunk-based development" is, as he is reading the glossary to learn more about Continuous Delivery. 
As this branching model is widely used in the cloud native space, I thought it would be a good idea to add this term to the glossary, but I saw that it was already proposed and rejected: https://github.com/cncf/glossary/issues/834 

So I think we should update this term, either:
- completly remove this sentence, as it's not necessary to understand what Continuous Delivery means, and it is confusing
- or add a link to https://en.wikipedia.org/wiki/Branching_(version_control) to allow the reader to dig deeper if needed. (or another website, there is no "trunk-based development" page on wikipedia)  

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [X] I want to work on this suggestion and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)".. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by iamNoah1** [comment]
@guillaumebernard84 the update has been accepted :) you can start working on it if you want :)

**Comment by professorabhay** [comment]
Hey @iamNoah1, Does it still need to be resolved?
I would like to work on this.

**Comment by iamNoah1** [comment]
@guillaumebernard84 friendly ping. Otherwise @professorabhay could give it a go.

**Comment by guillaumebernard84** [comment]
> @guillaumebernard84 friendly ping. Otherwise @professorabhay could give it a go.

Hello @iamNoah1, I completely forgot this issue! I'll assign myself and create a PR!
