### ISSUE TITLE
Stateless and Stateful Apps are not listed in sidebar

### ISSUE THREAD

**Issue by supirman** [cncf/glossary#244]
Stateless and Stateful Apps are searchable and accessible from the URL, but not listed in the sidebar.

![image](https://user-images.githubusercontent.com/329333/139573150-183ab81a-aff0-4990-ac11-d64d7731f77d.png)

**Comment by JasonMorgan** [comment]
Hey @supirman neither of those terms are completed yet. Only entries marked completed appear in the navigation bar.
