### ISSUE TITLE
[ja] Localize devsecops

### ISSUE THREAD

**Issue by naonishijima** [cncf/glossary#2448]
Localize https://glossary.cncf.io/devsecops/

**Comment by HANABE926** [comment]
HI, I would like to work on it .
can you assign me this issue?

**Comment by Okabe-Junya** [comment]
friendly ping @HANABE926 

I would like to know the progress of this issue. If it's a bit difficult to work on, we can support for you, or is it okay to un-assign it so that anyone else can work on this issue?

**Comment by Okabe-Junya** [comment]
Let me un-assign @HANABE926 so that someone else can work on this issue. When you work on again, feel free to re-assign :D

**Comment by katzchang** [comment]
着手しますのでアサインをお願いします @Okabe-Junya
