### ISSUE TITLE
[ja] Localize How To Contribute

### ISSUE THREAD

**Issue by naonishijima** [cncf/glossary#2449]
Localize https://glossary.cncf.io/contribute/

**Comment by aryasoni98** [comment]
I would like to work on it .

**Comment by naonishijima** [comment]
Hi @aryasoni98,
Thank you for your interest on Japanese localization task, but this task needs a native Japanese speaker skills like 「てにおは」「ですます」 and discuss in Japanese with approvers. Is this alright with you? 
https://github.com/cncf/glossary/pull/2140#issuecomment-1610418343 helps you.

**Comment by kaitoii11** [comment]
Closing as it is already localized in https://github.com/cncf/glossary/pull/2088
