### ISSUE TITLE
[ja] Localize API Gateway

### ISSUE THREAD

**Issue by naonishijima** [cncf/glossary#2450]
Localize https://glossary.cncf.io/api-gateway/

**Comment by aryasoni98** [comment]
I would like to work on it

**Comment by naonishijima** [comment]
Hi @aryasoni98,
Thank you for your interest on Japanese localization task, but this task needs a native Japanese speaker skills like 「てにおは」「ですます」 and discuss in Japanese with approvers. Is this alright with you? 
https://github.com/cncf/glossary/pull/2140#issuecomment-1610418343 helps you.

**Comment by Okabe-Junya** [comment]
I would like to work on this issue!!

**Comment by Okabe-Junya** [comment]
@naonishijima cc: @kaitoii11 

用語 `API Gateway` は翻訳せずに、そのまま表記した方が良いですか？あるいは `APIゲートウェイ` と表記する方が良いですか？

**Comment by naonishijima** [comment]
文の中では"API gateway"とgatewayが小文字になっているので固有名詞ではないと思います。なのでAPIゲートウェイがいいかと思います。
