### ISSUE TITLE
[Update term] `Service mesh` for `it`

### ISSUE THREAD

**Issue by shurup** [cncf/glossary#2472]
#### Why this term needs to be updated? (briefly) 

While browsing through the Italian localisation directory, I noticed that its [service-mesh.md](https://github.com/cncf/glossary/blob/main/content/it/service-mesh.md) is wrong. Instead of actually describing service mesh, it duplicates the contents of [distributed-apps.md](https://github.com/cncf/glossary/blob/main/content/it/distributed-apps.md). It seems that this confusion happened during  #1115, so I think it's reasonable to reach @ugho16 here.

**Comment by ugho16** [comment]
Hi @shurup, thank you for your help. This issue has been already resolved: if you take a look at the ’dev-it’ branch the file is correct.

We will soon open a PR to merge all the changes in ’main’, so this will be fixed soon.

Thanks again!
