### ISSUE TITLE
[hi] Localize API for Hindi 

### ISSUE THREAD

**Issue by kumarankit999** [cncf/glossary#2502]
Localize Application Programming Interface in Hindi Localization.

Source https://glossary.cncf.io/application-programming-interface/

**Comment by ARYANis0001** [comment]
Please assign this issue to me 
I have already raised the PR

**Comment by kumarankit999** [comment]
Hey @ARYANis0001, This issue isn't assigned to anyone, wait.....

**Comment by RupeshHacker** [comment]
I have made some changes please have look
![Screenshot (33)](https://github.com/cncf/glossary/assets/58428810/d9326d9e-c848-4172-a3df-d23ec3111f1f)

**Comment by ARYANis0001** [comment]
@kumarankit999 Please check my PR is there any need of improvement

**Comment by kumarankit999** [comment]
Is there any working on this issue?

**Comment by aryasoni98** [comment]
@kumarankit999 I would like to work on this issue .

**Comment by RupeshHacker** [comment]
@kumarankit999 https://github.com/cncf/glossary/issues/2502#issuecomment-1792038616 please check

**Comment by Aryan-Singla** [comment]
@kumarankit999 Close this issue as it is a duplicate of #1624 and PR for #1624 is already merged

**Comment by kumarankit999** [comment]
Thanks for letting me Know!!
