### ISSUE TITLE
[tw] Localize `Idempotence` for Traditional Chinese

### ISSUE THREAD

**Issue by mattwang44** [cncf/glossary#2511]
source: https://glossary.cncf.io/idempotence/

**Comment by ydFu** [comment]
Note: you can start working on an issue after the maintainers assigned it to you. You can only claim one term at a time. Workig on multiple terms is sequential, you must complete a term before claiming the next one.

Ref: https://glossary.cncf.io/contribute/#work-on-an-existing-issue

**Comment by mattwang44** [comment]
thx for the reminder! I won't open any new PR until the current ones are resolved.

**Comment by ydFu** [comment]
Get Merged,thank @mattwang44
