### ISSUE TITLE
mTLS definition

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#252]
We should have a definition for mTLS. What it is and what it does.

**Comment by ShivankPro** [comment]
Hey,
Can you provide more info about this issue,
and where it's located.
Mutual Transport Layer Security (mTLS)

**Comment by CathPag** [comment]
Hi @ShivankPro, we need a new definition for mTLS that follows the [style guide](https://glossary.cncf.io/style-guide/).  You'd be creating a new file — we don't have anything on mTLS yet. Does that make sense?

**Comment by ShivankPro** [comment]
Hi @CathPag , I am just trying to start with some Beginner-friendly issues, 
Therefore trying to know, How should I get started.

**Comment by CathPag** [comment]
[Does this help](https://glossary.cncf.io/contribute/)?

**Comment by Alt-Shivam** [comment]
Yes, it is,
Thanks a lot!

**Comment by JasonMorgan** [comment]
Hey @Alt-Shivam I set you as the assignee, please reach out to me on slack if you need any help. Here's a definition we have for it in the linkerd docs: https://linkerd.io/service-mesh-glossary/#mtls

Thanks!

**Comment by Alt-Shivam** [comment]
Yeah, Sure
