### ISSUE TITLE
[IT]: Basic structure for Italian l10n

### ISSUE THREAD

**Issue by annalisag-spark** [cncf/glossary#256]
### Details (optional)

Just init

**Comment by Giulia-dipietro** [comment]
Hi @annalisag-spark I'd like to contribute to the Italian l10n of the glossary.

**Comment by annalisag-spark** [comment]
Ciao! Nice to meet you and welcome!
Join the Italian team on #glossary-localization-italian CNCF channel, so that we can synch :)

**Comment by seokho-son** [comment]
complete by #404
