### ISSUE TITLE
Remove the What it is Header completely

### ISSUE THREAD

**Issue by iamNoah1** [cncf/glossary#2575]
Remove the what it is header from templates and all terms.

**Comment by nate-double-u** [comment]
Also related: https://github.com/cncf/glossary/pull/2243

**Comment by FII78** [comment]
Hello, This would be my first contribution, can you assign it to me please?

**Comment by jihoon-seo** [comment]
@FII78 you has been assigned, please proceed.

**Comment by rohan-kapse** [comment]
hey @FII78 is the issue fixed or still persists? If not i would be happy to make the changes.

**Comment by nate-double-u** [comment]
@iamNoah1, @jihoon-seo, @seokho-son, should this only be done for English and then let the localization teams open issues for their languages?

**Comment by jihoon-seo** [comment]
@nate-double-u for me, either way is fine. I will follow however decided. 😁

**Comment by nate-double-u** [comment]
Let's just do English first then.

**Comment by kumarankit999** [comment]
Who is working on this issue!!

**Comment by aliok** [comment]
Hey folks,

We (Turkish l10n team) are curious if you would like to go on with this change? If so, we'll do the same (w/o waiting for you)

**Comment by seokho-son** [comment]
Hi folks,
Let me unassign @FII78, and handle this issue quickly as possible as one of maintainers of this repo. 

@aliok please wait for changes to all English docs in main branch first. after that, Turkish l10n team would better to rebase the dev branch. (in fact, all localization teams should be notified and work similarly)
