### ISSUE TITLE
[hi] Localize Transport Layer Security for Hindi

### ISSUE THREAD

**Issue by kumarankit999** [cncf/glossary#2579]
I would like to work on this!

**Comment by I-MirzaBaig** [comment]
Can you assign this issue?

**Comment by kumarankit999** [comment]
Do you work on this issue @I-MirzaBaig!

**Comment by I-MirzaBaig** [comment]
@kumarankit999 I would like to give it a try😁! And resolve it .....

**Comment by ARYANis0001** [comment]
I want to work on this issue

**Comment by kumarankit999** [comment]
Hey @ARYANis0001, I am assigning @I-MirzaBaig because he has come first on this issue, you Can still contribute on the issue or can both collaborate on this issue

**Comment by ARYANis0001** [comment]
But I raised the PR first

**Comment by kumarankit999** [comment]
Hey @I-MirzaBaig, Can you try/reslove this!

**Comment by ARYANis0001** [comment]
Before my PR you did not mention that you had assigned to him

**Comment by I-MirzaBaig** [comment]
@ARYANis0001 Alright then, assign this issue to yourself and solve it..

**Comment by ARYANis0001** [comment]
@kumarankit999 Please check the PR is there any need of improvement
