### ISSUE TITLE
[tw] Localize `Infrastructure as Code` for Traditional Chinese

### ISSUE THREAD

**Issue by chienfuchen32** [cncf/glossary#2583]
#### Why this term needs to be updated? (briefly) 
Localize IaC for Traditional Chinese
https://glossary.cncf.io/infrastructure-as-code/

**Comment by chienfuchen32** [comment]
@ydFu, sorry, I might get the wrong label issue. is there any way to transfer to `lang/tw`? thank you.

**Comment by ydFu** [comment]
> @ydFu, sorry, I might get the wrong label issue. is there any way to transfer to `lang/tw`? thank you. 

Done, thank @chienfuchen32

**Comment by ydFu** [comment]
@chienfuchen32 
Please be careful when nominating tasks next time if you repeat them with others. Thank you.

**Comment by chienfuchen32** [comment]
@ydFu I see, I'll follow the task from slack channel next time. sorry for the inconvenience.

**Comment by ydFu** [comment]
Get Merged,thank @chienfuchen32
