### ISSUE TITLE
[New term] `GitHub`

### ISSUE THREAD

**Issue by vinayakjaas** [cncf/glossary#2592]
#### What this term is about? (briefly)
- GitHub is a web-based platform for version control and collaboration that allows developers to manage and share their code repositories. It is widely used for hosting open-source and private software projects, making it easier for teams to work together on code, track changes, and manage project development.
#### Why this term needs to be added? (briefly) 
- The term "GitHub" is relevant because it is a widely used platform for software development and collaboration, and understanding its purpose is important for those involved in software development, coding, and version control. It's a fundamental tool in the tech industry and provides a central hub for developers to work on and share their code, making it an essential concept in the field of software development and computer science.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)". (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by jihoon-seo** [comment]
@vinayakjaas Thank you for your suggestion, but the term 'GitHub' seems not appropriate to be added to the CNCF Glossary.
First, GitHub does not fit into the condition that a term should be related to cloud-native properties,
and second, GitHub is a well-known Git hosting service owned by Microsoft, and we are not likely to add vendor-specific terms.
Anyway, thank you again for your interest in this project!

**Comment by kumarankit999** [comment]
Hey @jihoon-seo, Should I close this issue!

**Comment by seokho-son** [comment]
I agree with @jihoon-seo 

Let me close this issue.
