### ISSUE TITLE
[ja] Localize Kubernetes

### ISSUE THREAD

**Issue by kaitoii11** [cncf/glossary#2596]
Localize https://glossary.cncf.io/kubernetes/

**Comment by aryasoni98** [comment]
I would like to work on it.

**Comment by aryasoni98** [comment]
@kaitoii11 Please assign the issue . I just raise the PR .

**Comment by Okabe-Junya** [comment]
Is anyone working on this issue? I can work on this issue

**Comment by kaitoii11** [comment]
@Okabe-Junya go ahead !
