### ISSUE TITLE
[ja] Localize Horizontal Scaling

### ISSUE THREAD

**Issue by kaitoii11** [cncf/glossary#2600]
Localize https://glossary.cncf.io/horizontal-scaling/

**Comment by shizhenhu** [comment]
Hi @kaitoii11 
Could you please assign it to me? Thank you.

**Comment by Okabe-Junya** [comment]
Go for it :)

**Comment by Okabe-Junya** [comment]
these docs are helpful when you contribute :)

- Localization rules (reviews will be based on this): https://kubernetes.io/ja/docs/contribute/localization/
- Style Guide: https://github.com/cncf/glossary/blob/dev-ja/content/ja/style-guide/_index.md
- Contribution Documentation: https://github.com/cncf/glossary/blob/dev-ja/content/ja/contribute/_index.md
