### ISSUE TITLE
[ja] Localize Vertical Scaling

### ISSUE THREAD

**Issue by kaitoii11** [cncf/glossary#2601]
Localize https://glossary.cncf.io/vertical-scaling/

**Comment by ARYANis0001** [comment]
Please assign this issue to me I have raised the PR

**Comment by kaitoii11** [comment]
Hi @ARYANis0001. Thanks for your interest.
Before moving on, I wanted to make sure that you are a Japanese native.

**Comment by shizhenhu** [comment]
Could you assign it to me? Thank you.
