### ISSUE TITLE
Add "Site Reliability Engineering"

### ISSUE THREAD

**Issue by iamNoah1** [cncf/glossary#261]

**Comment by Nawaz027** [comment]
Hey @iamNoah1, May I help with this issue?

**Comment by iamNoah1** [comment]
@Nawaz027 go for it. @CathPag could assign you probably.

**Comment by CathPag** [comment]
There you go :)

**Comment by Nawaz027** [comment]
thanks @CathPag @iamNoah1

**Comment by JasonMorgan** [comment]
@Nawaz027 you're now assigned to two terms. Would you mind letting me know which one you prefer to do first so I can mark the other as available?

**Comment by Nawaz027** [comment]
Hey @JasonMorgan ,  I am doing "site reliability engineering" first.
