### ISSUE TITLE
Add "CaaS"

### ISSUE THREAD

**Issue by iamNoah1** [cncf/glossary#262]

**Comment by sandipanpanda** [comment]
Hi @iamNoah1, can you please say if you are interested to add the definition of CaaS yourself, or is this issue is for asking help from a contributor?

**Comment by CathPag** [comment]
Hi @sandipanpanda, nice to see you here again :) I think @iamNoah1 wanted to work on it himself but I'll leave it up to him to respond.

**Comment by iamNoah1** [comment]
@sandipanpanda my primary intention was to raise awareness that the term should be added. I do not have to work on it necessarily, so if there is someone from the community who wants to work on it: go for it :) Otherwise I would probably pick it up.

**Comment by JasonMorgan** [comment]
@sandipanpanda it's all your if you want to take a crack at it.

**Comment by sandipanpanda** [comment]
Hi there, apologies for the late response. I was off GitHub for a month, so didn't know that this issue was assigned to me. Sending a PR to this issue ASAP.
