### ISSUE TITLE
Translate Existing Definitions to German 

### ISSUE THREAD

**Issue by iamNoah1** [cncf/glossary#263]
As a native german speaker I would volunteer to translate all of them :) 

Just assign me to the issue.

**Comment by CathPag** [comment]
@iamNoah1, please have a look at our new [localization doc](https://github.com/cncf/glossary/blob/main/LOCALIZATION.md) and, if possible, join our Glossary Working Group meeting on Thursday. You can find the meeting and add it to your calendar [here](https://www.cncf.io/calendar/).

We do require at least three volunteers per language. If it's only you, we can try to help recruit volunteers. In any case, let's discuss on Thursday.
