### ISSUE TITLE
[hi] Localize Tightly Coupled Architectures

### ISSUE THREAD

**Issue by Aarav238** [cncf/glossary#2640]
Page content - https://glossary.cncf.io/tightly-coupled-architectures/

`Tightly Coupled Architectures.md` is not available in hindi .

# Please describe why this term needs to be updated
- `Tightly Coupled Architectures.md` term available in English only but This term also needs to be Localized in Hindi.
- visit on page- https://glossary.cncf.io/tightly-coupled-architectures/

**Comment by abhay-raj19** [comment]
Okay @Aarav238 now you can proceed further.
