### ISSUE TITLE
add a new term GitOps

### ISSUE THREAD

**Issue by jgershater** [cncf/glossary#265]
### What it is
GitOps describes the desired state of the whole system using a declarative specification for each environment — the system of record. You may describe environments such as test, stage, and production in a code repository with the application version that resides in that environment.

### Problem it addresses
GitOps helps administrators and operators manage environments using declarative code vs scripts, notes, and other manual operations.

### How it helps
With GitOps operators have a complete history of how the environment was modified over time. Error recovery is simplified by issuing a git revert and the environment is restored.

**Comment by JasonMorgan** [comment]
@jgershater looks interesting, would you like to submit a PR for this?

**Comment by Alt-Shivam** [comment]
Hey, @jgershater 
In case, You are not interested in this issue,
I would like to work on it.
Thanks.

**Comment by hseligson1** [comment]
Hey @JasonMorgan - I just submitted a PR, attempting to give this definition a stab. Apologies I didn't link the PR to this issue - I wasn't sure if I was able to without assigning myself to it. 
PR: https://github.com/cncf/glossary/pull/302
