### ISSUE TITLE
[Hi] `Transport Layer Security (TLS)` for `hindi`

### ISSUE THREAD

**Issue by abhay-raj19** [cncf/glossary#2653]
#### Why this term needs to be updated? (briefly) 
-  Localisation of transport layer security will help native Hindi learners to use it for better understanding and getting all concepts clear.
- This change will also help in synchronizing it with other localized pages .

**Comment by professorabhay** [comment]
Hey @abhay-raj19!
Is it ready to resolve?
I would like to work on this.

**Comment by abhay-raj19** [comment]
I am firstly waiting for my assign so that i can work on it .

**Comment by aj11anuj** [comment]
Duplicate of #2579 issue, anyone who's interested in localizing this issue or want to get involved in it can heads up to original issue.
