### ISSUE TITLE
[Update term] `Ingress` for `En`

### ISSUE THREAD

**Issue by nate-double-u** [cncf/glossary#2663]
#### Why this term needs to be updated? (briefly)
- Follow up to https://github.com/cncf/glossary/pull/2397, “Ingress” doesn’t look like it’s showing up in the sidebar list of terms.
- Update frontmatter `status` to “Completed”
- Update frontmatter to remove empty `tags` entries

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [X] I want to work on this suggestion and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)".. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by professorabhay** [comment]
hey @nate-double-u! 
I would like to work on this.

**Comment by nate-double-u** [comment]
You're welcome to @professorabhay 🙂

**Comment by professorabhay** [comment]
Hey, @nate-double-u! I'm starting to work on it.
Kindly share some more details if possible.

**Comment by nate-double-u** [comment]
The frontmatter is this section:

```
---
title: Ingress
status: Feedback Appreciated
category: technology
tags: ["fundamental", "", ""]
---
```

**Comment by nate-double-u** [comment]
Related issue: https://github.com/cncf/glossary/issues/2679

**Comment by nate-double-u** [comment]
Hi @professorabhay, how are things going?
I'd like to get this update in soon, so if you're not able to do so by Monday Dec 11, may I reassign it?

**Comment by professorabhay** [comment]
Hey @nate-double-u, Kindly take a look to the PR.
