### ISSUE TITLE
[pt] Remove the "What it is" header

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#2667]
## Description
Based on [this](https://github.com/cncf/glossary/issues/2242) issue, remove the "What it is" header of all definition files.

**Comment by madfelps** [comment]
opa, tenho interesse em trabalhar nessa issue!

**Comment by edsoncelio** [comment]
> opa, tenho interesse em trabalhar nessa issue!

Opa, bem vindo @madfelps!
Vou deixar aqui um resumo do processo de contribuição (caso ainda não tenha feito): https://gist.github.com/edsoncelio/d7fdec7f24d5aba87e3e517c672e9eb5

Mais alguma dúvida entra lá no canal do time no slack da CNCF (se ainda não tiver por lá): `#glossary-localization-portuguese`

Vou atribuir a issue a você, e de novo: qualquer dúvida só falar :D
