### ISSUE TITLE
Changes need to be applied for the Glossary for Bare Metal Server

### ISSUE THREAD

**Issue by pushpjeetcholkar** [cncf/glossary#2681]
![changes](https://github.com/cncf/glossary/assets/20379769/6fd0cbe1-0d6c-442e-af84-0cefe4559647)

These are some of the changes I think should be implemented.

**Comment by kumarankit999** [comment]
Hey @pushpjeetcholkar, Thanks for Raising the Issue!
Can you refer to the page which we have to make changes!!

**Comment by pushpjeetcholkar** [comment]
Hi @kumarankit999 
Page link: https://glossary.cncf.io/bare-metal-machine/
Its Bare Metal Machine

**Comment by rohan-kapse** [comment]
@pushpjeetcholkar, @kumarankit999 Hi, if its fine can i help to solve it and work on it ?

**Comment by rohan-kapse** [comment]
#2707

**Comment by rohan-kapse** [comment]
![Screenshot 2023-12-15 125743](https://github.com/cncf/glossary/assets/112313349/3012cfc5-344a-49cd-88d2-c19c9412c988)
@pushpjeetcholkar Seems like the label is different. Plz look into this.
