### ISSUE TITLE
[hi] Localize Service Proxy for Hindi 

### ISSUE THREAD

**Issue by kumarankit999** [cncf/glossary#2686]
Localize Service Proxy Site for Hindi localization folks from https://glossary.cncf.io/service-proxy/

**Comment by aryasoni98** [comment]
@kumarankit999  I would like to work on it.

**Comment by kumarankit999** [comment]
Hey @aryasoni98, but @Aryan-Singla is already working on this!!

**Comment by Aryan-Singla** [comment]
Yes I have already raised the PR and am waiting for a review on this PR

**Comment by kumarankit999** [comment]
No worries! @Aryan-Singla
