### ISSUE TITLE
[ja] Localize Service Proxy for Japanese

### ISSUE THREAD

**Issue by Okabe-Junya** [cncf/glossary#2769]
Localize https://glossary.cncf.io/service-proxy/

**Comment by draunger** [comment]
assign me

**Comment by Okabe-Junya** [comment]
This repo does not have commands like those in the kubernetes org. (To be assigned, you need to ask someone with triage rights)

It seems that no one is currently working on this issue.  Go for it :)

**Comment by draunger** [comment]
@Okabe-Junya sir i want to convert this in Japanese language am I right

**Comment by Okabe-Junya** [comment]
Yes!! You are right. (I apologize for the lack of detail in the issue description) Before working on this issue, please check the following points.

Localization requires knowledge equivalent to a native Japanese speaker. (This corresponds to JLPT N1~N2 level)

ref. https://github.com/cncf/glossary/issues/2139#issuecomment-1655732923

> this job needs a native Japanese speaker skill likes てにおは and ですます and so on

Please refer to the following materials:

- Localization rules (reviews into Japanese will be based on this): https://kubernetes.io/ja/docs/contribute/localization/
- Style Guide: https://github.com/cncf/glossary/blob/dev-ja/content/ja/style-guide/_index.md
- Contribution Documentation: https://github.com/cncf/glossary/blob/dev-ja/content/ja/contribute/_index.md"

**Comment by draunger** [comment]
@Okabe-Junya sir i want to convert this in Japanese language am I right

**Comment by draunger** [comment]
@Okabe-Junya i have done my issue but i am unable to push my code what to do now sir??

**Comment by draunger** [comment]
@Okabe-Junya as I forked then I done changes with my local repo in vscode of my main default branch then I use git commit but after that on writing git push then it shows this 

remote: Permission to cncf/glossary.git denied to draunger.
fatal: unable to access 'https://github.com/cncf/glossary.git/': The requested URL returned error: 403

**Comment by Okabe-Junya** [comment]
Checking the error message, it appears that you are trying to push directly to `cncf/glossary`. Probably, this issue is due to the fact that during the git clone process, you used `git clone https://github.com/cncf/glossary` instead of `git clone https://github.com/<your-user-name>/glossary`

You can rectify this by either forking the correct repo again or by executing the following command:

```bash
$ git remote  -v
origin	https://github.com/Okabe-Junya/glossary (fetch)
origin	https://github.com/Okabe-Junya/glossary (push)
upstream	https://github.com/cncf/glossary.git (fetch)
upstream	https://github.com/cncf/glossary.git (push)

$ git remote set-url origin <new-url>
```

ref. https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories

**Comment by Okabe-Junya** [comment]
Here is the translation of the provided text into English:

---
Also, the default branch for Japanese localization is `dev-ja`. Creating branches from any other branch (for example, main) will result in them being unmergeable. Please be cautious.

(Additionally, it is recommended to create a new feature branch for your work from dev-ja.)

**Comment by Okabe-Junya** [comment]
Also, the default branch for Japanese localization is `dev-ja`. Creating branches from any other branch (for example, main) will result in them being unmergeable. Please be cautious.

(Additionally, it is recommended to create a new feature branch for your work from dev-ja.)

**Comment by draunger** [comment]
@Okabe-Junya means first i again fork this glossary repository then I will change the name of the branch from main to dev-ja then  do the issue then git push??

**Comment by Okabe-Junya** [comment]
No, the `dev-ja` branch already exists, so checkout and work it. (It appears that you have already forked it. There is no need to fork it again.)

- upstream: https://github.com/cncf/glossary/tree/dev-ja
- origin: https://github.com/draunger/glossary/tree/dev-ja
