### ISSUE TITLE
Regarding How To Contribute Guide.

### ISSUE THREAD

**Issue by Aditya-Narayan-Nayak** [cncf/glossary#278]
Please Add Step By Step How SomeOne Can Start From Scratch( It Will Be Good IF You Take a Simple Issue Solve Them And Creating Pull Request )to Adding Value In CNCF Repo. 

An Example From Community Classroom They Have Pretty Good Documentation:-https://github.com/commclassroom/commclassroom/blob/development/CONTRIBUTING.md (link)

**Comment by Alt-Shivam** [comment]
Hey @Aditya-Narayan-Nayak 
I would like to work on it.

**Comment by Alt-Shivam** [comment]
Provide me some more details,
What would you like to include in it.
Thanks

**Comment by JasonMorgan** [comment]
OBE
