### ISSUE TITLE
[ja] Localize eBPF for Japanese

### ISSUE THREAD

**Issue by Okabe-Junya** [cncf/glossary#2804]
Localize https://glossary.cncf.io/ebpf/ for Japanese

**Comment by bashi8128** [comment]
Hi @Okabe-Junya, are you already working on this term?
If not, I would like to take it on.

**Comment by Okabe-Junya** [comment]
yes!! I'm not working. Go for it :)

**Comment by Okabe-Junya** [comment]
（もし作業中であれば）#2868 でタグの変更が取り込まれそうなので、こちらでも反映していただけると助かりますーー

**Comment by bashi8128** [comment]
まだ取り掛かれてなくてすみません...
カテゴリの修正とタグ追加反映します！

**Comment by Okabe-Junya** [comment]
急かすような感じになってしまい申し訳ないです（そのような意図は全くないです🙏）

単に一緒に取り込んでもらえると助かります。よろしくお願いします :)
