### ISSUE TITLE
[ja] Localize Distributed Apps into Japanese

### ISSUE THREAD

**Issue by Okabe-Junya** [cncf/glossary#2863]
Localize https://glossary.cncf.io/distributed-apps/ into Japanese

**Comment by t-katsumura** [comment]
@Okabe-Junya 
Hi! Can you assign this work to me?

**Comment by Okabe-Junya** [comment]
もちろんです〜！よろしくお願いします。以下のドキュメントを適宜参考にしてください :)

参考:

- [Localization team guidelines](https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#localization-team-guidelines)
- 翻訳ガイドライン: [Kubernetesのドキュメントを翻訳する](https://kubernetes.io/ja/docs/contribute/localization/)
    - 用語の表記はこのドキュメントに準じてください

**Comment by t-katsumura** [comment]
ありがとうございますー！
