### ISSUE TITLE
[Update term] `Ingress` for `En`

### ISSUE THREAD

**Issue by seb-835** [cncf/glossary#2881]
#### Why this term needs to be updated? (briefly)
- Clarify the definition of ingress; in my view, the ingress controller operates as a reverse proxy rather than a web server. 
-  However, it is important for the reader to understand the term "reverse proxy," and now, the glossary lacks these terms for further clarification. 
- In the meantime, I suggest simplifying the sentence.

NOW:
The ingress controller **is a web server that allows for a single entry point through a URL** ([www.example-url.com](http://www.example-url.com/)) and does the actual routing and balancing based on different URL paths ([www.example-url.com/path](http://www.example-url.com/path)).

NEW:
The ingress controller **publish a single entry point through a URL** ([www.example-url.com](http://www.example-url.com/)) and does the actual routing and balancing based on different URL paths ([www.example-url.com/path](http://www.example-url.com/path)).

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [X] I want to work on this suggestion and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)".. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by seokho-son** [comment]
- #2904 closes this issue.
