### ISSUE TITLE
Initiate Portuguese Localization Team

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#290]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

For example, the two-letter code for Korean is `ko`.

 - Language name (ex: `Korean`): Portuguese
 - Language two-letter code (ex: `ko`): pt

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

- [A] Edson Ferreira (@edsoncelio)
- [A] Bruno Guidone (@brunoguidone)
- Jéssica Lins (@jessicalins)
- Ana Cunha (@anacunha)
- Thiago Santo (@thsanto)
- Ed Carlos Marinho de Oliveira (@edmarinho)
---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-ko`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by edsoncelio** [comment]
Hello @seokho-son, I've opened this issue to the Portuguese team, could you help us? We already have a label and a branch but I think it's better to create a new branch (`dev-pt`), following the guide that you suggested, thanks!

**Comment by seokho-son** [comment]
Thanks @edsoncelio !
I am going to create `dev-pt` branch and update label.

We need to check permission configuration for branches.
PR #296 is waiting for a peer-review. After #296 I will setup the development branch.
So, please wait for a moment :) let's interact using this issue :)

**Comment by MatheusPaes** [comment]
#312

**Comment by seokho-son** [comment]
Hello @edsoncelio ! I'd like to inform you following progress.

- Added a new label for the language.
  `lang/pt` https://github.com/cncf/glossary/issues/labels
- Created a new development branch for the l10n. 
  https://github.com/cncf/glossary/tree/dev-pt
- Update permission to add l10n contents approvers.
  Working on it (It takes time to reach consensus on updated permission strategy among administrators)

PT team can start site configuration (ex: PR #291) using the branch even though the team does not have a permission for approving PR yet.
You can refer https://github.com/cncf/glossary/blob/38bf7501dc9aea02696a1a6e8d48b74074c670c1/LOCALIZATION.md#2-configure-a-new-language-to-the-site for details (Note: it is a draft of LOCALIZATION.md from PR #341)

**Comment by edsoncelio** [comment]
Thank you @seokho-son! I'll start to work on it :D
