### ISSUE TITLE
[FR] Localize Multi-tenancy

### ISSUE THREAD

**Issue by Krast76** [cncf/glossary#2996]
### Please describe why this term needs to be updated

I'll translate multi-tenancy

**Comment by ibrahimkedir10** [comment]
i can do this issue if its still open to be re-assigned

**Comment by Krast76** [comment]
I'm already working on this one 😊

You should join our Slack channel to ask for which terms you can translate

**Comment by ibrahimkedir10** [comment]
Ive been trying to find how to join the slack and community, but no luck yet. can you please give me a slack code or invite to my email so I can join ?

**Comment by ibrahimkedir10** [comment]
@Krast76 no that link does not work as it says my email doesn’t have an account on this workspace.

can i maybe get added to by the admin to add me, or can i give you my email to get a link ?
