### ISSUE TITLE
Issue on language selection on mobile website

### ISSUE THREAD

**Issue by tperelle** [cncf/glossary#2997]
On the mobile version of the glossary website (at least on iOS), the menu entry to select another language is not present.

**Comment by jihoon-seo** [comment]
Hi @tperelle
In the mobile version, the language selector is in the bottom of each page.
![image](https://github.com/cncf/glossary/assets/46767780/a3d2105e-9bac-4a7c-b290-99a258932303)

If you found one, then please close this issue as completed,
or the problem persists, then please leave another comment!

**Comment by tperelle** [comment]
You're right! I hadn't seen it.
Thanks
So I close the issue.
