### ISSUE TITLE
[ja] Localize Service Discovery into Japanese

### ISSUE THREAD

**Issue by Okabe-Junya** [cncf/glossary#3005]
Localize https://glossary.cncf.io/service-discovery/ into Japanese

**Comment by mhdamaan79** [comment]
Hey @Okabe-Junya, I'd like to work on this task, please assign it to me.

**Comment by Okabe-Junya** [comment]
Hi @mhdamaan79, thank you for interesting in Japanese Localization project !!

Localization requires native or equivalent Japanese language proficiency. It looks you live in India. Please confirm this before working on this issue.

I believe the issues labeled with `lang/hi` or `lang/en` (or those you created) are areas where you can contribute more effectively.

**Comment by mhdamaan79** [comment]
Okay, I'll focus on contributing to the ```lang/hi``` and ```lang/en``` issues. Thank you!

**Comment by t-katsumura** [comment]
/assign 

@Okabe-Junya 
アサインお願いしますー
