### ISSUE TITLE
Add new terms SLO/SLI/SLA

### ISSUE THREAD

**Issue by Giulia-dipietro** [cncf/glossary#303]
Add three new terms to describe Service level objectives, indicators, and agreements to expand on the new SRE page. 

**Instructions**: These should be three different terms but all mirror each other and refer to one another as they all belong together.

**Comment by Giulia-dipietro** [comment]
Hi, could somebody please assign me to this issue?

**Comment by JasonMorgan** [comment]
Thank you!

**Comment by Giulia-dipietro** [comment]
@JasonMorgan thank you! 
How can I add a label? It should be lang/en  and good first issue

**Comment by JasonMorgan** [comment]
Done, thank you!

@Giulia-dipietro if you'd like to stay involved with the project we can talk about getting you set up with triage permissions. Would you mind chatting about it in the glossary channel of the CNCF slack if you're interested?

**Comment by JasonMorgan** [comment]
Hey @Giulia-dipietro are you still planning on working this?

**Comment by Giulia-dipietro** [comment]
Hi @JasonMorgan, yes I'm still working on it.

**Comment by JasonMorgan** [comment]
@Giulia-dipietro do you mind linking a PR?

**Comment by Giulia-dipietro** [comment]
Hi @JasonMorgan, I'm sorry but I have been unable to write this due to personal issues. I have removed myself to make this issue available to other contributors. I apologize for the inconvenience.

**Comment by fsbaraglia** [comment]
@JasonMorgan  Please assign it to me, I can work on it

**Comment by CathPag** [comment]
@fsbaraglia, we only allow people to work on one issue at a time. Once debugging is done, I'll assign this one to you (please remind me though) :)

**Comment by jaynarayan20** [comment]
i want to work on this issue but can anyone guide me how should i do it as i am new to open source.

**Comment by CathPag** [comment]
Sorry, @jaynarayan20, but @fsbaraglia had asked for it first and was waiting for it to move to accepted.  

@fsbaraglia, please note these should be three different terms but all mirror each other and refer to one another as they all belong together. Like CI and CD.

**Comment by fsbaraglia** [comment]
Thank you @CathPag

**Comment by fsbaraglia** [comment]
linking to a pull draft request: https://github.com/cncf/glossary/pull/680

**Comment by CathPag** [comment]
According to our new guidelines, this term does not meet the criteria for the glossary. I'll go ahead and close this issue.
