### ISSUE TITLE
[ru] Localize `Datacenter` 

### ISSUE THREAD

**Issue by FightingFox** [cncf/glossary#3048]
### Description

This Issue is to localize [datacenter.md](https://github.com/cncf/glossary/blob/main/content/en/data-center.md) into Russian.

### Checklist before opening your PR (put `x` in the checkboxes) — note that you have to _add this checklist to your PR and check all the boxes for it to be approved_.
- [] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.
    

[Link to the original term](https://github.com/cncf/glossary/blob/main/content/en/data-center.md)

ETA: April 20, 2024

Useful links:
[Как внести свой вклад](https://glossary.cncf.io/ru/contribute/)
[Руководство по стилю](https://glossary.cncf.io/ru/style-guide/)

**Comment by FightingFox** [comment]
I would like to work on this therm

**Comment by kirkonru** [comment]
Hello and welcome to the Russian localization community! 🤗 Feel free to join our [Telegram channel ](https://t.me/ru_cloudnative) to stay on top of what is happening.

Please refrain from opening Issues on your own — this makes it very difficult to keep track of them and greatly increases the risk of duplicates. On top of that, we need to maintain a certain format to make Issues easier to find and navigate.

**Comment by kirkonru** [comment]
@FightingFox I have assigned the Issue to you with an expected completion date of April 20, 2024. If you have any questions/suggestions, feel free to contact me here, in Slack or in the Telegram channel mentioned above.

**Comment by FightingFox** [comment]
@kirkonru can you fix access? Or am I doing something wrong?

![Снимок экрана 2024-04-13 в 19 19 24](https://github.com/cncf/glossary/assets/77280748/0da15e79-37d0-46fc-aa8b-f34234fecbf6)

**Comment by kirkonru** [comment]
> @kirkonru can you fix access? Or am I doing something wrong?

@FightingFox it is currently not possible to work in the main glossary repository.

#### Here is the right sequence of actions:

- Fork this repository (as suggested)
- In your fork, create a branch to work on (you can name it whatever you want, e.g., _translate-datacenter_)
- Do the translation
- Once the translation is complete, create a Pull Request to the **dev-ru** branch
