### ISSUE TITLE
Initiate German localization team

### ISSUE THREAD

**Issue by iamNoah1** [cncf/glossary#305]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

 - Language name (ex: `Korean`): German
 - Language two-letter code (ex: `ko`): de

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

- @CathPag [A]
- @iamNoah1 [A]
- @DaveVentura [A]

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-ko`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by seokho-son** [comment]
Thanks @iamNoah1 !
Thank you for the initiation! 
I am going to create dev-ge branch and update label.

For this moment, maintainers need to check permission configuration for branches.
PR #296 is waiting for a peer-review. After #296 I will setup the development branch.
So, please wait for a moment :) let's interact using this issue :)

**Comment by iamNoah1** [comment]
@seokho-son apparently #296 is merged, can we do something to move this one forward?

**Comment by seokho-son** [comment]
Hello @iamNoah1 
We are about to finish configurations. Thank you for your patience !

I shared following [message](https://cloud-native.slack.com/archives/C02N2RGFXDF/p1642425205006300?thread_ts=1642423997.006200&cid=C02N2RGFXDF) through slack channel 

---

I'd like to share current progress in setting up Localization environment. We just completed permission setting. :slightly_smiling_face: (but still need a test). Soon, we will annouce dev-kk brances for every l10n teams.

1) Create issue template #277
2) Update localization guide to update #279
3) Setup permissions and branch protection rules
 - Open a PR(#296) to setup permissions and branch protection rules
 - Review and merge the PR(#296) and PR(#324)
 - Test the configuration
   - Check a Korean approver can push a commit to dev-ko branch (We are here★)
   - Check a Korean approver cannot push a commit to main branch (We are here★)
   - Check maintainers can push a commit to every branch (We are here★)
4) Add approvers for l10n teams according to the reuqest in issues
 - Initiate Korean Localization Team #288
 - Initiate Portuguese Localization Team #290
 - Initiate Hindi Localization Team #297
 - Initiate German localization team #305
 - Initiate Italian Localization Team #308
 - ...
5) Create dev branchs for all l10n teams
6) Announce start of l10n works with the l10n dev branch

**Comment by seokho-son** [comment]
Oh, you just checked the message in slack :)

**Comment by seokho-son** [comment]
Hello @iamNoah1 ! I'd like to inform you following progress.

- Added a new label for the language.
  `lang/de` https://github.com/cncf/glossary/issues/labels
- Created a new development branch for the l10n. 
  https://github.com/cncf/glossary/tree/dev-de
- Update permission to add l10n contents approvers.
  Working on it (It takes time to reach consensus on updated permission strategy among administrators)

German team can start site configuration (ex: PR #291) using the branch even though the team does not have a permission for approving PR yet.
You can refer https://github.com/cncf/glossary/blob/38bf7501dc9aea02696a1a6e8d48b74074c670c1/LOCALIZATION.md#2-configure-a-new-language-to-the-site for details (Note: it is a draft of LOCALIZATION.md from PR #341)

**Comment by iamNoah1** [comment]
@seokho-son, FYI we updated the status of David to be an approver as well
