### ISSUE TITLE
[ru] Localize `Distributed System`

### ISSUE THREAD

**Issue by kirkonru** [cncf/glossary#3056]
### Description

This Issue is to localize [`Distributed System
`](https://github.com/cncf/glossary/blob/main/content/en/distributed-systems.md) into Russian.

### Checklist before opening your PR (put `x` in the checkboxes) — note that you have to _add this checklist to your PR and check all the boxes for it to be approved_.
- [] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.
    
**ETA: TBD**

Useful links:
[Как внести свой вклад](https://glossary.cncf.io/ru/contribute/)
[Руководство по стилю](https://glossary.cncf.io/ru/style-guide/)

[Slack channel](https://app.slack.com/client/T08PSQ7BQ/C05G46RMQTX)
[Telegram channel](https://t.me/ru_cloudnative)

**Comment by vickylikh** [comment]
I'd like to work on this issue.

**Comment by kirkonru** [comment]
Sure, you're assigned! 😎
