### ISSUE TITLE
Initiate Italian Localization Team

### ISSUE THREAD

**Issue by meryem-ldn** [cncf/glossary#308]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

 - Language name: Italian
 - Language two-letter code: it

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

- [A] Giulia Di Pietro (@giulia-dipietro)
- [A] Meryem Fourdaous (@meryem-ldn)
- [A] Annalisa Gennaro (@annalisag-spark)
- [A] Simone Stella (@sistella)

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-it`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by seokho-son** [comment]
Thank you for the initiation! @meryem-ldn
I am going to create dev-it branch and update label.

For this moment, maintainers need to check permission configuration for branches.
PR #296 is waiting for a peer-review. After #296 I will setup the development branch.
So, please wait for a moment :) let's interact using this issue :)

**Comment by seokho-son** [comment]
Hello @meryem-ldn ! I'd like to inform you following progress.

- Added a new label for the language.
  `lang/it` https://github.com/cncf/glossary/issues/labels
- Created a new development branch for the l10n. 
  https://github.com/cncf/glossary/tree/dev-it
- Update permission to add l10n contents approvers.
  Working on it (It takes time to reach consensus on updated permission strategy among administrators)

Italian team can start site configuration (ex: PR #291) using the branch even though the team does not have a permission for approving PR yet.
You can refer https://github.com/cncf/glossary/blob/38bf7501dc9aea02696a1a6e8d48b74074c670c1/LOCALIZATION.md#2-configure-a-new-language-to-the-site for details (Note: it is a draft of LOCALIZATION.md from PR #341)

**Comment by sistella** [comment]
Hi @seokho-son, we're working on site configuration. A new contributor joined us in the meanwhile, can you add him to the list of volunteers for `lang/it` https://github.com/cncf/glossary/pull/342?
* [A] Francesco Sbaraglia (@fsbaraglia)

**Comment by seokho-son** [comment]
Thank you for sharing progress. @sistella :)
Regarding the additional `approver`, maintainers are going to discuss appropriate number of `approver`s. (at this moment, maximum is four for each l10n team.) It will be determined soon. After that we will revisit this request.
(Please understand that, contributors can contribute without permission for approval. l10n team approver is responsible to manage PRs for l10n contribution.)

**Comment by seokho-son** [comment]
@sistella @fsbaraglia In a maintainers' meeting, we have decided the maximum `approvers` for a l10n team is four. 
Please understand it is to minimize permission maintenance issue. Without the permission, contributors still can contribute.
I think changing approvers may be possible based on their activities. But it is early stage of localization activities for this Glossary project, we don't have a strict policy on that yet.
(cc: @CathPag)
