### ISSUE TITLE
[it] Deprecare termine Version Control

### ISSUE THREAD

**Issue by sistella** [cncf/glossary#3111]

**Comment by matteobisi** [comment]
lo status di questa pagina è 
Deprecated  anche nella versione on-line. C'è da farci altro o si puo chiudere l'issue?

**Comment by sistella** [comment]
Ah ok allora è fatto!

**Comment by sistella** [comment]
Done https://github.com/cncf/glossary/blob/999a7e21608cfa539c8c66387aa453c71a2faddf/content/it/version-control.md?plain=1#L3
