### ISSUE TITLE
Function as a Service (FaaS) and Serverless

### ISSUE THREAD

**Issue by Mohiit70** [cncf/glossary#3113]
The page for Function as a Service (FaaS) in Platform as a Service (PaaS), Serverless, and Software-as-a-Service (SaaS) is not found.

link: https://glossary.cncf.io/function-as-a-service/
link: https://glossary.cncf.io/serverless/

![Screenshot 2024-05-05 235455](https://github.com/cncf/glossary/assets/120316966/8dc217dc-d67d-4b1a-906e-5e1b2f17891a)

**Comment by jihoon-seo** [comment]
I see that some links are broken.
We might remove links, converting links to plain texts.
