### ISSUE TITLE
Cloud Native Apps

### ISSUE THREAD

**Issue by Mohiit70** [cncf/glossary#3114]
The link provided for "tightly coupled" in the Cloud Native Apps page does not seem to be focusing correctly. The correct link for tightly coupled architecture articles is https://glossary.cncf.io/tightly-coupled-architecture/. 

link: https://glossary.cncf.io/cloud-native-apps/

![Screenshot 2024-05-06 001145](https://github.com/cncf/glossary/assets/120316966/9c6317c4-7684-46fa-a054-3a3d4ff9456f)

**Comment by asem-hamid** [comment]
issue verified . 

![image](https://github.com/cncf/glossary/assets/155321064/bdab32fb-846d-4cc2-8000-d771371c3582)

**Comment by ibrahimkedir10** [comment]
I would like to take on this issue, if it is still open

**Comment by asem-hamid** [comment]
@ibrahimkedir10  I guess no one is working on this issue  , you can go ahead .

**Comment by kumarankit999** [comment]
Go ahead and work on this issue @ibrahimkedir10

**Comment by iamNoah1** [comment]
@Mohiit70 nice catch :) thanks. Will assign @ibrahimkedir10

**Comment by ibrahimkedir10** [comment]
okay will do. @kumarankit999 @asem-hamid
