### ISSUE TITLE
[ru] Localize `Loosely Coupled Architecture`

### ISSUE THREAD

**Issue by kirkonru** [cncf/glossary#3124]
### Description

This Issue is to localize [`Loosely Coupled Architecture`](https://github.com/cncf/glossary/blob/main/content/en/loosely-coupled-architecture.md) into Russian.

### Checklist before opening your PR (put `x` in the checkboxes) — note that you have to _add this checklist to your PR and check all the boxes for it to be approved_.
- [] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.
    
**ETA: TBD**

Useful links:
[Как внести свой вклад](https://glossary.cncf.io/ru/contribute/)
[Руководство по стилю](https://glossary.cncf.io/ru/style-guide/)

[Slack channel](https://app.slack.com/client/T08PSQ7BQ/C05G46RMQTX)
[Telegram channel](https://t.me/ru_cloudnative)

**Comment by hcz** [comment]
@kirkonru Please assign me this issue

I've already localized articles about "Loosely Coupled Architecture" and related "Highly Coupled Architecture", and prepared PR https://github.com/cncf/glossary/pull/3199

**Comment by kirkonru** [comment]
Hi! You're assigned!

**Comment by kirkonru** [comment]
I have added a separate Issue #3203 for [Tightly Coupled Architecture](https://github.com/cncf/glossary/blob/main/content/en/tightly-coupled-architecture.md). Please note that in the CNCF glossary, a dedicated PR for each term is considered good practice, i.e., it is strongly recommended to open an individual PR for each term.

**Comment by hcz** [comment]
@kirkonru These articles are cross-referenced, so I decided to combine changes to the single PR.
Do I need to separate them in two PRs?
