### ISSUE TITLE
[English]: Shift Left

### ISSUE THREAD

**Issue by murriel** [cncf/glossary#314]
### Details 
Shift left, including relevance for cloud, development, devops, testing, and security

**Comment by JasonMorgan** [comment]
Hey @murriel are you planning to submit a PR for this? It's a good issue regardless but it's currently assigned to you.

**Comment by murriel** [comment]
Yes! I was planning to write this shortly after submitting the issue and got sidetracked. Will submit a PR in the next day or so. Thank you so much for following up.

**Comment by JasonMorgan** [comment]
Hey @murriel do you mind linking a PR even if it's a WIP?

**Comment by murriel** [comment]
Apologies for the delay - any feedback on the entry is welcome!
