### ISSUE TITLE
[zh-cn]Could someone update the dev-zh branch to match the main branch?

### ISSUE THREAD

**Issue by Petrie** [cncf/glossary#3145]
I attempted to create a merge request to do this, but I don't have the permission. 
The error message says 'Pull request creation failed. Validation failed: must be a collaborator'.

**Comment by seokho-son** [comment]
Hi dev-zh approvers!
@hanyuancheung @Jacob953 @Rocksnake @Submarinee

Could you open a PR to update main branch according to the dev-zh ?

Also, PTAL https://github.com/cncf/people/pull/769#issuecomment-2559259734
Regarding the request from @pacoxu 

(CC: @cjyabraham @iamNoah1 )

**Comment by hanyuancheung** [comment]
> Hi dev-zh approvers! [@hanyuancheung](https://github.com/hanyuancheung) [@Jacob953](https://github.com/Jacob953) [@Rocksnake](https://github.com/Rocksnake) [@Submarinee](https://github.com/Submarinee)
> 
> Could you open a PR to update main branch according to the dev-zh ?
> 
> Also, PTAL [cncf/people#769 (comment)](https://github.com/cncf/people/pull/769#issuecomment-2559259734) Regarding the request from [@pacoxu](https://github.com/pacoxu)
> 
> (CC: [@cjyabraham](https://github.com/cjyabraham) [@iamNoah1](https://github.com/iamNoah1) )

Of course, we'll finish it recently. Thanks for reminding us.

**Comment by iamNoah1** [comment]
Branches are up to date
