### ISSUE TITLE
[English]: Hyperscaler 

### ISSUE THREAD

**Issue by murriel** [cncf/glossary#315]
### Details (optional)

What are hyperscalers and how did this term originate?

**Comment by PadminiRai** [comment]
I'd like to work on it.

**Comment by CathPag** [comment]
Hi @PadminiRai, I just assigned Golden Signals to you. Please finish that term first before claiming a new one — thank you!

**Comment by shambashib20** [comment]
Can I work on this issue @CathPag? I already pinged you up for the other issue right there!

**Comment by CathPag** [comment]
@hady68, here you go.

@shambashib20, unfortunately, hady68 claimed the issue before you did. If you claimed another issue, you shouldn't be claiming a new one anyways. We only assigned one issue per person :)

**Comment by CathPag** [comment]
@hady68, please make sure to read the [style guide](https://glossary.cncf.io/style-guide/) before getting started — that is very important.

**Comment by CathPag** [comment]
@hady68, I'll open this issue up again since it's been assigned to you over a month and we haven't seen any PR yet. If you have been working on something and were about to submit, please let me know and I'll reassign it to you.

**Comment by CathPag** [comment]
After some consideration, the maintainers couldn't determine if this term should be included in the Glossary per our new guidelines (terms must meet the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or be a foundational term to understand it). For that reason, we will not include this term until we have found a good reason to do so.
