### ISSUE TITLE
[English]: Declarative System

### ISSUE THREAD

**Issue by avinashupadhya99** [cncf/glossary#317]
Add Declarative System to the glossary

**Comment by JasonMorgan** [comment]
Can you provide some more context? Any examples you have of "Declarative System" being used would be handy.

**Comment by avinashupadhya99** [comment]
Kubernetes is a Declarative System and a very important design principle of Kubernetes. When folks are trying to understand Kubernetes, understanding Declarative Systems becomes very important

**Comment by mayank-cse** [comment]
@JasonMorgan  ma'am and @avinashupadhya99  sir
If the issue is not yet assigned to anyone, I would like to work on it

Thank You:)

**Comment by CathPag** [comment]
Oops, sorry. You already have Container Storage Interface assigned. Please finish that one first before claiming a new term.

**Comment by Anujakumari** [comment]
@CathPag
Can I work on this issue?

**Comment by CathPag** [comment]
@Anujakumari, I'll open this PR up again since it's been assigned to you over in February and we haven't seen any PR yet.

**Comment by CathPag** [comment]
We reviewed this issue and, since it doesn't meet the cloud native definition, we will not include this in the glossary.
