### ISSUE TITLE
[Portuguese] Rename and update the content of tightly-coupled-architectures.md and microservices.md

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#3179]
Rename the following files:
* `tightly-coupled-architectures.md` -> `tightly-coupled-architecture.md`
* `microservices.md` -> `microservices-architecture.md`

And update the content with the original (`content/en/`)

**Comment by camilosm** [comment]
Hi! Can I work on this one? Thanks!

**Comment by edsoncelio** [comment]
> Hi! Can I work on this one? Thanks!

Sure! 
I'll assign it to you; let us know If you have any questions.
