### ISSUE TITLE
[Portuguese] Localize GitOps

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#3180]
Localize https://glossary.cncf.io/gitops/

**Comment by thiagorider** [comment]
@edsoncelio I can work on this one! Could you please assign it to me? 😃

**Comment by edsoncelio** [comment]
> https://glossary.cncf.io/gitops/

Thanks, sure! 
I will assign this issue to you, and the other two I will assign when you finish this one.
If you have any questions, let me know :)

**Comment by thiagorider** [comment]
Hi @edsoncelio ! #3252 resolves this issue!

**Comment by edsoncelio** [comment]
> Hi @edsoncelio ! #3252 resolves this issue!

Thanks! As soon as possible, I'll take a look
