### ISSUE TITLE
Cloud Native Glossary page resets the scroll to top whenever a tag is selected in the left side scrollable pane.

### ISSUE THREAD

**Issue by ritveak** [cncf/glossary#3209]
Cloud Native Glossary page resets the scroll to top whenever a tag is selected in the left side scrollable pane.

It is disruptive if someone is going through the tags one by one, they have to scroll back to their visited tag.

Ideally, the scroll bar should stay at the same state and only the content part should be refreshed whenever a new tag is selected.

**Comment by arunkarthicknm** [comment]
Can I take this issue?

**Comment by Okabe-Junya** [comment]
Thanks, help is welcome :)

**Comment by thetwopct** [comment]
I wonder if another solution is to offer a "next" and "previous" button (or similar) at the bottom of each page, which would lead to the next item in the list. This would negate the need for some kind of auto-scrolling sidebar (@arunkarthicknm how are you progressing with this task?)
