### ISSUE TITLE
Initiate Arabic localization team

### ISSUE THREAD

**Issue by same7ammar** [cncf/glossary#326]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

 - Language name : Arabic
 - Language two-letter code : ar

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

-  [A] Tarek M. Sayed (@tarekmsayed)
-  [A] Sameh Ammar (@same7ammar)
-  [A] Ahmed Shabana (@AShabana)
-  [A] Osama Nabil (@Hacktron95)

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-ar`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by seokho-son** [comment]
Hello @same7ammar  :) 
Thank you for the initiation of l10n for Arabic !!

We are going to proceed following tasks
- Add a new label for the language.
- Update codeowners to add l10n contents approvers.
- Create a new development branch for the l10n. (dev-ar)

But we are testing some permission issues for new branches. So, these tasks will take some time.

**Comment by seokho-son** [comment]
Hello @same7ammar ! I'd like to inform you following progress.

- Added a new label for the language.
  `lang/ar` https://github.com/cncf/glossary/issues/labels
- Created a new development branch for the l10n. 
  https://github.com/cncf/glossary/tree/dev-ar
- Update permission to add l10n contents approvers.
  Working on it (It takes time to reach consensus on updated permission strategy among administrators)

Arabic team can start site configuration (ex: PR #291) using the branch even though the team does not have a permission for approving PR yet.
You can refer https://github.com/cncf/glossary/blob/38bf7501dc9aea02696a1a6e8d48b74074c670c1/LOCALIZATION.md#2-configure-a-new-language-to-the-site for details (Note: it is a draft of LOCALIZATION.md from PR #341)

**Comment by same7ammar** [comment]
Hi @seokho-son .
Thank you so much 👍 .
