### ISSUE TITLE
[English]: Orchestrator

### ISSUE THREAD

**Issue by turjachaudhuri** [cncf/glossary#327]
### Details (optional)

Currently , in the CNCF glossary , there is no term - "Orchestrator" .
I believe this is an important concept in Cloud Native ecosystem , and should be part of the glossary .

Let me know your thoughts .

**Comment by turjachaudhuri** [comment]
If the issue is accepted will like to work on this .

**Comment by JasonMorgan** [comment]
@turjachaudhuri happy to assign but you have another issue assigned already. Do you mind completing that first?

**Comment by Asmit2952** [comment]
Can I work on this? @JasonMorgan

**Comment by Asmit2952** [comment]
Can I work on this? @JasonMorgan @CathPag

**Comment by CathPag** [comment]
Sure, here you go, @Asmit2952 :)

**Comment by CathPag** [comment]
@Asmit2952, I'll open this PR up again since it's been assigned to you over a month ago and we haven't seen any PR yet. If you have been working on something and were about to submit, please let me know and I'll reassign it to you.

**Comment by Asmit2952** [comment]
> @Asmit2952, I'll open this issue up again since it's been assigned to you over a month ago and we haven't seen any PR yet. If you have been working on something and were about to submit, please let me know and I'll reassign it to you. 

Hey @CathPag , I was busy with university exams. I'm almost done with them. I will start working on this as soon as possible. Please reassign this issue to me.

**Comment by CathPag** [comment]
ok, there you go

**Comment by Asmit2952** [comment]
Hey @CathPag is it fine if we change the term to orchestration rather than orchestrator? Orchestration involves the entire process while orchestrator is just a tool required for orchestration.

**Comment by iamNoah1** [comment]
Hi @Asmit2952 and thank you for your patience. After having some discussions we decided to rename `Orchestrator` to `Container Orchestration`. Regarding issue #701, our conclusion is to remove CaaS and Kubernetes as single terms and just mention them in the `Container Orchestration` term. Feel free to ask if something is still not clear.

**Comment by Asmit2952** [comment]
> Hi @Asmit2952 and thank you for your patience. After having some discussions we decided to rename `Orchestrator` to `Container Orchestration`. Regarding issue #701, our conclusion is to remove CaaS and Kubernetes as single terms and just mention them in the `Container Orchestration` term. Feel free to ask if something is still not clear.

So, I think instead of writing about `Orchestrator`, I need to write about `Container Orchestration`?

**Comment by Asmit2952** [comment]
> Yes.

Cool, I'll work on it as soon as I am done with university stuff

**Comment by CathPag** [comment]
@Asmit2952, do you still want to work on this?

**Comment by Asmit2952** [comment]
> @Asmit2952, do you still want to work on this?

Created a PR. Sorry for delaying this, was busy with university stuff. Thank you for your patience.

**Comment by sha-lik** [comment]
I want to work on this

**Comment by CathPag** [comment]
@sha-lik, this issue has already been assigned and @Asmit2952 is working on it.

**Comment by sha-lik** [comment]
Okay
