### ISSUE TITLE
No issue template for general issues like bug/enhancement/etc

### ISSUE THREAD

**Issue by jihoon-seo** [cncf/glossary#332]
### Details (optional)

There is no issue template for general issues like bug/enhancement/etc for this repo.

- https://github.com/cncf/glossary/tree/main/.github/ISSUE_TEMPLATE
- https://github.com/cncf/glossary/issues/new/choose

![image](https://user-images.githubusercontent.com/46767780/149854643-41c869cb-cb47-4889-9a58-6832e845c2e2.png)

**Comment by verma-kunal** [comment]
Hey @jihoon-seo , i can work on this one! 🙂

**Comment by verma-kunal** [comment]
Hey @jihoon-seo @JasonMorgan  , what are some of the main things we would be having in a bug report?
The main points i have thought of are:
- Description of the bug
- Working environment (e.g. operating system, browser, device)
- Adding any screenshot (if needed)
- Any other comments or context related to the topic

Anything else that could be added?

**Comment by seokho-son** [comment]
Hi @verma-kunal , I think we need to check current issue-templates and need some decisions by maintainers (remove, update, add). Could you let me handle this issue first? I will leave some tasks that you can contribute soon :)

**Comment by verma-kunal** [comment]
Sure @seokho-son , sounds good! 🙂
