### ISSUE TITLE
[English]: Chaos Engineering

### ISSUE THREAD

**Issue by avinashupadhya99** [cncf/glossary#336]
### Details (optional)

Add Chaos Engineering to glossary

**Comment by Alt-Shivam** [comment]
I want to work on this.
assign it to me

**Comment by CathPag** [comment]
Removing @Alt-Shivam as requested in the other issue.

**Comment by fsbaraglia** [comment]
Hi Team, I would like to work on this issue

**Comment by fsbaraglia** [comment]
pull request already in place #357

**Comment by fsbaraglia** [comment]
PR for only Chaos Eng concept https://github.com/cncf/glossary/pull/498
