### ISSUE TITLE
Initiate Bengali Localization Team 

### ISSUE THREAD

**Issue by mitul3737** [cncf/glossary#339]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

For example, the two-letter code for Korean is `ko`.

 - Language name (ex: `Korean`): Bengali
 - Language two-letter code (ex: `ko`): bn

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

Ex: `- [A] Seokho Son (@seokho-son)`

- [A] MD. Shahriyar Al Mustakim Mitul ( @mitul3737 )
- [A] Umme Abira Azmary ( @Mouly22 )
- [A] MD Ikramul Kayes ( @ikramulkayes )

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-ko`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by seokho-son** [comment]
Hello @mitul3737  :)
Thank you for the initiation of l10n for Bengali !!

We are going to proceed following tasks

- Add a new label for the language. (lang/bn)
- Update codeowners to add l10n contents approvers.
- Create a new development branch for the l10n. (dev-bn)

But we are testing some permission issues for new branches. So, these tasks will take some time.
(You can check current status from a slack message: https://cloud-native.slack.com/archives/C02N2RGFXDF/p1642425205006300?thread_ts=1642423997.006200&cid=C02N2RGFXDF)

**Comment by seokho-son** [comment]
Hello @mitul3737 ! I'd like to inform you following progress.

- Added a new label for the language.
  `lang/bn` https://github.com/cncf/glossary/issues/labels
- Created a new development branch for the l10n. 
  https://github.com/cncf/glossary/tree/dev-bn
- Update permission to add l10n contents approvers.
  Working on it (It takes time to reach consensus on updated permission strategy among administrators)

Bengali team can start site configuration (ex: PR #291) using the branch even though the team does not have a permission for approving PR yet.
You can refer https://github.com/cncf/glossary/blob/38bf7501dc9aea02696a1a6e8d48b74074c670c1/LOCALIZATION.md#2-configure-a-new-language-to-the-site for details (Note: it is a draft of LOCALIZATION.md from PR #341)

**Comment by mitul3737** [comment]
@seokho-son  the candidate list is confirmed
