### ISSUE TITLE
[English]: Database as a Service (DBaaS)

### ISSUE THREAD

**Issue by avinashupadhya99** [cncf/glossary#340]
### Details (optional)

Add Database as a Service (DBaaS) to the glossary

**Comment by jihoon-seo** [comment]
It seems that 'DBaaS' is more common expression.
@avinashupadhya99 What do you think? 😊

**Comment by avinashupadhya99** [comment]
Yes, DBaaS is a more common expression. I will edit it.

**Comment by CathPag** [comment]
@avinashupadhya99, do you want to work on this term or are you only suggesting it?

**Comment by avinashupadhya99** [comment]
I will leave it to a technical writer, I'm only suggesting

**Comment by Alt-Shivam** [comment]
hey @CathPag ,
Assign it to me. :)

**Comment by CathPag** [comment]
Looks like you already have chaos engineering assigned, so let's wait until you're done for the next term

**Comment by Alt-Shivam** [comment]
Hey @CathPag 
I am too busy these days with my college assignments.
You can assign it to anyone else. :)
Thanks

**Comment by Asmit2952** [comment]
Is this issue still open? Can you assign me this issue @CathPag?

**Comment by Asmit2952** [comment]
Is this issue active? @CathPag

**Comment by CathPag** [comment]
There you go, @Asmit2952
