### ISSUE TITLE
[English]: TLS

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#344]
### Details (optional)

Need TLS definition so we can link mTLS to it

**Comment by Alt-Shivam** [comment]
Hey @CathPag 
I would like to work on it.

**Comment by CathPag** [comment]
As mentioned in the other issue, please select one term as we only allow people to work on one at a time — thank you!

**Comment by Alt-Shivam** [comment]
Apologies for it.

**Comment by Alt-Shivam** [comment]
I will take this only. :)
