### ISSUE TITLE
[English]: Event Streaming

### ISSUE THREAD

**Issue by avinashupadhya99** [cncf/glossary#346]
Add Event Streaming to the glossary. This https://landscape.cncf.io/card-mode?category=streaming-messaging&grouping=category should give a good idea about Cloud Native Streaming

Should `Messaging` be a part of this or should it be a separate word if it all included?

**Comment by TheJaySmith** [comment]
I am happy to tackle this

**Comment by CathPag** [comment]
Sorry, just seeing this, @jasonsmithio. If possible, please also ping us in the Slack channel. There are so many issues, it's really difficult to keep track. Are you still interested in this one or would you rather wait for serverless eventing?

**Comment by iamNoah1** [comment]
@wafi981 thanks for your interest. I think @jasonsmithio wanted to work on this initially. Jason do you still want to do it or can we assign it to @wafi981?
