### ISSUE TITLE
Two stateful app entries

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#35]
Tom Leyden, could you please address this? You mentioned your stateful app entry wasn't in the glossary, so I added part of it per our email conversation. We did have one, though, and we have two: Stateful Apps [https://github.com/cncf/glossary/blob/main/definitions/stateful_apps.md](url) and Stateful vs Stateless Apps [https://github.com/cncf/glossary/blob/main/definitions/stateful_vs_stateless_applications](url) The latter is yours. 

Could you please add what's missing in the original entries and delete the one latter one?

**Comment by TomLeyden** [comment]
@CathPag Neither of these links give me any results. Really not sure what to do. If the entries are there, it's ok, I'm not too worried about not being mentioned. As said, I had entered the content in the Google doc and it looks like my content was not used. I can live with that.

**Comment by CathPag** [comment]
Strange. Trying again. If this doesn't work, just follow the path in the screen recording (also, realized that I didn't save my file as .md Rookie mistake :) Just updated but not in the recording yet):
https://github.com/cncf/glossary/blob/main/definitions/stateful_apps.md
https://github.com/cncf/glossary/blob/main/definitions/stateful_vs_stateless_applications
https://github.com/cncf/glossary/blob/main/definitions/stateless_apps.md

https://user-images.githubusercontent.com/74001907/107954069-fd7cdd00-6f69-11eb-8215-851d22de9361.mov

**Comment by CathPag** [comment]
Tom doesn't have time to tackle this right now which opens this up to anyone who's interested.
