### ISSUE TITLE
Make contributing easier

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#36]
- [x] Add a how-to document for accomplishing some common tasks.
- [ ] Link the github tutorial recording to the README.md

**Comment by sandipanpanda** [comment]
Hey, I would love to work on this. Can you please elaborate or maybe throw a few examples on what type of "how-to document for accomplishing some common tasks" you are referring to?

**Comment by sandipanpanda** [comment]
Hey there, I would like to work on the second part of the issue: 
- [ ]  Link the GitHub tutorial recording to the README.md 

I want to make a video tutorial on: How to navigate https://github.com/cncf/glossary and submit a PR. Please give some feedback and suggest me on whether I can work on this.

**Comment by JasonMorgan** [comment]
OBE
