### ISSUE TITLE
[English]: Idempotence

### ISSUE THREAD

**Issue by murriel** [cncf/glossary#364]
### Details (optional)

Optional details

**Comment by hady68** [comment]
how can i contribute in this issue ?

**Comment by shambashib20** [comment]
hey! @CathPag  how can I contribute here? I want to work on this one! Can you guide about how to work on this issue?

**Comment by CathPag** [comment]
@hady68, as I mentioned to shambashib20 in the other issue, please only claim one issue at a time.

@shambashib20, since hady68 has already claimed an issue, this is yours. Please make sure to read the [style guide](https://glossary.cncf.io/style-guide/) before getting started.

**Comment by shambashib20** [comment]
Okay no probs!

**Comment by shambashib20** [comment]
Yeah, I have already started researching on this one!

**Comment by CathPag** [comment]
Hi @neelshah2409, I'm sorry but this is already done. We forgot to close the issue so I will do so now.
