### ISSUE TITLE
[English]: Continuous Deployment

### ISSUE THREAD

**Issue by murriel** [cncf/glossary#365]
### Details (optional)

Create an entry for Continuous Deployment OR update the Continuous Delivery entry to distinguish between CD as Continuous Deployment vs Continuous Delivery

**Comment by Vrukshali-26** [comment]
Can I work on this issue?

**Comment by CathPag** [comment]
Absolutely!

**Comment by Vrukshali-26** [comment]
Hey @CathPag, should I create a new file named continuous_deployment.md or just update the continuous delivery one??

**Comment by Vrukshali-26** [comment]
Hey @CathPag I have created https://github.com/cncf/glossary/pull/441 for this issue.
