### ISSUE TITLE
[English]: Golden Signals 

### ISSUE THREAD

**Issue by murriel** [cncf/glossary#367]
### Details (optional)

Optional details

**Comment by PadminiRai** [comment]
Can I work on it ?

**Comment by CathPag** [comment]
Here you go, @PadminiRai. Please make sure to read the [style guide](https://glossary.cncf.io/style-guide/) before getting started and let us know if you have any questions.

**Comment by JasonMorgan** [comment]
@remote007 how's it going? Is there anything we can do to help this move forward?

**Comment by remote007** [comment]
Hi @JasonMorgan , I edited the content it's in the draft format rn. I fell ill and am taking some rest. Will create asap. Thanks for asking.

**Comment by CathPag** [comment]
Apologies for the delay, but this term no longer meets the requirements to be included in the cloud native glossary. I will go ahead and close this issue.
