### ISSUE TITLE
[help complete]: Load Balancer

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#373]
### Details (optional)

This [load balancer definition ](https://github.com/cncf/glossary/blob/main/content/en/load_balancer.md)needs a little more context. Please refer to the [style guide ](https://glossary.cncf.io/style-guide/)before getting started.

Here's some feedback that needs to be incorporated:

## What it is (update)

Load balancing refers to a process in which network traffic is distributed across multiple application instances. Services communicate over a network to coordinate and provide some type of functionality. Applications generally have multiple services with the same functionality, and, to ensure one service doesn't get all the requests, the (request) load is balanced across those services. A load balancer can be software or hardware-based.

## Problem it addresses (feedback on current definition)

This is not talking about the problem it addresses. Instead, it's focusing on the solution (which goes in the next section). 
"Problem it addresses should focus on the problem, not the solution (that comes in the next section). In fact, avoid mentioning the term that is defined. The problem focuses on what led us to need that thing."

**Comment by abhilashk433** [comment]
Hi @CathPag @JasonMorgan, Could you please assign this issue to me?

**Comment by CathPag** [comment]
Done! :)

**Comment by abhilashk433** [comment]
Hi @CathPag , I have created PR #400 . Could you please review it?

**Comment by CathPag** [comment]
This issue is available again (we had to close the PR for this term due to inactivity).

**Comment by enraiha0307** [comment]
Can I help on this?

**Comment by CathPag** [comment]
Sure, here you go! Please make sure to read the [style guide](https://glossary.cncf.io/style-guide/) before getting started

**Comment by sarkartanmay393** [comment]
Hello @CathPag, Have we still had this issue? I can't see the load balancer definition page.

**Comment by sarkartanmay393** [comment]
Hello @CathPag, I am Tanmay Sarkar, new to CNCF community. I would like to work on it.

**Comment by CathPag** [comment]
Hi @sarkartanmay393, sure. [Here's the PR](https://github.com/cncf/glossary/pull/651/files) that was closed. The "what it is section" is pretty much good to go. The feedback on the other two sections might be interesting to read as well as you work on this.
