### ISSUE TITLE
[English]: Version/Source Control

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#385]
### Details (optional)

Please refer to the [style guide ](https://glossary.cncf.io/style-guide/)before getting started.

**Comment by arunkarthicknm** [comment]
Hey @CathPag Can you tell me what to do , I read the style guide :)

**Comment by CathPag** [comment]
Hi @arunkarthicknm, we need a definition for version control. How these definitions should look like is described in the [style guid](https://docs.google.com/spreadsheets/d/1OFs5ho6QIn1tPbjHUKrYGO7tHgC6jAP0JUHV7sXGEbA/edit#gid=0)e, does that make sense?

**Comment by arunkarthicknm** [comment]
Yeah sure, I can work on this :)

**Comment by CathPag** [comment]
Here you go :)
