### ISSUE TITLE
[Updated]: Automation

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#386]
### Details (optional)

Here's an initial definition for [automation](https://github.com/cncf/glossary/blob/main/content/en/automation.md) that needs a few tweaks before going live. 

To claim this issue, please ask for it below AND in the #glossary channel of the CNCF Slack (to ensure we don't miss it). Before getting started, please refer to the [style guide](https://glossary.cncf.io/style-guide/).

**Comment by CathPag** [comment]
There you go, @a-muk.

**Comment by a-muk** [comment]
@CathPag Can you please give me some more details on this issue? I went through the links that you have provided.

**Comment by JasonMorgan** [comment]
OBE
