### ISSUE TITLE
Initiate Spanish Localization Team

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#387]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

 - Language name: Spanish 
 - Language two-letter code: `es` 

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

- [A] Catherine Paganini (@CathPag)
- [A] Rael Garcia (@raelga)
- [A] Victor Morales (@electrocucaracha)
- Rodolfo Martínez Vega (@ramrodo)
- Miguel Garzon (@miguelangat)
- Yngrid Coello (@yngrdyn)
- Carol Valencia (@krol3)
- Anyul Rivas Oropeza (@anyulled) 
- Jhonnatan Gil(@jthan24)

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-ko`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by raelga** [comment]
Awesome!

**Comment by seokho-son** [comment]
Hello @electrocucaracha 
Thank you the initiation of Spanish localization team !

I'd like to inform you following progress.

- Added a new label for the language.
lang/es https://github.com/cncf/glossary/issues/labels

- Created a new development branch for the l10n.
https://github.com/cncf/glossary/tree/dev-es

- Update permission to add l10n contents approvers.
Working on it (I will open a PR to do this, after a consensus among maintainers)

I will review #388 :)

**Comment by anyulled** [comment]
Hi @electrocucaracha please add me to this initiative

**Comment by yngrdyn** [comment]
Let's go! 🚀

**Comment by habarahonaa** [comment]
Heeey dear friends! May I please be added to this initiative? Thanks in advance :)

**Comment by CathPag** [comment]
Hi, for those interested in joining the Spanish localization team, please join the #glossary-localizations and #glossary-localization-spanish channels on the CNCF Slack
