### ISSUE TITLE
[English]: Ingress

### ISSUE THREAD

**Issue by Krishnamohan-Yerrabilli** [cncf/glossary#422]
### Details (optional)

I'm happy to work on this content.

**Comment by JasonMorgan** [comment]
Let's change it to ingress and we can use ingress controller in the example.

**Comment by iamNoah1** [comment]
What Jason said and please keep in mind to also bring in the term ingress resource if you want to use ingress controller. I found that people have problems distinguishing between those.  @Krishnamohan-Yerrabilli

**Comment by PrathyushaModala** [comment]
@CathPag  I would like work on this issue

**Comment by Krishnamohan-Yerrabilli** [comment]
> Pasting the same message I posted in the other issue:
> 
> @PrathyushaModala, you asked to be assigned to three issues. We only assign one issue per person. Which one would you like to tackle? 

It's fine for me, if she want to work on that.

**Comment by PrathyushaModala** [comment]
> > Pasting the same message I posted in the other issue:
> > @PrathyushaModala, you asked to be assigned to three issues. We only assign one issue per person. Which one would you like to tackle?
> 
> It's fine for me, if she want to work on that.

@Krishnamohan-Yerrabilli , you can pick up this issue I'm okay with it.

**Comment by Krishnamohan-Yerrabilli** [comment]
Yep ok, but I don't when I pick this up, cause this issue is still opened, anyone can work on this, if they're interested .

**Comment by Krishnamohan-Yerrabilli** [comment]
> > > Pasting the same message I posted in the other issue:
> > > @PrathyushaModala, you asked to be assigned to three issues. We only assign one issue per person. Which one would you like to tackle?
> > 
> > It's fine for me, if she want to work on that.
> 
> @Krishnamohan-Yerrabilli , you can pick up this issue I'm okay with it.

Yep ok, but I don't  know when I will pick this up, cause this issue is still opened, anyone can work on this, if they're interested .

**Comment by aakankshabhende** [comment]
@CathPag I'm ready to work on this issue. Could you please assign me this?

**Comment by Krishnamohan-Yerrabilli** [comment]
> @CathPag I'm ready to work on this issue. Could you please assign me this?

Thanks for showing interest in working on this. It will be assigned to you soon by @CathPag

**Comment by aakankshabhende** [comment]
Yes I have read it

**Comment by CathPag** [comment]
Ok, I assume you also confirm that you have deep cloud native expertise. That was the actual question ;)

**Comment by aakankshabhende** [comment]
Yes I'm working on it

**Comment by aakankshabhende** [comment]
Could you please suggest to me which tags I should use? @CathPag

**Comment by CathPag** [comment]
Don't worry about the tags right now. Add that as a comment in the PR, and we can start a discussion there when it has been submitted. Will have to think about it. Might only be fundamentals.

**Comment by aakankshabhende** [comment]
Will make a PR by tomorrow.
