### ISSUE TITLE
[English]: Debugging

### ISSUE THREAD

**Issue by Krishnamohan-Yerrabilli** [cncf/glossary#423]
### Details (optional)

I'm so excited to work on this term.

**Comment by CathPag** [comment]
This PR is available again. Below is a definition that is almost ready. The how it works needs a little more context.

## What it is

A bug is a software error or fault leading to incorrect or unexpected output. Debugging is the process or activity of identifying and removing these bugs (or errors) from a software program to get the desired output.

## Problem it addresses

When developers write code errors occur. That affects the program which will likely not function as desired (undefined behavior). To identify the source of the problem developers have to review the code line-by-line. Without context, i.e. variables, data, location in memory, etc., catching errors is quite hard.

## How it helps
Debugging tools provide developers with the needed context to review code and catch errors. By running the program and connecting a debugger, developers can control the flow of the program and instruct it to stop the program at specific points where ...[they suspect the error may be?]. >> needs more info. what exactly do they see and how are errors flagged?

**Comment by fsbaraglia** [comment]
@CathPag  assign it to me, I will finish

**Comment by CathPag** [comment]
Here you go :)

**Comment by Krishnamohan-Yerrabilli** [comment]
My apologies @JasonMorgan for not giving an update on this issue, thank you to @CathPag for assigning this issue to another person :) .

**Comment by fsbaraglia** [comment]
Hi @CathPag @JasonMorgan , this is the first version  , here the PR : https://github.com/cncf/glossary/pull/552 
if you can please have a look, you might find some good improvements
