### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by caniszczyk** [cncf/glossary#425]

**Comment by Asmit2952** [comment]
Can I work on this? @caniszczyk

**Comment by iamNoah1** [comment]
I also tend to look after a contribution.md in open source repositories, so I already thought about this as well. But there is a [contribution guide](https://glossary.cncf.io/contribute/), so I am not entirely sure if it makes sense to have a contribution.md as well. What do you think @CathPag @seokho-son @JasonMorgan?!

**Comment by iamNoah1** [comment]
Also @Asmit2952, @caniszczyk thanks for your willingness to help. Make sure to join the #glossary channel of the [cncf slack](https://cloud-native.slack.com)

**Comment by seokho-son** [comment]
@iamNoah1 @Asmit2952 Thank you for your support ! :) 
@caniszczyk is a maintainer of this repository. It would be better for the contributors to discuss what caniszczyk thinks before they start contributing :) 

@caniszczyk 
As @iamNoah1 mentioned, there is a there is a contribution guide https://glossary.cncf.io/contribute/ (https://github.com/cncf/glossary/blob/main/content/en/contribute/_index.md).
Is a CONTRIBUTING.md that includes a link to the contribution guide webpage https://glossary.cncf.io/contribute/ enough? 
or do we need additional contents regarding contribution ?

**Comment by CathPag** [comment]
Ideally, it'd live on the GitHub code page AND on the glossary website. @cjyabraham, see the conversation above. Can we move things around so the same content is found in both places?

**Comment by cjyabraham** [comment]
My sense is that a CONTRIBUTING.md file is [a standard GitHub file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) for any repo that should outline rules and guidelines for contributing to the glossary repo as a whole, which includes the core code for running a glossary site. This file will show up in a sidebar link when people create PRs and issues.

[The contributing guide that we publish here](https://glossary.cncf.io/contribute/) is directed at those who want to contribute to the _contents_ of the glossary, not its underlying code.

So I feel they both address a different use-case and should be kept distinct. Any thoughts?

**Comment by CathPag** [comment]
@JasonMorgan, @seokho-son, @jihoon-seo, @iamNoah1, let's think about what makes sense. We could discuss during our meeting on Monday.

**Comment by JasonMorgan** [comment]
Hey folks! I'm a bit confused about who's going to be writing this guide. @cjyabraham do you plan on handling this?

**Comment by cjyabraham** [comment]
I don't know. I wasn't part of the meeting that @CathPag suggested above so don't know what the follow-up items were. I'm happy to help if that was the decision.

**Comment by Asmit2952** [comment]
> We didn't cover it in the meeting but your suggestion above has a thumbs up from the rest of the maintainers. Your suggestion [here](https://github.com/cncf/glossary/issues/425#issuecomment-1042866779) seems to be appropriate. Please add the CONTRIBUTING.md and include some basic content on working with the repo that includes a link to the contributing guide.

So can I work on this?

**Comment by cjyabraham** [comment]
[I've submitted a PR](https://github.com/cncf/glossary/pull/501)

**Comment by CathPag** [comment]
Thank you, @cjyabraham !!
