### ISSUE TITLE
[English]: DataOps

### ISSUE THREAD

**Issue by cnu1812** [cncf/glossary#431]
### Details (optional)

Optional details

**Comment by JasonMorgan** [comment]
@cnu1812 are you interested in working this? Also can you provide an example where you see dataops being used?

**Comment by cnu1812** [comment]
I am working on other issue currently. And I would like to take up after that. Meanwhile if anyone interested can do this.

**Comment by iamNoah1** [comment]
@cnu1812 can you please open a new issue and fill the template correctly, this would help us with further proceeding :) thanks
