### ISSUE TITLE
How to contribute to french localization

### ISSUE THREAD

**Issue by ManuSquall** [cncf/glossary#439]
### Details (optional)

Hello world, want to contribute to french localization, is there already an existing team please?

**Comment by iamNoah1** [comment]
Hi @ManuSquall, AFAIK there is no french team right now. If you want to help out, make sure to read the [contribution guide](https://glossary.cncf.io/contribute/), the [localization guide](https://github.com/cncf/glossary/blob/main/LOCALIZATION.md) and to join the #glossary-localization channel in the [cncf slack](https://cloud-native.slack.com). Thank you :)

**Comment by seokho-son** [comment]
Hi @ManuSquall 
We welcome new localization team :) If we find more volunteers we can initiate a French localization team by using this issue template https://github.com/cncf/glossary/issues/new?assignees=&labels=enhancement&template=l10n-initiation.md . Please take a look [localization guide](https://github.com/cncf/glossary/blob/main/LOCALIZATION.md).

I think you've found the answer, let me close this issue.

**Comment by ManuSquall** [comment]
> Hi @ManuSquall We welcome new localization team :) If we find more volunteers we can initiate a French localization team by using this issue template https://github.com/cncf/glossary/issues/new?assignees=&labels=enhancement&template=l10n-initiation.md . Please take a look [localization guide](https://github.com/cncf/glossary/blob/main/LOCALIZATION.md).
> 
> I think you've found the answer, let me close this issue.

Sure, thank you for the assistance @iamNoah1 , @seokho-son
