### ISSUE TITLE
"Inter-link" terms before going live w/ V1

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#44]
Once we consolidate the terms into one doc, we'll need to link terms that are mentioned in a definition and have their own definition. That way, readers can jump right to that term if they aren't familiar with it.

**Comment by IdealUsrname** [comment]
@CathPag Is now the time to go through and link as many definitions as possible for the completed terms?

**Comment by CathPag** [comment]
Unfortunately, the first version will be a PDF, @IdealUsrname. But we can still do this.
