### ISSUE TITLE
Add some installation hints for Hugo

### ISSUE THREAD

**Issue by iamNoah1** [cncf/glossary#442]
This may be a small one but on the readme, setting up a local instance assumes that hugo is installed. I think it would be nice to add some info about the prerequisite of hugo that has to be installed at least. Best case IMHO there should also be some info about how to install hugo.

**Comment by edsoncelio** [comment]
Great point! maybe we can have something like we have in Kubernetes docs: 
https://github.com/kubernetes/website#using-this-repository

**Comment by Anosh21** [comment]
Hey I would like to prepare the installation guide for Hugo.

**Comment by seokho-son** [comment]
@iamNoah1 are you interested in adding installation hints for Hugo ? or you hope to assign this task to another contributor ? :)

**Comment by iamNoah1** [comment]
There we have a volunteer :) 👍

**Comment by seokho-son** [comment]
@Anosh21 
Please go ahead. :)
