### ISSUE TITLE
[English]: Substrate

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#447]
### Details (optional)

Define the term substrate in the context of Kubernetes and modern dev platforms.

This issue was inspired by [this article](https://thenewstack.io/hello-kubernetes-operators-and-vendors-few-people-know-what-youre-selling/) which covered some terms that seem to be somewhat ambiguous.

**Comment by CathPag** [comment]
Jason, we spoke with Noah and this term feels a little too much in the weeds for the glossary. I'll close for one. If you have strong feeling about it, we can discuss and add again later.
