### ISSUE TITLE
To use relative path rather than absolute path in links

### ISSUE THREAD

**Issue by jihoon-seo** [cncf/glossary#449]
### Details (optional)

For example, in `content/en/virtual_machine.md`, the links to other glossary terms are set with absolute path:
- `[virtualization](https://glossary.cncf.io/virtualization/)`
- `[bare metal](https://glossary.cncf.io/bare_metal_machine/)`

But I suggest to use relative path rather than absolute path in links to the page of the same site (`glossary.cncf.io`).

```diff
-[virtualization](https://glossary.cncf.io/virtualization/)
+[virtualization](/virtualization/)

-[bare metal](https://glossary.cncf.io/bare_metal_machine/)
+[bare metal](/bare_metal_machine/)
```

Here is one of the reason:
If one PR modifies multiple files and some of those are linked with hyperlinks,
then it would be good to use relative path because:
- If relative paths are used, then someone can browse across multiple preview pages in that Netlify-built preview website.
- But if absolute paths are used, then when someone clicks that link, then he/she will get out of Netlify-built preview website, which is not appropriate.

PTAL folks! 😊

Edit: For now,
some files like [`continuous_delivery.md`](https://github.com/cncf/glossary/blob/main/content/en/continuous_delivery.md?plain=1) contain links with relative path,
and other files like [`virtual_machine.md`](https://github.com/cncf/glossary/blob/main/content/en/virtual_machine.md?plain=1) contain links with absolute path.

**Comment by seokho-son** [comment]
@jihoon-seo 
I agree with you ! :)
But I hope to reduce the impact of the modifications. I think this issue is worth to discuss among maintainers as well.

**Comment by JasonMorgan** [comment]
I totally agree, I think we should update the contributing guide as part of this. @jihoon-seo do you want to work it or is it open to be picked up?

**Comment by jihoon-seo** [comment]
@JasonMorgan It would be great if someone (other than me) handles this issue (update the contributing guide). 😊

**Comment by cjyabraham** [comment]
Is this still an open issue? When I search through the `/content/` folder I don't find any instances of `glossary.cncf.io`. Perhaps it is already resolved?

**Comment by seokho-son** [comment]
I think we can close this issue :)
Thanks @cjyabraham
