### ISSUE TITLE
Request to Initiate Chinese Localization Team

### ISSUE THREAD

**Issue by hanyuancheung** [cncf/glossary#451]
# This issue is to initiate a new l10n Team

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

I've recruited 4 volunteers (including myself), and I've read the localization guide. Also, I've created the slack channel which is [#glossary-localization-chinese](https://cloud-native.slack.com/archives/C033LHQCGS1)

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

For example, the two-letter code for Korean is `ko`.

 - Language name: Chinese
 - Language two-letter code: zh

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

- [hanyuancheung](https://github.com/hanyuancheung)
- [Rocksnake](https://github.com/Rocksnake)
- [Jacob953](https://github.com/Jacob953)
- [Submarinee](https://github.com/Submarinee)

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-zh`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by hanyuancheung** [comment]
Sorry to bother you guys, but I have no permission to create the origin branch for the Chinese language. 
Could you please help to do that so we can open PRs to finish the localization initiation? Great thanks for that~

**Comment by seokho-son** [comment]
Hello @hanyuancheung  ! I am one of the maintainers of CNCF Glossary. 
I'd like to inform you following progress.

- Added a new label for the language.
  `lang/zh` https://github.com/cncf/glossary/issues/labels
- Created a new development branch for the l10n. 
  https://github.com/cncf/glossary/tree/dev-zh
- Update permission to add l10n contents approvers.
  Working on it (It takes time to reach consensus on updated permission strategy among administrators)

ZH team can start site configuration (ex: PR #291) using the branch even though the team does not have a permission for approving PR yet.
You can refer https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#3-configuring-a-new-language to open a PR (base should be dev-zh) to configure a new language in a draft site.

**Comment by seokho-son** [comment]
@hanyuancheung 
Could you check, among the volunteers, who are interested in managing dev-zh branch ? (candidates for approver)

- [hanyuancheung](https://github.com/hanyuancheung)
- [Rocksnake](https://github.com/Rocksnake)
- [Jacob953](https://github.com/Jacob953)
- [Submarinee](https://github.com/Submarinee)

I recommend to take a look role and responsibility from 
 - PR: #432 
 - Contributor ladder: https://glossary.cncf.io/contributor-ladder/#localization-approvers

Could you share this message to candidates? :)

**Comment by hanyuancheung** [comment]
Yeah, I've shared this info above with them. I think I could take on the task of managing dev-zh branch. Thx

**Comment by hanyuancheung** [comment]
Hi @seokho-son , how's the initiation and PR going? Please help to review them, so we could continue our work~ Thanks lot.

**Comment by seokho-son** [comment]
@hanyuancheung I was waiting for agreements from the other candidates :)

**Comment by hanyuancheung** [comment]
@seokho-son Thanks for approving the initialization PR. I think this issue could also be closed.
