### ISSUE TITLE
[English]: Technical Debt

### ISSUE THREAD

**Issue by iamNoah1** [cncf/glossary#452]
### Details (optional)

Optional details

**Comment by gullapalli9482** [comment]
Could you explain more regarding the issue

**Comment by gullapalli9482** [comment]
@iamNoah1

**Comment by iamNoah1** [comment]
Hei @gullapalli9482 Thanks for reaching out. I am not quite sure what you want to hear TBH. Like with every other issue in this repo, this issue is a request to add a glossary definition about what technical debt is. If you want to contribute, please make sure to read the [contribution guide](https://glossary.cncf.io/contribute/) and join [this slack channel](https://cloud-native.slack.com/archives/C02TX20MQBB). Thanks ✌️

**Comment by unnati914** [comment]
can I work on this? or can help @gullapalli9482 to solve this

**Comment by gullapalli9482** [comment]
I understand what the issue is about now, thanks @iamNoah1 😃 . And thank you @unnati914 , it would be really great receiving tips from someone like you 😄 .

**Comment by gullapalli9482** [comment]
I would definitely like to work on this , do assign me this issue.

**Comment by gullapalli9482** [comment]
Can i make a pull request now

**Comment by iamNoah1** [comment]
There you go @gullapalli9482, please make sure to read the [contribution guide](https://glossary.cncf.io/contribute/) and join [this slack channel](https://cloud-native.slack.com/archives/C02TX20MQBB). ;)
