### ISSUE TITLE
[Korean]: Update 'virtual machine'

### ISSUE THREAD

**Issue by jihoon-seo** [cncf/glossary#462]
### Details (optional)

- #424 에서 `dev-ko` 브랜치에 'virtual machine' 항목이 추가되었는데,
- 그 이후에 #448 에서 영문 'virtual machine' 항목이 업데이트 되었습니다.
- 이에, `dev-ko` 브랜치의 'virtual machine' 항목을 업데이트하는 이슈를 오픈합니다. 😊

Edit: 새 이슈 대신, #379 의 댓글로 적는 것이 더 나으려나요 😅

**Comment by seokho-son** [comment]
@jihoon-seo 다양한 방법 모두 적절히 사용하면 될 것 같습니다. (큰 변경 사항이 아니라면 PR로 바로 열어도 될 것 같아요.)
현재는 작업하는 인원이 많이 않아서, 팀 내부에서 효율적인 방법으로 추진하면 될 것 같아요. :) 
기여자가 늘어난다면, 이슈 등 퍼블릭하게 작업하는 형태로 변경해 나갈 필요가 있습니다. (아직은 다소 먼 이야기이네요^^)

**Comment by seokho-son** [comment]
아직 dev-ko 의 영어 원문이 최신으로 업데이트 되지는 않았습니다.
PR #392 머지를 maintainer가 승인해줘야 하고, 
제가 maintainer이지만 해당 PR의 author 라서 직접 승인하는 것은 바람직하지 않고, 
잠시 기다려보고 있습니다. :)
