### ISSUE TITLE
L10n of "Feedback" section

### ISSUE THREAD

**Issue by jihoon-seo** [cncf/glossary#470]
### Details (optional)

In each term page, "Feedback" section is displayed in English, regardless of the language user has chosen.
[Example 1](https://deploy-preview-424--cncfglossary.netlify.app/ko/virtual_machine/#:~:text=Feedback,this%20page%20helpful%3F),
[Example 2](https://deploy-preview-468--cncfglossary.netlify.app/pt-br/devops/#:~:text=Feedback,this%20page%20helpful%3F):
![image](https://user-images.githubusercontent.com/46767780/155280495-42d0bb03-ecf6-4b9a-a4e9-d84d43a7b1f8.png)

---

Cf. [Kubernetes website](https://kubernetes.io/ko/docs/concepts/overview/what-is-kubernetes/#:~:text=피드백,페이지가%20도움이%20되었나요%3F):
![image](https://user-images.githubusercontent.com/46767780/155280736-92c73a92-3bc7-4f6e-8988-0729f1bda5d9.png)

**Comment by gullapalli9482** [comment]
I would like to work on this issue , can it be assigned to me

**Comment by gullapalli9482** [comment]
@jihoon-seo, I wasn't able to find the actual html file for the different languages , could you help me out by giving me the location of these files , so that I can make necessary changes .

**Comment by jihoon-seo** [comment]
@gullapalli9482 Let me add placeholders for this!

**Comment by gullapalli9482** [comment]
I understand it better now i think, so just to keeps things clear , the feedback section needs to get converted to whichever language it's opened in , am i getting it right?

**Comment by jihoon-seo** [comment]
@gullapalli9482 Please refer to the PR #519,
and you can add L10n to `dev-xx` that you want to (e.g. `dev-hi`) !

**Comment by Shivansh-yadav13** [comment]
hello @jihoon-seo, I'm a new contributor here can I contribute by working on this issue.

**Comment by jihoon-seo** [comment]
@Shivansh-yadav13 Please refer to the PR #519,
and you can add L10n to `dev-xx` that you want to (e.g. `dev-hi`) !
