### ISSUE TITLE
[New term] `Docker` for `En`

### ISSUE THREAD

**Issue by vish-han** [cncf/glossary#484]
#### What this term is about? (briefly)

- Docker is a set of platform as a service products that use OS-level virtualization to deliver software in packages called containers. 

#### Why this term needs to be added? (briefly) 
- Docker streamlines the development lifecycle by allowing developers to work in standardized environments using local containers which provide your applications and services. Containers are great for continuous integration and continuous delivery (CI/CD) workflows.

**Comment by CathPag** [comment]
Thanks, @vish-han. Docker is a product, not a technology category. If someone wants to know what Docker is, all they need to know is that it is a container and then look up container in the glossary. Does that make sense?

**Comment by CathPag** [comment]
Perfect :)
