### ISSUE TITLE
[German] localize 'Cloud Computing'

### ISSUE THREAD

**Issue by DaveVentura** [cncf/glossary#514]

**Comment by gdenn** [comment]
@DaveVentura I would like to take this Issue over.

**Comment by gdenn** [comment]
@iamNoah1  PR: https://github.com/cncf/glossary/pull/696

**Comment by gdenn** [comment]
made a new PR based on dev-de (and targetting dev-de)

**Comment by jihoon-seo** [comment]
German translation of the term "Cloud Computing" has been added to `dev-de` branch by #711,
and it will be visible on CNCF Glossary website when the commits in `dev-de` branch get merged into `main` branch.

I am hereby closing this issue. 😊
