### ISSUE TITLE
[German] localize 'Cloud Native Apps'

### ISSUE THREAD

**Issue by DaveVentura** [cncf/glossary#515]

**Comment by ohdle** [comment]
I would like to work on this issue.

**Comment by iamNoah1** [comment]
@ohdle oops, somehow this comment got lost :) Are you already in the slack channel?

**Comment by ohdle** [comment]
@iamNoah1 , I am in the slack channel but haven't been able to participate much recently and unfortunately currently no longer have time to work on this localization.

**Comment by iamNoah1** [comment]
kk @ohdle thanks for the info
