### ISSUE TITLE
[ English ]: Digital Certificates

### ISSUE THREAD

**Issue by root21cuib** [cncf/glossary#527]
Please can I contribute by adding this term to glossary ?

**Comment by iamNoah1** [comment]
there you go @root21cuib

**Comment by CathPag** [comment]
...and please don't forget to read the [style guide](https://glossary.cncf.io/style-guide/) before getting started — thank you! :)

**Comment by root21cuib** [comment]
@iamNoah1 and @CathPag thank you very much for the opportunity I will do my best

**Comment by iamNoah1** [comment]
#920
