### ISSUE TITLE
[English]: Nightly

### ISSUE THREAD

**Issue by akshatcoder-hash** [cncf/glossary#531]
### Details (optional)

Please can I contribute by adding this term to glossary ?

**Comment by jihoon-seo** [comment]
It would be appropriate for other maintainer(s) to assign this issue. 😊

**Comment by CathPag** [comment]
HI @akshatcoder-hash, we decided that this term shouldn't be part of the glossary as it's not a widely known one. I'll go ahead and close this issue. If you want to work on a term, feel free to check out the list of open issue. There are a ton of them.
