### ISSUE TITLE
[English]: How to contribute

### ISSUE THREAD

**Issue by kelvinparmar** [cncf/glossary#536]
### Details (optional)

Optional details

**Comment by CathPag** [comment]
We also already have a [how to contribute](https://glossary.cncf.io/contribute/). If you want to contribute but don't know how, the best way is to pick an existing issue. Please note that we are implementing a new way to vet issues (proposed terms) before they are approved for the Glossary. Not all current issues will be green-lighted. Feel free to pick one and wait until we decide and let you know.
