### ISSUE TITLE
[English]: Docker

### ISSUE THREAD

**Issue by peeyushguleria** [cncf/glossary#545]
### Details (optional)

Optional details

**Comment by peeyushguleria** [comment]
@CathPag may I work on it?

**Comment by iamNoah1** [comment]
Hi @peeyushguleria and welcome :)  … please note, that Docker is a product, not a technology or concept. The concept behind it is containers and for containers, we already have a definition (https://glossary.cncf.io/container/)

**Comment by peeyushguleria** [comment]
Thanks @iamNoah1 for correcting me , will keep that in mind in the future.
