### ISSUE TITLE
[New term] `Firewall` for `En`

### ISSUE THREAD

**Issue by akshatcoder-hash** [cncf/glossary#546]
#### What this term is about? (briefly)
 A firewall is a system present in Network Layer which protects a secure network from an unsecure network. It keeps out all unauthorized traffic.
#### Why this term needs to be added? (briefly) 
Firewall is one of the most common terms which people come across while working with a browser even when their connection fails. But at the same time, most do not know about it.

**Comment by akshatcoder-hash** [comment]
@seokho-son , is this assigned to me?
I am ready to contribute

**Comment by seokho-son** [comment]
Hi @akshatcoder-hash This issue is in `triage/awaiting` 
Maintainers are assessing the term if the term needs to be included in the CNCF Glossary. If the term is accepted, we will give the `triage/accepted` label to the issue and assign the task to you.

**Comment by CathPag** [comment]
@akshatcoder-hash, here you go @akshatcoder-hash. Please make sure to read the [style guide](https://glossary.cncf.io/style-guide/) before getting started.

**Comment by akshatcoder-hash** [comment]
@CathPag , please assign this issue to me so that I can contribute to this.

**Comment by CathPag** [comment]
Oops, sorry, forgot to do that. It's assigned now :)
