### ISSUE TITLE
Identity as a Service

### ISSUE THREAD

**Issue by karnatisrinivas** [cncf/glossary#547]
### Please describe why this term needs to be added

Identity as a service (IDaaS) is a cloud service model which helps in Identity and Access Management.

**Comment by iamNoah1** [comment]
@karnatisrinivas you described what Identity as a Service is, but not why this term needs to be added. Can please state, why you think that the terms is important for the cncf glossary?

**Comment by iamNoah1** [comment]
@karnatisrinivas friendly reminder

**Comment by karnatisrinivas** [comment]
IDaaS makes the accessing easier and more secured. I think Identity is an important asset for Applications. And In the age of increased Data thefts, most enterprises are opting for IDaaS Cloud service to secure their identity governance.  
I believe it is also an term that Cloud and Cloud native community needs to be aware of.

**Comment by JasonMorgan** [comment]
Lets close this and circle back once we have IDP defined.
