### ISSUE TITLE
[Spanish] localize 'Chaos Engineering'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#569]
Localize the `content/en/chaos_engineering.md` document to Spanish

**Comment by jthan24** [comment]
I will be work in this!! Can you assign me, please!

**Comment by jthan24** [comment]
In branch `origin/dev-es` doesn't exist a `chaos_engineering.md` file

**Comment by electrocucaracha** [comment]
@jthan24 that's the main idea, you have to create the `content/es/chaos_engineering.md` from `content/en/chaos_engineering.md` in a new PR based on `dev-es` branch
