### ISSUE TITLE
[Spanish] localize 'Containers as a Service'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#579]
Localize the `content/en/containers_as_a_service.md` document to Spanish

**Comment by RedwineOS** [comment]
Hello! Can you assign me this issue alongside https://github.com/cncf/glossary/issues/597 and https://github.com/cncf/glossary/issues/582 ? @electrocucaracha 

Thank you!

**Comment by electrocucaracha** [comment]
> Hello! Can you assign me this issue alongside #597 and #582 ? @electrocucaracha
> 
> Thank you!

@RedwineOS could you put any comment on them? The reason behind is that only in that way your name appears as option in the assignees list

**Comment by electrocucaracha** [comment]
@RedwineOS did you still working on this? Can I reassign this one?

**Comment by valeriahhdez** [comment]
Hello! I'd like to localize this concept
