### ISSUE TITLE
[Spanish] localize 'DevSecOps'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#599]
Localize the `content/en/devsecops.md` document to Spanish

**Comment by jthan24** [comment]
Me!! Please!!

**Comment by electrocucaracha** [comment]
@jthan24 Planeas trabajar en este issue? Puedo reasignarlo a alguien mas?

**Comment by valeriahhdez** [comment]
Hello! I'd like to help localize this concept
