### ISSUE TITLE
Create a Style Guide

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#6]
Build, publish, and maintain a style guide so that new folks can more easily contribute.

**Comment by JasonMorgan** [comment]
A couple items I'd like to see, the big one being a definitive template for entries and an explanation for every property. An example: I put in a category property for each entry but as of right now the only value I can think of is concept. Either we should have more categories or remove that property.

**Comment by IdealUsrname** [comment]
I've completed a basic outline for a style guide. Just waiting for the acceptance of #31, So I don't have to change the format again :)
