### ISSUE TITLE
[Spanish] localize 'Horizontal Scaling'

### ISSUE THREAD

**Issue by electrocucaracha** [cncf/glossary#604]
Localize the `content/en/horizontal_scaling.md` document to Spanish

**Comment by mdf-ido** [comment]
I can work on this

**Comment by electrocucaracha** [comment]
@mdf-ido voy a regresar este issue a pool, avísame en caso contrario

**Comment by marianogg9** [comment]
@electrocucaracha veo que ya esta hecha [la traduccion](https://github.com/cncf/glossary/blob/dev-es/content/es/horizontal-scaling.md) - podrias confirmarlo por favor?
