### ISSUE TITLE
[English] `Event-Driven Architecture`

### ISSUE THREAD

**Issue by jasonsmithio** [cncf/glossary#630]
#### What this term is about? (briefly)
-  Serverless Eventing is essentially binding event sources to their sinks in a declarative manner
#### Why this term needs to be added? (briefly) 
- With Knative being added to the CNCF, defining serverless eventing (or just eventing) would be of value as this is what Knative Eventing does

### 2. Checklist

- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by JasonMorgan** [comment]
@jasonsmithio would you be open to doing simply eventing, or ideally a more fundamental term around event driven architectures? As of right now the glossary is a little light on serverless terms and an entry that talks about the core concepts behind event driven architectures seems important.

Serverless Eventing seems too specific to be added at this time.

**Comment by jasonsmithio** [comment]
@JasonMorgan good point. `Serverless Eventing` and `Eventing` are similar yet different architectures. However, I agree on doing general and then doing specific definitions. I would be happy to make this an "Event Driven Architecture" definition first

**Comment by iamNoah1** [comment]
@jasonsmithio thanks for adding the proposal. I saw that you also created a PR already. In the future, I would like to ask for a little more patience before actually starting. A term has to be accepted for the glossary first (label `triage/accepted` indicated that). Also, make sure to mention the approvers/maintainers in the slack channel and only work on 1 term at a time :)

**Comment by jasonsmithio** [comment]
Howdy, 

Cool, a bit overzealous on my end.

**Comment by jihoon-seo** [comment]
This issue has been resolved by #637 and #976.
@jasonsmithio thank you for your hard work and devotion!
