### ISSUE TITLE
[English] `Pod`

### ISSUE THREAD

**Issue by dipankardas011** [cncf/glossary#638]
#### What this term is about? (briefly)
pod inside Kubernetes
#### Why this term needs to be added? (briefly) 
as pod term is not yet defined 

### 2. Checklist

- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by seokho-son** [comment]
Hi @dipankardas011 :) 
I am one of maintainers of the Glossary repository.

This issue is under `triage/awaiting`

> (Note)
> Maintainers will assign a label after assessment procedure.
> (from triage/awaiting to triage/accepted or triage/not accepted)
> 
> A contributor can be assigned to this issue after the issue get the triage/accepted label.
> The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

So, your PR #639
cannot be reviewed at this moment.

Please wait until the maintainers decides acceptance of this term.

**Comment by CathPag** [comment]
@dipankardas011, thanks for suggesting this term but I'm afraid it is too Kubernetes specific and belongs in the [Kubernetes Glossary](https://kubernetes.io/docs/reference/glossary/?fundamental=true). The cloud native Glossary should focus on broader cloud native terms.
