### ISSUE TITLE
cgroups and Namespaces

### ISSUE THREAD

**Issue by karnatisrinivas** [cncf/glossary#640]
#### What this term is about? (briefly)
Namespaces partitions kernel resources such that one set of processes sees one set of resources while another set of processes sees a different set of resources.

Cgroups allow you to allocate resources — such as CPU time, system memory, network bandwidth, or combinations of these resources — among user-defined groups of tasks (processes) running on a system.

#### Why this term needs to be added? (briefly) 
-
Both Namespaces and Cgroups are the underlying technologies of Containers. 

### 2. Checklist

- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by vish-han** [comment]
I want to work on this issue if the maintainers can assign me the task🚀

**Comment by karnatisrinivas** [comment]
Hello @vish-han , I opened this issue for new term so that i can work on this. Thanks

**Comment by CathPag** [comment]
Hi @karnatisrinivas, thanks for suggesting these terms but I'm afraid they are too Kubernetes specific and belong in the [Kubernetes Glossary](https://kubernetes.io/docs/reference/glossary/?fundamental=true). The cloud native Glossary should focus on broader cloud native terms.
