### ISSUE TITLE
[bn] Localize the style guide for Bengali Documentation

### ISSUE THREAD

**Issue by mitul3737** [cncf/glossary#660]
The file `content/bn/style-guide/_index.md` under `dev-bn` needs to be Localized
Tracking issue: #410

**Comment by ikramulkayes** [comment]
\assign

**Comment by mitul3737** [comment]
@ikramulkayes  any update on the PR?

**Comment by mitul3737** [comment]
Do follow https://github.com/cncf/glossary/blob/dev-hi/content/hi/style-guide/_index.md while localizing.

**Comment by ikramulkayes** [comment]
\unassign

**Comment by mitul3737** [comment]
This issue has been resolved #750
