### ISSUE TITLE
[ Typo] in glossary/content/en/contribute/_index.md 

### ISSUE THREAD

**Issue by jaynarayan20** [cncf/glossary#668]
Working on an existing issue ->in  e.g first good issue should be good first issue according to label.
![typo](https://user-images.githubusercontent.com/54346106/160844811-f3807359-dde5-47e2-9c2d-60ad1806528c.jpg)

**Comment by jaynarayan20** [comment]
i would like to work  on this if maintainers thinks that this issue is valid.

**Comment by iamNoah1** [comment]
Thanks @jaynarayan20, valid point

**Comment by jaynarayan20** [comment]
i've worked and fixed this

**Comment by jaynarayan20** [comment]
can i create a pull request

**Comment by jihoon-seo** [comment]
@jaynarayan20 I assigned you, and updated labels.
Please open a PR. 😊

**Comment by jaynarayan20** [comment]
hey @seokho-son  and @iamNoah1  also found another typo on the same page while goinng through it.
![typo2](https://user-images.githubusercontent.com/54346106/161072793-52e1a83d-037d-4f52-88a5-58cb822465b5.jpg)
as you can see in (there are three ways to contribute ) mentioned but following that are actually 4 points.
so is this a valid issue?

**Comment by seokho-son** [comment]
Hi @jaynarayan20 :)
If typos or bugs are obvious and modifications are simple, you don't have to open Issue. You can open a PR directly. :) The PR will be reviewed anyway. (If suggestion is not simple, I recommend to open an issue and get agreements)

**Comment by jaynarayan20** [comment]
@seokho-son so is this a valid issue? can i work on it?

**Comment by CathPag** [comment]
Yes, for quick updates like this, no issue is required. Issues are only for new terms or major changes. Feel free to submit a PR directly :)

**Comment by CathPag** [comment]
Great! I'll close this issue since it isn't necessary
