### ISSUE TITLE
[New term] `Container Orchestrator`

### ISSUE THREAD

**Issue by gdenn** [cncf/glossary#701]
#### What this term is about? (briefly)

"Container Orchestrator"

#### Why this term needs to be added? (briefly) 

Container Orchestrators like Kubernetes are key technologies in cloud-native app development. We rely on container orchestrators to deploy and maintain (containerized) micro-service architectures with a reasonable effort.

Yet many have troubles understanding where Platforms like Kubernetes or Swarm fit into the classical three-layer concept (IaaS, PaaS, SaaS) of Cloud Computing. 

We should not only explain what problem container orchestrators solve but also mention the difference between multi-vm container orchestrators like K8s and Swarm and single host orchestrators like Docker Compose.

### 2. Checklist

- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by iamNoah1** [comment]
Thanks for the proposal @gdenn. Considering the existing term definitions for CaaS and Kubernetes, didn't we explain what problem container orchestration is solving already? Even though implicitly. Regarding the difference between multi-vm and single host container solutions, I think it does not matter in order to understand what it is about. Also we are trying to avoid talking about concrete products like Docker Swarm or Docker Compose. 

Would it be an acceptable suggestion to try to sharpen the existing terms in order to make your point, without the need for introducing a new term? i.e. making it more clear in the CaaS term definition, where it fits in the classical three layer concept.

**Comment by gdenn** [comment]
@iamNoah1 you are right, having an entry for Kubernetes and Container Orchestrators is like explaining the same thing twice. I guess it is also difficult to explain K8s without explaining what problem it solves (which is the orchestration of containers).

Still, I think it would be nice to explicitly mention in the Kubernetes definition that K8s is a container orchestrator. That makes it clear to the reader that k8s implements that concept. It would also deliver the "Kubernetes" definition as a result when I search for  "container orchestration" (people might stumble across the "container orchestrator" term on the internet and type it into the CNCF glossary search). 

The CaaS definition almost mentions container orchestrators already 😅 
_...CaaS providers offer a framework or orchestration platform..._ 

But the term "orchestration platform" may confuse some people. We may put "container orchestrator" in parenthesis behind or (even better) write _...or orchestration platforms like Kubernetes..._ and link the Kubernetes definition.

I think it would be really helpful if we mention where the CaaS layer fits into the IaaS, PaaS & SaaS layer model. The three layers are often the first thing people find when they look for "Cloud Computing" on the internet.

**Comment by iamNoah1** [comment]
> @iamNoah1 you are right, having an entry for Kubernetes and Container Orchestrators is like explaining the same thing twice. I guess it is also difficult to explain K8s without explaining what problem it solves (which is the orchestration of containers).
> 
> Still, I think it would be nice to explicitly mention in the Kubernetes definition that K8s is a container orchestrator. That makes it clear to the reader that k8s implements that concept. It would also deliver the "Kubernetes" definition as a result when I search for "container orchestration" (people might stumble across the "container orchestrator" term on the internet and type it into the CNCF glossary search).
> 

agreed. 

> The CaaS definition almost mentions container orchestrators already 😅 _...CaaS providers offer a framework or orchestration platform..._
> 
> But the term "orchestration platform" may confuse some people. We may put "container orchestrator" in parenthesis behind or (even better) write _...or orchestration platforms like Kubernetes..._ and link the Kubernetes definition.
> 
> I think it would be really helpful if we mention where the CaaS layer fits into the IaaS, PaaS & SaaS layer model. The three layers are often the first thing people find when they look for "Cloud Computing" on the internet.

That's what I meant as I said sharpening the existing terms :). So we would need two follow-up issues, one for the Kubernetes term, explicitly stating that it is a container orchestrator, one for updating CaaS in regards to its connection to k8s, and stating where it fits in the 3 layer model. Right?

**Comment by gdenn** [comment]
Closed in favour of #707 & #706
