### ISSUE TITLE
[Update term] `Kubernetes` for `En`

### ISSUE THREAD

**Issue by gdenn** [cncf/glossary#707]
#### Why this term needs to be updated? (briefly) 

As discussed with @iamNoah1  in #701:

We want to explicitly mention that k8s is a container orchestrator. Some people might encounter the term "container orchestrator" in the www. Searching for "container orchestrator" in the CNCF glossary would show Kubernetes as a search result (once we tweaked the definition).

**Comment by gdenn** [comment]
@iamNoah1 could make the changes herefore too if you aprove.

**Comment by gdenn** [comment]
PR https://github.com/cncf/glossary/pull/719

**Comment by CathPag** [comment]
Hi @gdenn, no need to create an issue for an update...unless it's a huge change maybe. Next time, feel free to go ahead and update the term directly :)
