### ISSUE TITLE
[hi] [new term] DevSecOps for Hindi

### ISSUE THREAD

**Issue by SahityaGupta25** [cncf/glossary#727]
#### What this term is about? (briefly)
-  DevSecOps stands for development, security, and operations. It's an approach to culture, automation, and platform design that integrates security as a shared responsibility throughout the entire IT lifecycle
#### Why this term needs to be added? (briefly) 
- This term to be Entered in Hindi Language because I don't find it in hindi. 
#### Languages that use this term? (briefly)
-

**Comment by jihoon-seo** [comment]
@SahityaGupta25 We can assign you one term at a time, so please choose the term that you want to translate for this time, between [`DevSecOps`](https://github.com/cncf/glossary/issues/727) and [`Microservices`](https://github.com/cncf/glossary/issues/728). 😊

**Comment by SahityaGupta25** [comment]
DevSecOps ready & in few hours I will merge it.

**Comment by anubha-v-ardhan** [comment]
Closing this for #1183
