### ISSUE TITLE
[hi] Translate `Microservices` into `Hindi`

### ISSUE THREAD

**Issue by Shivansh-yadav13** [cncf/glossary#728]
- Microservices localization for Hindi needs to be added.
- https://glossary.cncf.io/microservices/
- https://glossary.cncf.io/hi/microservices/

**Comment by SahityaGupta25** [comment]
@Shivansh-yadav13 are you working on this issue??

**Comment by Shivansh-yadav13** [comment]
@SahityaGupta25 not working on it rn you can make a pr 🙂

**Comment by SahityaGupta25** [comment]
Sure Let me  Solve that First Issue after than I will work on this.

**Comment by SahityaGupta25** [comment]
**Thank You @anubha-v-ardhan  for Assigning me this Task.**

**Comment by Garima-Negi** [comment]
Re-assigning this issue due to inactivity

**Comment by sayantani11** [comment]
Done in #1572
