### ISSUE TITLE
Canary Deployment - improvement in "CNCF glossary" definition

### ISSUE THREAD

**Issue by antaloala** [cncf/glossary#736]
I think [current definition of "Canary Deployment" in CNCF glossary](https://glossary.cncf.io/canary_deployment/) is not totally right due to the current starting sentence:

``Canary deployments is a deployment strategy that starts with two environments: one with live traffic and the other containing the updated code without live traffic``

That sentence could be understood as starting with two ``complete`` environments for the two versions (the current/stable one and the canary one) but it is not like that (this would be too costly from a footprint point of view). In a Canary process you have a whole/complete environment for the current/stable version and a minimum starting one for the canary version and, as more real traffic is moved to the canary version, more workload instances of the canary version are needed and less workload instances of the current/stable version are run ... and so, from a footprint point of view, it is always required the same amount of cloud resources.
(this is actually as CNCF Argo-rollouts and CNCF flagger projects implement a canary upgrade)

What then about replacing that first sentence as follows:

``Canary deployments is a deployment strategy that starts with two environments: one with live traffic and the other containing the updated code without receiving (yet) traffic and for which a minimum amount of starting cloud resources is required``

At the end of the first paragraph it could also be added this sentence:

``During a canary upgrade process the amount of required cloud resources (compute, memory and storage) from the stable plus canary environments is kept (almost) the same as it was before starting it``

**Comment by starlightknown** [comment]
I would like to work on this issue

**Comment by seokho-son** [comment]
Hi @antaloala Thanks for your interest in the CNCF Glossary Project!
Your proposal is being considered by admins and glossary approvers :) 
Please wait for triage.

Hello @starlightknown :)
I assume the author of this issue (@antaloala) is willing to work on this issue. 
If not, you can be assigned. Anyway we need to triage this issue. :)

**Comment by JasonMorgan** [comment]
Looks good!

**Comment by antaloala** [comment]
Thanks @JasonMorgan and @seokho-son for putting hands on this (and sorry a lot for being silent).

**Comment by CathPag** [comment]
Agreed. I think the "what it is" section is pretty good, actually. I'd leave it as is too.

**Comment by antaloala** [comment]
IMO (influenced by flagger and argo-rollouts implementations) there are three relevant things you must 'have' for an in-service software upgrade procedure to be considered a Canary one:

1. Usted traffic during the upgrade procedure (routed to current/stable workloads and to new/canary workloads) is production traffic

2. Total amount of (cloud) resources is kept (more or less) constant

3. There are one or several 'validation steps' where decided if canary upgrade process continues (finally promoting the canary version to become the stable one) or if it is aborted (as new canary version does not fulfill the expectations).

In current definition the second point is missing.

**Comment by iamNoah1** [comment]
> IMO (influenced by flagger and argo-rollouts implementations) there are three relevant things you must 'have' for an in-service software upgrade procedure to be considered a Canary one:
> 
> 1. Handle taffic during the upgrade procedure to validate the canary/new sw instances (for which a well-known amount of that traffic is being routed to new/canary instances and the rest to old/stable workloads instances, changing the percentages as the canary upgrade progress) is production traffic
> 2. Total amount of (cloud) resources (required for new/canary workload instances + old/stable ones) is kept (more or less) constant across the whole canary upgrade execution.
> 3. There are several 'validation steps' where decided if canary upgrade process should continue (finally promoting the canary version to become the stable one) or the whole canary upgrade is to aborted (as the new/canary version does not fulfill the expectations).
> 
> In current definition the second point is missing.

I feel like I said something like this before. While your comments might be true, the CNCF Glossary focuses on making it easy especially for non-technical folks to understand complex cloud native topics. IMO the amount of technical detail you suggest is not necessarily required to understand what a canary deployment is.

**Comment by CathPag** [comment]
@antaloala, please refer to the "[minimal viable definition](https://glossary.cncf.io/style-guide/#minimal-viable-definition)" section in our style guide. As Noah stated, your points are valid but do introduce unnecessary complexity for our purpose. So, while correct, I'll close this PR to keep our simplicity focus. 

I hope it makes more sense now that you got the chance to review the style guide. We truly appreciate your contribution and hope you can contribute to another term now that we have clarified the Glossary's goals.

**Comment by antaloala** [comment]
Thanks for your time on this. Yes, according to the style guide to follow (sorry, I did not know about it), I agree that adding all these details would not work ... but, at the same time, this missing information precludes to use/refer to the CNCF glossary definitions to clarify if this or that upgrade procedure can be entitled or not as a Canary upgrade.

Would it be possible to add, in a coming future, some kind of 'extended definition' link to each term so, only when clicked,  extend the definition text (adding these additional but relevant details, only for those terms that could require it)?
