### ISSUE TITLE
[hi] Translate `Blue Green Deployment` into `Hindi`

### ISSUE THREAD

**Issue by starlightknown** [cncf/glossary#741]
- Blue Green Deployment localization for Hindi needs to be added.
- https://glossary.cncf.io/blue_green_deployment/

**Comment by Shivansh-yadav13** [comment]
hello @starlightknown, I have created a PR https://github.com/cncf/glossary/pull/632 can you review it.

**Comment by anubha-v-ardhan** [comment]
@starlightknown Sorry but we'll have to close this PR as this term is already localized and under review on #632. To avoid conflicts like this, please always make an issue first and wait for maintainers triage before starting to work
