### ISSUE TITLE
 [hi] Translate `Firewall` into `Hindi`

### ISSUE THREAD

**Issue by starlightknown** [cncf/glossary#764]
localization of `Firewall` into Hindi 
- https://glossary.cncf.io/firewall/

**Comment by abh139** [comment]
I wanna work on this

**Comment by starlightknown** [comment]
@abh139 @Shivansh-yadav13 yep I'll be working on it

**Comment by anubha-v-ardhan** [comment]
Thankyou @starlightknown. I've assigned you :)

**Comment by AniketNS** [comment]
Hi @jihoon-seo, is this issue still open. If yes, then please assign it to me. I'd love to work on it.
