### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by cjyabraham** [cncf/glossary#767]
Activate the tagging feature in docsy. Ideally these tags will go on top of the categories.

**Comment by cjyabraham** [comment]
Here are the design options from Gareth:
<img width="971" alt="glossary1" src="https://user-images.githubusercontent.com/463160/164459707-ff0aaf93-81dc-4ef4-a5ae-a715eb06363c.png">
<img width="971" alt="glossary2" src="https://user-images.githubusercontent.com/463160/164459733-f197f1dc-6ca9-489a-85e0-e6e189e09f11.png">

**Comment by CathPag** [comment]
@cjyabraham, I updated the order of the tags. Fundamentals and Advanced should come first, then Technology, Property or Concept, and then the rest — thank you!! 


1. Fundamentals
2. Advanced
3. Technology
4. Property
5. Concept
6. Application
7. Infrastructure
8. Architecture
9. Networking
10. Data
11. Security
12. Platform
13. Analytics
14. Methodology

**Comment by CathPag** [comment]
> Here are the design options from Gareth: <img alt="glossary1" width="971" src="https://user-images.githubusercontent.com/463160/164459707-ff0aaf93-81dc-4ef4-a5ae-a715eb06363c.png"> <img alt="glossary2" width="971" src="https://user-images.githubusercontent.com/463160/164459733-f197f1dc-6ca9-489a-85e0-e6e189e09f11.png">

I would 100% go with pink. It needs to pop so people see it.
