### ISSUE TITLE
Update Chinese lang ID: `zh` → `zh-cn`

### ISSUE THREAD

**Issue by jihoon-seo** [cncf/glossary#769]
Recently, Docsy has renamed language 'zh' to 'zh-cn'.
(Ref: https://github.com/google/docsy/pull/832)

And after [updating Docsy](https://github.com/kubernetes/website/pull/32906) used by [kubernetes/website repo](https://github.com/kubernetes/website),
this causes some issues (like [this](https://github.com/kubernetes/website/issues/33002), and so on..).

To resolve this, [Qiming Teng](https://github.com/tengqm), an active English & Chinese approver in kubernetes/website repo, suggested a solution: 
**update the Chinese language identifier from `zh` to `zh-cn`**,
causing everything under `https//kubernetes.io/zh/*` to be moved to `https//kubernetes.io/zh-cn/*` .
- https://github.com/kubernetes/website/pull/33050
- https://github.com/kubernetes/website/pull/33051

It is likely that we update our Docsy version some time or other, and that we will encounter this issue too.

So I suggest to update the Chinese language identifier from `zh` to `zh-cn` in CNCF Glossary project, before `dev-zh` goes live,
because updating **before** `dev-zh` going live will be better than updating **after** `dev-zh` going live.
(Which means that Chinese contents will be live in `https://glossary.cncf.io/zh-cn/`, not `https://glossary.cncf.io/zh/`.)

How about your thoughts,
Chinese approvers (@hanyuancheung @Jacob953 @Rocksnake @Submarinee) and
maintainers and English approvers (@cjyabraham @CathPag @jasonmorgan @seokho-son @iamNoah1) ? 😊

[Refs]
- https://github.com/google/docsy/issues/732
- https://github.com/google/docsy/pull/712
- https://github.com/google/docsy/pull/826
- https://github.com/google/docsy/pull/832
- https://github.com/kubernetes/website/issues/33002

**Comment by seokho-son** [comment]
Hi @cjyabraham 
Do you have a plan to update Docsy theme version ? :)
If we update it, we need to apply the issue raised by @jihoon-seo

**Comment by cjyabraham** [comment]
I'm not planning it, however, it makes sense to update it if we want to take advantage of any updates and new features. So I think this issue is a good idea to get ahead of the directory change.

**Comment by hanyuancheung** [comment]
On behalf of the Chinese team, I agree to change the branch name as suggested!

**Comment by jihoon-seo** [comment]
Resolved by #869.
