### ISSUE TITLE
[hi] Localize `Cluster.md` in `Hindi`

### ISSUE THREAD

**Issue by octonawish-akcodes** [cncf/glossary#771]
Localization of **Cluster.md** file in Hindi
[cncf/glossary/blob/main/content/en/cluster.md](url)

**Comment by abh139** [comment]
Okay

**Comment by Garima-Negi** [comment]
Hi @octonawish-akcodes , are you still working on this issue? 
If yes, do you have a placeholder PR?
If no, should we re-assign it to another contributor?

**Comment by octonawish-akcodes** [comment]
Please assign to someone else af there are compatibility issues arising in my local system  It is taking time for resolvement

**Comment by bishal7679** [comment]
@anubha-v-ardhan Could you assign me this issue?
I would to work on it

**Comment by anubha-v-ardhan** [comment]
Thank you @bishal7679 :)

**Comment by AniketNS** [comment]
Is this issue still Open? If yes then please assign it to me. I'd like to work on it.

**Comment by AniketNS** [comment]
Can You assign this issue to me @Garima-Negi

**Comment by Omkar0114** [comment]
This issue is resolved @AniketNS by merging PR #1227. We can close this issue @anubha-v-ardhan @Garima-Negi

**Comment by Garima-Negi** [comment]
Thank you @Omkar0114 and @AniketNS !
