### ISSUE TITLE
Add "Related terms" section to template

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#792]
If a term is highly related to others, we should add a "Please also refer to" section. See [Continuous Delivery](https://glossary.cncf.io/continuous_delivery/) as an example. That section should be part of the template as "if applicable."

**Comment by Stuti-mishra** [comment]
I'd like to work on this. Kindly assign me this.

**Comment by CathPag** [comment]
Sure, here you go, @Stuti-mishra. We should actually call it "Related terms" instead. Could you also update the terms that have that implemented? >> CI/CD and vertical/horizontal scaling/autoscaling.

**Comment by Stuti-mishra** [comment]
> Sure, here you go, @Stuti-mishra. We should actually call it "Related terms" instead. Could you also update the terms that have that implemented? >> CI/CD and vertical/horizontal scaling/autoscaling.

Yep! I'll update the terms that have already implemented it

**Comment by Stuti-mishra** [comment]
Kindly ignore the above pr it was redundant, I've merged the 2 patches in #808 itself
