### ISSUE TITLE
[Portuguese] Localize 'Kubernetes'

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#813]
Localize https://glossary.cncf.io/kubernetes/

**Comment by SpawW** [comment]
I would be happy to work on this issue, I'm a native portuguese speaker.

**Comment by edsoncelio** [comment]
> I would be happy to work on this issue, I'm a native portuguese speaker.

Hey @SpawW! Thanks, I'll assign it to you - feel free to ask for help at your slack channel :D :D
