### ISSUE TITLE
[Portuguese] Localize 'Chaos Engineering'

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#814]
Localize https://glossary.cncf.io/chaos-engineering/

**Comment by MrErlison** [comment]
New local https://glossary.cncf.io/chaos-engineering/

**Comment by fsegredo** [comment]
@edsoncelio could you please assign this issue to me?

Thanks

**Comment by rafaelmnatali** [comment]
@edsoncelio @MrErlison if this still needs to be done, please assign it to me. 

Thanks!
