### ISSUE TITLE
[Portuguese] Localize 'Container as a Service'

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#815]
Localize https://glossary.cncf.io/containers_as_a_service/

**Comment by MrErlison** [comment]
Localize [https://glossary.cncf.io/containers-as-a-service/](https://glossary.cncf.io/containers-as-a-service/)

**Comment by edsoncelio** [comment]
This term was deprecated - add the following information to the head:
```
status: Deprecated
tags: ["descontinuado", "", ""]
```

**Comment by MrErlison** [comment]
Deprecated
