### ISSUE TITLE
[Portuguese] Localize 'Continous Deployment'

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#816]
Localize https://glossary.cncf.io/continuous-deployment/

**Comment by rafaelmnatali** [comment]
Hi @edsoncelio, I would like to work in this issue. To clarify, I believe that the correct URL is <https://glossary.cncf.io/continuous-deployment/>, right?

**Comment by edsoncelio** [comment]
> https://glossary.cncf.io/continuous-deployment/

Hi @rafaelmnatali! You're right; I'm fixing it now (This issue was created before the naming change).
I'll assign it to you - If you need help, let us know.
