### ISSUE TITLE
[Portuguese] Localize 'Distributed Systems'

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#821]
Localize https://glossary.cncf.io/distributed-systems/

**Comment by rafaelmnatali** [comment]
Hi @edsoncelio, could I start working on this one. 

FYI, the new location is <https://glossary.cncf.io/distributed-systems/>

**Comment by edsoncelio** [comment]
> Hi @edsoncelio, could I start working on this one.
> 
> FYI, the new location is https://glossary.cncf.io/distributed-systems/
> 
> thanks

Sure! Assigned to you :)
