### ISSUE TITLE
[Portuguese] Localize 'Infrastructure as a Code'

### ISSUE THREAD

**Issue by edsoncelio** [cncf/glossary#828]
Localize https://glossary.cncf.io/infrastructure_as_code/

**Comment by MrErlison** [comment]
Hi @edsoncelio assign it to me.

**Comment by MrErlison** [comment]
> Localize https://glossary.cncf.io/infrastructure_as_code/

New local https://glossary.cncf.io/infrastructure-as-code/

**Comment by MrErlison** [comment]
PR #1086 created.
