### ISSUE TITLE
[hi] Localize `Database as a Service (DBaaS)`

### ISSUE THREAD

**Issue by Shivansh-yadav13** [cncf/glossary#894]
- https://glossary.cncf.io/database_as_a_service/

**Comment by sumit-158** [comment]
Hi , @Shivansh-yadav13 can I work on this if yes, could you let me know what exactly I have to do?

**Comment by Shivansh-yadav13** [comment]
@sumit-158 are you working on it?

**Comment by sumit-158** [comment]
@Garima-Negi [Pr ](https://github.com/cncf/glossary/pull/934)is already up, u just have to review it
