### ISSUE TITLE
Review PDF for Kubecon

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#91]

**Comment by caniszczyk** [comment]
[cncf-glossary-v3.pdf](https://github.com/cncf/glossary/files/6409828/cncf-glossary-v3.pdf)

FYI my feedback here is that we need an acknowledgements section and add that all documentation is licensed under CC-BY 4.0 at the end of the glossary.

**Comment by tomkerkhove** [comment]
Nice document 👌
