### ISSUE TITLE
Initiate French Localization Team

### ISSUE THREAD

**Issue by huats** [cncf/glossary#915]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

 - Language name : French
 - Language two-letter code : fr

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

- [A]  Christophe Sauthier (@huats )
- [A] Flavien Hardy ( @fydrah )
- [A] Ludovic Logiou ( @Krast76 )

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-ko`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by seokho-son** [comment]
Hi @huats 
I created [#glossary-localization-french](https://cloud-native.slack.com/archives/C03JHQ02FCH) channel in the CNCF Slack.
Please join and invite volunteers :)

**Comment by seokho-son** [comment]
Regarding `dev-fr` development branch, 
I can create `dev-fr` branch immediately. But, since we expect a lot of changes in `main` branch soon, we'd better to postpone create `dev-fr` until #922 . So, please wait :)

In the meantime, you can discuss how to operate French localization team :)

**Comment by seokho-son** [comment]
`lang/fr` is the label for French ! ;)

https://github.com/cncf/glossary/labels/lang%2Ffr

**Comment by huats** [comment]
Terrific. Thanks a lot for your help and actions.
We will then wait for the creation of the  `dev-fr` branch.

**Comment by silopolis** [comment]
> Hi @huats I created [#glossary-localization-french](https://cloud-native.slack.com/archives/C03JHQ02FCH) channel in the CNCF Slack. Please join and invite volunteers :)

Good evening Natives :)
I would love to join the (glossary) French translation team as a first step into CNCF projects t9n path... Would you please send me an invitation for the Slack channel?
Looking forward to discussing and hopefully collaborating with the team :)

**Comment by Krast76** [comment]
Hi @silopolis,

You do not need to be invited, you have to register there : https://communityinviter.com/apps/cloud-native/cncf (I hope this is the right link)

**Comment by silopolis** [comment]
Hey @Krast76 🙂

I can't create an account because gmail.com is not in the list of allowed domains 😢

**Comment by silopolis** [comment]
> You do not need to be invited, you have to register there :
> https://communityinviter.com/apps/cloud-native/cncf (I hope this is the
> right link)
>

Yey, that's one!
Invitation request sent...
Thanks a lot @Krast76 👍🙏
