### ISSUE TITLE
[New term] `Policy as Code`

### ISSUE THREAD

**Issue by anderseknert** [cncf/glossary#918]
#### What this term is about? (briefly)
Policy as Code

#### Why this term needs to be added? (briefly) 
Policy is an important component of cloud-native applications, and having it defined in the same declarative manner that describes the other components required by the application (e.g. infrastructure, resource manifests, etc) provides a number of benefits that I think would be good if we expanded on here.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by CathPag** [comment]
Apologies for the delay, @anderseknert. This term was accepted. Please let me know if you still want to work on it and I'll assign it to you.

**Comment by anderseknert** [comment]
No worries @CathPag 🙂 I'd be happy to work on it later this week, so please assign it to me!

**Comment by CathPag** [comment]
Hi @anderseknert, just following up on this :)

**Comment by anderseknert** [comment]
Oh, looks like someone beat me to it? https://glossary.cncf.io/policy-as-code/

**Comment by CathPag** [comment]
Hmm...I don't remember seeing this, and the two contributors on the GitHub repo don't really contribute content (very strange). It is listed as "feedback appreciated," which means it shouldn't appear on the Glossary website (will need to look into that). It also means that it has not been officially accepted yet. 

Anything you'd add or change?

**Comment by anderseknert** [comment]
@CathPag sorry for the delay! Looks OK to me :)

**Comment by CathPag** [comment]
Ok, great! Just added this as a term to be reviewed by the maintainers. So definition looks good on your end? Any other term you'd like to work on by any chance?
