### ISSUE TITLE
[bn] Update header text

### ISSUE THREAD

**Issue by jihoon-seo** [cncf/glossary#937]
Replace

```diff
-## এটি যেই সমস্যাটি দৃষ্টিপাত করে
+## এটা যেসব সমস্যাতে দৃষ্টিপাত করে

-## এটা যেসব সমস্যাতে ফোকাস করে
+## এটা যেসব সমস্যাতে দৃষ্টিপাত করে
```

in
- `content/bn/application-programming-interface.md` (ref: https://github.com/cncf/glossary/commit/4e4b8811f022b1b718d0a3a473812c08dc658a58)
- `content/bn/cloud-native-tech.md` (ref: https://github.com/cncf/glossary/commit/dbd2aa9f6485644bd8a90e1a45257f1d581fc06f)

Note:
- It would be great to contain changes for those 2 files in **one single commit**, not in multiple commits.
  It also applies to all the BN PRs.
- To BN L10n team, I recommend to use the merge method "**Squash and merge**" when merging BN PRs.

**Comment by devsachinsharma** [comment]
Can i please take up this issue?

**Comment by jihoon-seo** [comment]
@devsachinsharma please go ahead!
And please make sure that you branch off from & set merge target as the `dev-bn` branch, not `main` branch. 😊

**Comment by devsachinsharma** [comment]
Ok sure.Thank you

**Comment by devsachinsharma** [comment]
Hey @jihoon-seo i'm a beginner at contributing and i have no idea what i did wrong can you please guide me.Thank you.

**Comment by devsachinsharma** [comment]
I think i did all the changes. Can you please elaborate what I need to do? Thank you.

**Comment by sarkartanmay393** [comment]
Hello @devsachinsharma and @jihoon-seo, is this issue still present?  I would like to help.

**Comment by mitul3737** [comment]
@sarkartanmay393  You can work with the `content/bn/devops` file

**Comment by sarkartanmay393** [comment]
> @sarkartanmay393 You can work with the `content/bn/devops` file

Hello, @mitul3737 I have created a PR with header texts fixed in `devops` and `api` file.

**Comment by sarkartanmay393** [comment]
Hello @jihoon-seo, This issue is closed, isn't it?

**Comment by mitul3737** [comment]
Yes, @sarkartanmay393 but you can surely contribute from this Tracking issue #410
