### ISSUE TITLE
[zh] Localize 'observability' 

### ISSUE THREAD

**Issue by Superskyyy** [cncf/glossary#946]
In many cases, we translate observability as "可观测性", but I see that on the existing terms pages (e.g. [here](https://glossary.cncf.io/zh-cn/cloud-native-apps/)) we referred to the observability term as "可观察性 ", which do you guys prefer? 

I personally prefer "可观测性“ as Apache SkyWalking & Open Telemetry CN-docs both prefer this translation (Otel docs got some inconsistency), and I believe its genearlly more popular. To address this I suggest adding a note to indicate the alternative name so newcomers to the field will not get confused when seeing both terms.

I will take this issue.

**Comment by Anddd7** [comment]
"可观测性" +1

**Comment by Jacob953** [comment]
Plz go ahead. ;)
