### ISSUE TITLE
[zh] Localize 'self_healing'

### ISSUE THREAD

**Issue by Jacob953** [cncf/glossary#957]
- [ ] Localize the content/en/self_healing.md to content/zh-cn/ in dev-zh.

**Comment by EmilyXinyi** [comment]
I'd like to be assigned to work on this issue if that's ok!

**Comment by Jacob953** [comment]
@EmilyXinyi Hi, plz go ahead ;)

**Comment by EmilyXinyi** [comment]
@Jacob953 thanks! Could you please assign me to this issue? I don't see a self-assigning button :)

**Comment by EmilyXinyi** [comment]
I think this term is already localized by this PR #1525 but was never linked to this issue. 
@Jacob953 Could you please take a look? 

Note: this term is only localized on the dev-zh branch but not on main, so I am guessing that dev-tw and main haven't merged yet.

**Comment by Jacob953** [comment]
Sorry about that, I'll correct the status of this progress.

And yep, the dev-zh branch does only focus on content of Chinese(Simplified).

Thx for your contribution! ;)
