### ISSUE TITLE
[zh] Localize 'tightly_coupled_architectures'

### ISSUE THREAD

**Issue by Jacob953** [cncf/glossary#961]
- [ ] Localize the content/en/tightly_coupled_architectures.md to content/zh-cn/ in dev-zh.

**Comment by Petrie** [comment]
Hi  @Jacob953 , pls assign this to me. I translated it along with `lossely coupled architectures` 
#948

**Comment by Petrie** [comment]
Resolved by #1054

**Comment by hanyuancheung** [comment]
done
