### ISSUE TITLE
[zh] Localize 'security_chaos_engineering'

### ISSUE THREAD

**Issue by Jacob953** [cncf/glossary#970]
- [ ] Localize the content/en/security_chaos_engineering.md to content/zh-cn/ in dev-zh.

**Comment by devsachinsharma** [comment]
Can i work on this issue?

**Comment by Jacob953** [comment]
Of course. Please go ahead!

**Comment by Petrie** [comment]
I'll translate this, assign it me, ths. @Jacob953

**Comment by Petrie** [comment]
solve by https://github.com/cncf/glossary/pull/1091
