### ISSUE TITLE
[English] modify the content  in database_as_a_service.md

### ISSUE THREAD

**Issue by Submarinee** [cncf/glossary#984]
The origin text in database_as_a_service.md is:

> Database-as-a-Service (DBaaS) is a service managed by a [cloud](/cloud_computing/) operator (public or private) that supports applications without requiring the application team to perform traditional database administration functions.

The [cloud](/cloud_computing/)  actually links to cloud_computing doc. 
Do we need to update [cloud](/cloud_computing/)  to  [cloud computing](/cloud_computing/) ?

**Comment by jaynarayan-vaishnav** [comment]
I think the "cloud" suits perfectly well for this Explanation instead of "cloud computing"  grammatically.

**Comment by seokho-son** [comment]
Hi @Submarinee 
Thank you for the suggestion ! :)

I am one of the maintainers of this repo. I think most of people can understand the context with `cloud` without complete words `cloud computing`.

So, I hope to close this issue if you agree with it.

**Comment by Submarinee** [comment]
Thanks for all your comments. I agree with you.
