### ISSUE TITLE
[en] `auto_scaling` for `en`

### ISSUE THREAD

**Issue by Jacob953** [cncf/glossary#986]
#### Why this term needs to be updated? (briefly)
- Did not follow the template. https://github.com/cncf/glossary/blob/main/content/en/auto-scaling.md

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [X] I want to work on this suggestion. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by jihoon-seo** [comment]
@Jacob953 Thank you for the suggestion, but
please see [this](https://github.com/cncf/glossary/pull/627#issuecomment-1067889634):
> Autoscaling is a property and [properties don't follow that format](https://glossary.cncf.io/style-guide/#category).

I'll go ahead and close this issue. Again thank you for pointing out! 😊

**Comment by Jacob953** [comment]
Sry for the careless in searching. I'll take care next time. )
